import type { Column } from '../grid/index';
export type Condition={field:string;path?:string[];operator:string;values:string[];includeEmpty?:boolean;compareAs?:'raw'|'label'};
export type Filter={join:'and'|'or';conditions:(Condition|Filter)[]};
export const emptyFilter=():Filter=>({join:'and',conditions:[]});
export function FilterEditor({value,onChange,columns,compact=false,depth=0,allowFieldInput=false}:{value:Filter;onChange:(v:Filter)=>void;columns:Column[];compact?:boolean;depth?:number;allowFieldInput?:boolean}){
 const replace=(i:number,c:Condition|Filter)=>onChange({...value,conditions:value.conditions.map((x,n)=>n===i?c:x)});
 return <div className="filter-group"><div className="row"><strong>{depth?'조건 그룹':'필터'}</strong><select aria-label="조건 결합" value={value.join} onChange={e=>onChange({...value,join:e.target.value as 'and'|'or'})}><option value="and">AND · 모두 충족</option><option value="or">OR · 하나 이상</option></select><button onClick={()=>onChange({...value,conditions:[...value.conditions,{field:columns[0]?.field||'',operator:'equals',values:[]}]})}>+ 조건</button>{!compact&&<button onClick={()=>onChange({...value,conditions:[...value.conditions,emptyFilter()]})}>+ 그룹</button>}</div>
 {value.conditions.map((c,i)=><div className="filter-line" key={i}>{'conditions'in c?(compact?<div className="muted">상세 그룹 유지됨 · {c.conditions.length}개 조건 · 데스크탑에서 편집</div>:<FilterEditor columns={columns} value={c} depth={depth+1} allowFieldInput={allowFieldInput} onChange={v=>replace(i,v)}/>):<div className="condition">{allowFieldInput?<input aria-label="화면 조건 원천 키" placeholder="pointInfo 원천 키" value={c.field} onChange={e=>replace(i,{...c,field:e.target.value})}/>:<select aria-label="필터 열" value={c.field} onChange={e=>replace(i,{...c,field:e.target.value})}>{columns.map(col=><option key={col.field} value={col.field}>{col.label||col.field}</option>)}</select>}<input aria-label="JSON 경로" placeholder="JSON 경로 a.b (선택)" value={c.path?.join('.')||''} onChange={e=>replace(i,{...c,path:e.target.value?e.target.value.split('.'):undefined})}/><select value={c.operator} onChange={e=>replace(i,{...c,operator:e.target.value})}>{Object.entries({equals:'목록 중 일치',notEquals:'목록 모두 불일치',contains:'검색어 하나 포함',notContains:'검색어 모두 미포함',gt:'초과',gte:'이상',lt:'미만',lte:'이하',empty:'빈 값',notEmpty:'빈 값 아님'}).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><textarea aria-label="검색값 목록" placeholder="검색값을 한 줄에 하나씩 입력" value={c.values.join('\n')} onChange={e=>replace(i,{...c,values:e.target.value.split('\n')})}/><label><input type="checkbox" checked={!!c.includeEmpty} onChange={e=>replace(i,{...c,includeEmpty:e.target.checked})}/>빈값 포함</label><select value={c.compareAs||'raw'} onChange={e=>replace(i,{...c,compareAs:e.target.value as 'raw'|'label'})}><option value="raw">원값</option><option value="label">사전 표시값</option></select></div>}<button title="조건 삭제" onClick={()=>onChange({...value,conditions:value.conditions.filter((_,n)=>n!==i)})}>×</button></div>)}
 </div>;
}
