import { describe,it,expect } from 'vitest';
import { RecordView } from '../../apps/mvp/record-view';
import type { MvpSettings,ProcurementRecord } from '../../apps/mvp/contracts';
const settings:MvpSettings={theme:'light',extractionMode:'tables',hideEmptyColumns:true,hideUnmappedColumns:false,dictionary:{keys:{},values:{}},launchers:[]};
function record():ProcurementRecord{return{stage:'contract',identity:['N','01'],recordId:'test',storeVersion:1,fields:{ctrtNo:'N',ctrtChgOrd:'01',ctrtAmt:'100.5',dlvgdsTermYmd:'20261001','원본 JSON':'source-raw','종결':'source-closed','지정일':'source-date',goods:'source-goods'},userValues:{종결:false,지정일:'20261003',종결금액:'20.1'},children:[{key:'goods',label:'goods',kind:'items',rows:[{qty:0}]}],rawJson:'{"original":true}',source:{url:'https://g2b.go.kr',areaCd:'14',depth1:'01570',depth2:'01571',framePath:'top'},capturedAt:'now'};}
describe('source/user/display ownership',()=>{
 it('never overwrites same-named source fields with metadata or user values',()=>{const r=record(),v=new RecordView([r],'contract',settings),row=v.toRow(r);expect(row['원본 JSON']).toBe('source-raw');expect(row['종결']).toBe('source-closed');expect(row['지정일']).toBe('source-date');expect(row[v.rawKey]).toBe(r.rawJson);expect(row[v.completionKey]).toBe(false);expect(v.toEdit(r,row).fields).toEqual(r.fields);expect(v.toEdit(r,row).userValues).toEqual({...r.userValues,선금보증기한:'',선금보증금액:''});});
 it('never persists child projection aliases as user fields',()=>{const r=record(),v=new RecordView([r],'contract',settings),row=v.toRow(r);expect(row.goods).toBe('source-goods');expect(row[v.childNames.get('goods')!]).toEqual([{qty:0}]);expect(v.toEdit(r,row).userValues).not.toHaveProperty(v.childNames.get('goods')!);});
 it('keeps a source column and a user column with the same name separate',()=>{const r=record();r.userValues.goods='user-goods';const v=new RecordView([r],'contract',settings),row=v.toRow(r);expect(row.goods).toBe('source-goods');expect(row[v.userNames.get('goods')!]).toBe('user-goods');expect(v.toEdit(r,row).userValues.goods).toBe('user-goods');});
 it('never fills an empty user definition with a same-named source value',()=>{const r=record(),v=new RecordView([r],'contract',{...settings,userColumns:{contract:['goods']}}),row=v.toRow(r);expect(row.goods).toBe('source-goods');expect(row[v.userNames.get('goods')!]).toBe('');expect(v.toEdit(r,row).userValues.goods).toBe('');});
 it('defines empty user columns without materializing source fields',()=>{const r=record(),s={...settings,userColumns:{contract:['빈 사용자']}},v=new RecordView([r],'contract',s);expect(v.toRow(r)['빈 사용자']).toBe('');expect(v.toEdit(r,v.toRow(r)).userValues['빈 사용자']).toBe('');expect(v.definitionNames(v.userKeys)).toContain('빈 사용자');});
 it('keeps user definitions in zero-record views',()=>{const v=new RecordView([],'receipt',{...settings,userColumns:{receipt:['빈 열']}});expect(v.userKeys).toEqual(['빈 열']);});
 it('does not resurrect deleted definitions from rows outside the active filter',()=>{const r=record();r.stage='receipt';r.userValues={메모:'hidden row value'};const v=new RecordView([r],'receipt',{...settings,userColumns:{receipt:[]}});expect(v.userKeys).toEqual([]);expect(v.toRow(r)).not.toHaveProperty('메모');expect(v.toEdit(r,v.toRow(r)).userValues).toEqual(r.userValues);});
 it('removes a visible user column definition without erasing its stored value',()=>{const r=record();r.stage='receipt';r.userValues={메모:'preserved value'};const v=new RecordView([r],'receipt',settings),row=v.toRow(r);delete row.메모;expect(v.definitionNames([])).toEqual([]);expect(v.toEdit(r,row).userValues.메모).toBe('preserved value');});
 it('recalculates only separate derived aliases',()=>{const r=record(),v=new RecordView([r],'contract',settings),row=v.toRow(r);row[v.userNames.get('종결금액')!]='90.25';const patch=v.derive(row);expect(patch[v.userNames.get('지체일수')!]).toBe(2);expect(patch[v.userNames.get('미종결금액')!]).toBe('10.25');expect(Object.keys(patch)).toHaveLength(2);expect(row['지정일']).toBe('source-date');});
 it('rejects a silently lost edit to a source field absent on the row',()=>{const r=record(),other=record();other.fields.onlyOther='original';const v=new RecordView([r,other],'contract',settings),row=v.toRow(r);row.onlyOther='typed';expect(()=>v.toEdit(r,row)).toThrow('없는 원천 열');});
});
