import {installPagePanels} from './page-panels';
import {applyTheme} from './theme';
import {matchesNoteScreen,noteLabel,sortNotes} from './features/notes-model';
// Isolated-world entry. Page values are displayed as text, never executable markup.
(() => {
  const existing=document.getElementById('pce-extension-widget');
  if(existing){existing.hidden=!existing.hidden;return;}
  const host=document.createElement('div');host.id='pce-extension-widget';
  Object.assign(host.style,{position:'fixed',right:'18px',top:'90px',width:'340px',maxWidth:'calc(100vw - 16px)',zIndex:'2147483646'});
  const shadow=host.attachShadow({mode:'open'});
  shadow.innerHTML=`<style>
  :host{all:initial}*{box-sizing:border-box}section{position:relative;z-index:2147483647;font:12px/1.5 'Segoe UI','Malgun Gothic',sans-serif;color:#eef1f5;background:#191c22;border:1px solid #353b46;border-radius:12px;box-shadow:0 8px 28px #173f332b;overflow:hidden}header{background:#232831;color:white;display:flex;align-items:center;gap:6px;padding:9px 12px;cursor:move;touch-action:none}header strong{flex:1}button,input,select{font:inherit}button{cursor:pointer;border:1px solid #454c58;border-radius:6px;background:#22262e;color:#eef1f5;padding:6px 9px}button:hover{background:#303745}button:focus-visible,input:focus-visible{outline:2px solid #6f8cff;outline-offset:2px}button[disabled]{opacity:.5;cursor:wait}header button{border:0;background:transparent;color:white;padding:0 6px}nav{display:flex;padding:8px;gap:4px;border-bottom:1px solid #353b46}nav button{flex:1;padding:5px 3px;border:0}nav button[aria-selected=true]{background:#36466d;color:#dce5ff;font-weight:700}.body{padding:12px;max-height:65vh;overflow:auto}.row{display:flex;gap:6px;align-items:center;margin:7px 0}.row>*{min-width:0}input,select{color:#eef1f5;background:#22262e}input[type=number]{width:80px;padding:5px;border:1px solid #454c58;border-radius:4px}label{font-size:12px}p{margin:6px 0}h3{font-size:13px;margin:12px 0 6px}hr{border:0;border-top:1px solid #353b46;margin:12px 0}.muted{color:#a2aab7;font-size:12px}.card{display:block;width:100%;text-align:left;margin:6px 0;padding:8px}.launch-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px}.launch-slot{position:relative;min-width:0}.launch-slot .card{height:100%;margin:0;padding-right:24px}.launch-edit{position:absolute;right:2px;top:3px;padding:3px;border:0;background:transparent}.card.note{background:#fff2b8;color:#393627;border-color:#dfce8c}.card.note small{color:#6d6448}.card small{display:block;color:#a2aab7;white-space:pre-wrap}.status{font-size:12px;background:#111318;padding:8px 12px;max-height:95px;overflow:auto;white-space:pre-wrap}.error{color:#ff9c91}.four,.three{display:grid;gap:5px;margin:5px 0}.four{grid-template-columns:repeat(4,1fr)}.three{grid-template-columns:repeat(3,1fr)}details{margin-top:6px}summary{cursor:pointer;color:#a2aab7}.two{display:grid;grid-template-columns:1fr 1fr;gap:7px}[hidden]{display:none!important}
  </style><section aria-label="PCE 업무 위젯"><header><strong>PCE · 업무 도우미</strong><button data-do="refresh" title="새로고침">↻</button><button data-do="collapse" aria-label="위젯 접기">−</button><button data-do="close" aria-label="위젯 닫기">×</button></header><div class="expanded"><nav role="tablist"><button role="tab" data-tab="work" aria-selected="true">업무</button><button role="tab" data-tab="notes">메모/일정</button><button role="tab" data-tab="launcher">런처</button><button role="tab" data-tab="db">DB</button></nav><div class="body"></div><div class="status" role="status">연결 확인 중…</div></div></section>`;
  document.documentElement.append(host);
  installPagePanels(host,shadow);
  const body=shadow.querySelector('.body') as HTMLElement,status=shadow.querySelector('.status') as HTMLElement;
  let tab='work',context:any={},collapsed=false,automatic=false,noteMode='all',noteSearch='',noteSort='updated';
  const message=async(value:Record<string,unknown>)=>{const result=await chrome.runtime.sendMessage(value);if(result?.error)throw new Error(typeof result.error==='string'?result.error:result.error.message);return result;};
  const sql=async(command:string,payload:unknown={})=>{const result=await message({type:'gateway',request:{protocolVersion:1,requestId:crypto.randomUUID(),command,payload}});return result.result;};
  const report=(text:string,error=false)=>{status.textContent=text;status.classList.toggle('error',error);};
  const open=(surface:string,extra:object={})=>message({type:'surface.open',surface,...extra});
  const themeStyle=document.createElement('style');themeStyle.textContent=`section,header,nav,.body,.status{background:var(--pce-bg);color:var(--pce-text);border-color:var(--pce-border)}button,input,select{background:var(--pce-panel);color:var(--pce-text);border-color:var(--pce-border)}header button{color:var(--pce-text)}button:hover{background:var(--pce-hover)}nav button[aria-selected=true],button[aria-pressed=true]{background:var(--pce-hover);color:var(--pce-accent)}.muted,summary,.card small{color:var(--pce-muted)}.note-nav{display:flex;gap:3px;margin-bottom:8px}.note-nav button{flex:1;padding:5px 2px}.note-tools{display:flex;gap:5px}.note-tools input{width:0;flex:1;padding:5px;border:1px solid var(--pce-border);border-radius:5px}.note-tools select{width:76px;border:1px solid var(--pce-border);border-radius:5px}.note-list{margin-top:8px}.card.note{min-height:78px;border:0;box-shadow:0 1px 2px #0001}.card.note small{color:inherit;max-height:58px;overflow:hidden}.card.note[data-color=green]{background:#e0efcf}.card.note[data-color=blue]{background:#daebfa}.card.note[data-color=pink]{background:#f9dfe5}.card.note[data-color=plain]{background:var(--pce-panel);color:var(--pce-text)}.count-combo{position:relative;flex:1}.count-combo input{width:100%!important;padding-right:25px!important}.count-combo>button{position:absolute;right:1px;top:1px;padding:3px 6px;border:0}.count-options{position:absolute;top:100%;left:0;right:0;z-index:5;display:flex;flex-direction:column;background:var(--pce-panel);border:1px solid var(--pce-border);border-radius:5px;padding:3px}.count-options button{text-align:left;border:0;padding:4px 8px}`;shadow.append(themeStyle);
  const settingsButton=document.createElement('button');settingsButton.textContent='⚙';settingsButton.title='설정';settingsButton.setAttribute('aria-label','설정');settingsButton.dataset.open='settings';shadow.querySelector('header strong')!.after(settingsButton);
  async function readTheme(){try{const setting=await sql('settings.read',{key:'ui.appearance'});applyTheme(host,setting.value?.theme);}catch{applyTheme(host,'light');}}
  chrome.runtime.onMessage.addListener((incoming,sender)=>{if(sender.id===chrome.runtime.id&&incoming.type==='ui.refresh'){void readTheme();if(tab==='notes'||tab==='launcher')void render().catch(error=>report(String(error),true));}});
  async function render(){
    shadow.querySelectorAll('[data-tab]').forEach(button=>button.setAttribute('aria-selected',String((button as HTMLElement).dataset.tab===tab)));
    body.replaceChildren();
    if(tab==='work')body.innerHTML=`<div class="four"><button data-do="previous" title="기간을 1년 이전으로 변경">−1년</button><button data-do="next" title="기간을 1년 이후로 변경">+1년</button><button data-do="search">조회</button><button data-do="excel">엑셀</button></div><div class="row"><label for="count">건수</label><div class="count-combo"><input id="count" aria-label="조회 건수" role="combobox" aria-expanded="false" aria-controls="count-options" type="number" min="1" value="100"><button data-do="count-options" aria-label="조회 건수 목록">▾</button><div id="count-options" class="count-options" role="listbox" hidden>${[10,30,50,100,250,500,1000].map(value=>`<button role="option" data-count="${value}">${value}</button>`).join('')}</div></div><button data-do="count">적용</button></div><label><input type="checkbox" id="searchAfter"> 기간 변경 후 조회</label><hr><div class="three"><button data-do="${automatic?'stop':'start'}" title="이 탭의 등록 조건에 맞춰 자동 수집">${automatic?'자동 정지':'자동 시작'}</button><button data-do="once" title="등록 조건에 맞는 자료를 한 번 수집">1회 수집</button><button data-open="extract">추출</button></div><button data-open="aggregate" class="card">Excel 취합</button>`;
    if(tab==='db')body.innerHTML='<div class="two"><button data-open="db">DB 브라우저</button><button data-open="dictionary">사전 관리</button><button data-open="collection">수집 관리</button><button data-open="db" data-mode="relations">관계·통합 뷰</button></div>';
    if(tab==='launcher'){
      body.innerHTML='<div class="row"><strong style="flex:1">런처</strong><button data-open="launcher" data-mode="add" title="바로가기 추가">+</button><button data-open="launcher">설정</button></div><div class="two"><button data-open="documents">문서 생성</button><button data-open="explorer">업무 폴더</button></div><div class="launch-grid"></div>';
      const result=await sql('table.read',{sourceId:'launchers',limit:100});
      if(tab!=='launcher')return;
      for(const row of result.rows){const button=document.createElement('button');button.className='card';button.textContent=String(row.name||'이름 없는 바로가기');button.dataset.launch=row.__rowId;button.title=String(row.description||row.target||'');const small=document.createElement('small');small.textContent=String(row.description||row.kind||'');button.append(small);const slot=document.createElement('div');slot.className='launch-slot';slot.append(button);body.querySelector('.launch-grid')!.append(slot);const edit=document.createElement('button');edit.textContent='⋮';edit.title='바로가기 설정';edit.dataset.open='launcher';edit.dataset.row=row.__rowId;edit.className='launch-edit';slot.append(edit);}
    }
    if(tab==='notes'){
      body.innerHTML=`<div class="note-nav">${[['all','전체'],['memos','메모'],['manager','관리'],['schedules','일정'],['calendar','달력']].map(([mode,label])=>`<button data-note-mode="${mode}" aria-pressed="${noteMode===mode}">${label}</button>`).join('')}</div><div class="note-tools"><input aria-label="메모·일정 검색" type="search"><select aria-label="메모 정렬"><option value="updated">최근 수정</option><option value="created">최근 생성</option><option value="title">제목</option><option value="date">날짜</option></select><button data-open="notes" data-mode="sticky" data-source="${noteMode==='schedules'?'schedules':'memos'}" aria-label="새 ${noteMode==='schedules'?'일정':'메모'}">+</button></div><div class="note-list"></div>`;
      const search=body.querySelector<HTMLInputElement>('[type=search]')!;search.value=noteSearch;
      const sort=body.querySelector<HTMLSelectElement>('select')!;sort.value=noteSort;
      const results=await Promise.all(['memos','schedules'].map(sourceId=>sql('table.read',{sourceId,limit:1000})));
      if(tab!=='notes')return;
      const all=results.flatMap((result,index)=>result.rows.map((row:any)=>({...row,kind:index?'schedules':'memos'})));
      const draw=()=>{const list=body.querySelector('.note-list');if(!list)return;list.replaceChildren();const rows=sortNotes(all.filter(row=>row.trashed!==true&&matchesNoteScreen(row.screenKey,context.screenKey||'')&&(noteMode==='all'||row.kind===noteMode)&&(!noteSearch||JSON.stringify([row.title,row.body,row.start]).toLocaleLowerCase().includes(noteSearch.toLocaleLowerCase()))),noteSort as any);
       for(const row of rows.slice(0,30)){const button=document.createElement('button');button.className='card note';button.dataset.open='notes';button.dataset.row=row.__rowId;button.dataset.mode='sticky';button.dataset.source=row.kind;button.dataset.color=String(row.color||'yellow');button.textContent=(row.important?'★ ':'')+noteLabel(row)+(row.screenKey?' ⌖':'');const detail=document.createElement('small');detail.textContent=String(row.kind==='schedules'?(row.start||'')+' '+(row.body||''):row.body||'');button.append(detail);list.append(button);}
      };search.oninput=()=>{noteSearch=search.value;draw();};sort.onchange=()=>{noteSort=sort.value;draw();};draw();
    }
  }

  async function refresh(){await render();try{context=await message({type:'context.read'});const state=await message({type:'capture',mode:'status'});automatic=!!state.active;const toggle=shadow.querySelector('[data-do=start],[data-do=stop]') as HTMLButtonElement|null;if(toggle){toggle.dataset.do=automatic?'stop':'start';toggle.textContent=automatic?'자동 정지':'자동 시작';}report((state.active?'자동 수집 중 · ':'자동 수집 정지 · ')+location.hostname+(state.last?.error?'\n'+state.last.error:''));}catch(error){report(String(error),true);}}
  shadow.addEventListener('click',async event=>{
    if(!event.isTrusted)return;
    const button=(event.target as Element).closest('button') as HTMLButtonElement|null;if(!button||button.closest('.pce-window'))return;
    try{
      if(button.dataset.tab){if(tab===button.dataset.tab){collapsed=!collapsed;body.hidden=collapsed;return;}collapsed=false;body.hidden=false;tab=button.dataset.tab;if(tab==='notes')context=await message({type:'context.read'});await render();return;}
      if(button.dataset.count){(body.querySelector('#count') as HTMLInputElement).value=button.dataset.count;(body.querySelector('#count-options') as HTMLElement).hidden=true;body.querySelector('#count')?.setAttribute('aria-expanded','false');return;}
      if(button.dataset.noteMode){const mode=button.dataset.noteMode;if(mode==='manager'||mode==='calendar'){await open('notes',{mode});return;}noteMode=mode;await render();return;}
      if(button.dataset.open){await open(button.dataset.open,{mode:button.dataset.mode,rowId:button.dataset.row,sourceId:button.dataset.source});return;}
      if(button.dataset.launch){await message({type:'launcher.run',rowId:button.dataset.launch});report('바로가기 실행 요청 완료');return;}
      const action=button.dataset.do;
      if(action==='collapse'){collapsed=!collapsed;(shadow.querySelector('.expanded') as HTMLElement).hidden=collapsed;button.textContent=collapsed?'+':'−';button.setAttribute('aria-label',collapsed?'위젯 펼치기':'위젯 접기');return;}
      if(action==='close'){host.hidden=true;return;}
      if(action==='refresh'){await refresh();return;}
      if(action==='count-options'){const list=body.querySelector<HTMLElement>('#count-options')!;list.hidden=!list.hidden;body.querySelector('#count')?.setAttribute('aria-expanded',String(!list.hidden));return;}
      button.disabled=true;
      if(['start','stop','once'].includes(action||'')){const result=await message({type:'capture',mode:action});report(action==='stop'?(result.inFlight?'자동 수집 정지 · 전송 중 저장은 완료될 수 있습니다.':'자동 수집 정지') :action==='start'?'이 탭에서 자동 수집을 시작했습니다.':'원본 수집 완료 · 수집 관리에서 변경을 검토하세요.');if(action==='once')await open('collection');if(action==='start'||action==='stop'){automatic=!!result.active;button.dataset.do=automatic?'stop':'start';button.textContent=automatic?'자동 정지':'자동 시작';}if(result.cancelled)report('자동 시작이 취소되었습니다.');return;}
      const year=Number((shadow.querySelector('#year') as HTMLInputElement)?.value),rowCount=Number((shadow.querySelector('#count') as HTMLInputElement)?.value),searchAfter=(shadow.querySelector('#searchAfter') as HTMLInputElement)?.checked;
      const request=action==='previous'||action==='next'?{kind:'yearShift',years:action==='previous'?-1:1,searchAfter}:action==='year'||action==='yearSearch'?{kind:'yearRange',year,searchAfter:action==='yearSearch'}:action==='count'?{kind:'setRowCount',rowCount}:{kind:action};
      const result=await message({type:'work.action',action:{...request,mode:'apply'}});report(result.message||JSON.stringify(result));const startChange=result.changes?.find((change:any)=>change.role==='startDate');if(startChange){const matched=String(startChange.after).match(/^([0-9]{4})/);const input=shadow.querySelector('#year') as HTMLInputElement|null;if(matched&&input)input.value=matched[1];}if(result.status==='needsSelection')await open('work');
    }catch(error){report(String(error),true);}finally{button.disabled=false;}
  });
  const header=shadow.querySelector('header')!;let drag:{x:number;y:number;left:number;top:number}|null=null;
  header.addEventListener('pointerdown',event=>{const e=event as PointerEvent;if(!e.isTrusted||e.button!==0||(e.target as Element).closest('button'))return;const rect=host.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:rect.left,top:rect.top};header.setPointerCapture(e.pointerId);});
  header.addEventListener('pointermove',event=>{const e=event as PointerEvent;if(!drag)return;host.style.right='auto';host.style.left=Math.max(8,Math.min(innerWidth-host.offsetWidth-8,drag.left+e.clientX-drag.x))+'px';host.style.top=Math.max(8,Math.min(innerHeight-40,drag.top+e.clientY-drag.y))+'px';});
  header.addEventListener('pointerup',()=>{drag=null;});header.addEventListener('pointercancel',()=>{drag=null;});
  void readTheme();void refresh();
})();
