import {useEffect,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {ExtractionPanel} from './ExtractionPanel';
type Binding={name:string;start:string;end:string;search:string;excel:string;count:string};
const initial:Binding={name:'현재 업무 화면',start:'',end:'',search:'',excel:'',count:''};
export function BrowserWorkPanel({labels,report,onDataset,onRule}:{labels:Record<string,string>;report:(s:string)=>void;onDataset:(name:string,rows:any[],columns:any[])=>Promise<void>;onRule:(dataset:string)=>void}){
 const [binding,setBinding]=useState<Binding>(initial),[version,setVersion]=useState<number>(),[start,setStart]=useState(''),[end,setEnd]=useState(''),[days,setDays]=useState('7'),[extraction,setExtraction]=useState<any>(null),[status,setStatus]=useState<any>(null);
 useEffect(()=>{request('settings.read',{key:'screen.bindings'}).then(r=>{setBinding({...initial,...r.value?.browserWork});setVersion(r.storeVersion);}).catch(e=>report(String(e)));},[]);
 async function send(message:any){if(typeof chrome==='undefined'||!chrome.runtime?.id)throw Error('이 명령은 브라우저 확장 Side Panel에서 실행하세요.');const result=await chrome.runtime.sendMessage(message);if(result?.error)throw Error(typeof result.error==='string'?result.error:JSON.stringify(result.error));return result;}
 async function action(kind:string,selector:string,value?:string,amount?:number){try{if(!selector.trim())throw Error('업무 요소 선택자를 먼저 설정하세요.');const result=await send({type:'page.action',action:{kind,selector,value,days:amount}});if(kind==='readText')setStatus({rowCount:result});report('업무 화면 명령 완료');return true;}catch(e){report(String(e));return false;}}
 async function capture(mode:string){try{const r=await send({type:'capture',mode});if(mode==='extract')setExtraction(r);if(mode==='status'||mode==='start'||mode==='stop'||mode==='once')setStatus(r);report(mode==='stop'?'수집 정지 요청 완료':r.reviewPending?'원본 보관 완료 · 수집 관리자에서 비교 후 반영하세요.':'수집 명령 완료');}catch(e){report(String(e));}}
 return <><section className="panel"><h3>현재 브라우저 업무 화면</h3><div className="row"><button onClick={()=>capture('once')}>1회 수집</button><button onClick={()=>capture('start')}>자동 시작</button><button onClick={()=>capture('stop')}>정지</button><button onClick={()=>capture('status')}>수집 상태</button><button onClick={()=>capture('extract')}>임시 추출</button></div><p className="muted">현재 로딩된 자료만 수집합니다. 충돌은 수집 관리자에서 검토하세요.</p><details><summary>업무 화면 요소 설정 · 사용자 확인 선택자</summary>{(Object.entries({name:'화면 이름',start:'시작 날짜 입력',end:'종료 날짜 입력',search:'조회 버튼',excel:'Excel 다운로드 버튼',count:'건수 표시'}) as [keyof Binding,string][]).map(([key,label])=><label className="binding-field" key={key}>{label}<input aria-label={label+' 선택자'} value={binding[key]} onChange={e=>setBinding({...binding,[key]:e.target.value})} placeholder={key==='name'?'화면 이름':'CSS 선택자 · 정확히 한 요소'}/></label>)}<button onClick={async()=>{try{const previous=await request('settings.read',{key:'screen.bindings'});const saved=await request('settings.save',{key:'screen.bindings',storeVersion:version,value:{...previous.value,browserWork:binding}});setVersion(saved.storeVersion);report('업무 요소 설정 저장 완료');}catch(e){report(String(e));}}}>요소 설정 저장</button></details><div className="row"><label>시작<input aria-label="업무 시작 날짜" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><button disabled={!start} onClick={()=>action('setValue',binding.start,start)}>시작 날짜 입력</button><label>종료<input aria-label="업무 종료 날짜" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button disabled={!end} onClick={()=>action('setValue',binding.end,end)}>종료 날짜 입력</button><label>이동 일수<input aria-label="업무 날짜 이동 일수" type="number" value={days} onChange={e=>setDays(e.target.value)}/></label><button onClick={async()=>{if(!Number.isInteger(Number(days))){report('정수 일수를 입력하세요.');return;}if(await action('dateShift',binding.start,undefined,Number(days)))await action('dateShift',binding.end,undefined,Number(days));}}>기간 이동</button><button onClick={()=>action('click',binding.search)}>조회</button><button onClick={()=>action('readText',binding.count)}>건수 확인</button><button onClick={()=>action('click',binding.excel)}>Excel 다운로드</button></div>{status&&<pre>{JSON.stringify(status,null,2)}</pre>}</section>{extraction?.payload&&<ExtractionPanel payload={extraction.payload} bundle={extraction.bundle} labels={labels} onDataset={onDataset} onRule={onRule}/>}</>;
}
