import {useState} from 'react';
import {aggregateDecimal,evaluateCalculation,shiftDate} from '../../../plugins/core';
import type {Column,RecordRow} from '../Grid';
export function CalculationPanel({columns,rows,selected,onApply,report}:{columns:Column[];rows:RecordRow[];selected:()=>RecordRow[];onApply:(rows:RecordRow[])=>void;report:(message:string)=>void}){
 const [field,setField]=useState(''),[target,setTarget]=useState(''),[expression,setExpression]=useState(''),[days,setDays]=useState('1'),[result,setResult]=useState('');
 const selection=()=>{const chosen=selected();if(!chosen.length)throw Error('계산할 셀 범위를 선택하세요.');const ids=new Set(chosen.map(r=>r.__rowId));return rows.filter(r=>ids.has(r.__rowId));};
 function apply(kind:'formula'|'date'){try{if(!columns.some(c=>c.field===target&&c.editable!==false))throw Error('편집할 결과 열을 선택하세요.');const chosen=selection(),updates=new Map(chosen.map(r=>[r.__rowId,kind==='formula'?evaluateCalculation(expression,r):shiftDate(String(r[field]??''),Number(days))]));onApply(rows.map(r=>updates.has(r.__rowId)?{...r,[target]:updates.get(r.__rowId)}:r));report(`${chosen.length}행 계산 결과를 편집 버퍼에 적용했습니다. 저장으로 확정하세요.`);}catch(e){report(String(e));}}
 return <details className="calculation"><summary>선택 범위 계산 · 합계/평균 · 날짜 이동</summary><div className="row"><label>기준 열<select aria-label="계산 기준 열" value={field} onChange={e=>setField(e.target.value)}><option value="">열 선택</option>{columns.map(c=><option key={c.field} value={c.field}>{c.label||c.field}</option>)}</select></label>{(['sum','average'] as const).map(operation=><button key={operation} onClick={()=>{try{if(!field)throw Error('집계할 열을 선택하세요.');setResult(aggregateDecimal(selection().map(r=>r[field]),operation));}catch(e){report(String(e));}}}>{operation==='sum'?'합계':'평균'}</button>)}{result!==''&&<output aria-label="집계 결과">{result}</output>}</div><div className="row"><label>결과 열<select aria-label="계산 결과 열" value={target} onChange={e=>setTarget(e.target.value)}><option value="">열 선택</option>{columns.filter(c=>c.editable!==false).map(c=><option key={c.field} value={c.field}>{c.label||c.field}</option>)}</select></label><input aria-label="계산식" value={expression} onChange={e=>setExpression(e.target.value)} placeholder="[amount] * 1.1"/><button onClick={()=>apply('formula')}>수식 적용</button><label>이동 일수<input type="number" step="1" aria-label="날짜 이동 일수" value={days} onChange={e=>setDays(e.target.value)}/></label><button disabled={!field} onClick={()=>apply('date')}>날짜 이동 적용</button></div></details>;
}
