import {useEffect,useMemo,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {DataGrid,type RecordRow} from '../Grid';
import {FilterEditor,emptyFilter} from '../Filter';
import {download} from '../ImportExport';
const arr=(v:any)=>Array.isArray(v)?v:v?.relations||v?.captures||v?.rows||[];
export function CapturePanel({report,gridList=false}:{report:(s:string)=>void;gridList?:boolean}){
 const [captures,setCaptures]=useState<any[]>([]),[review,setReview]=useState<any>(null),[captureId,setCaptureId]=useState(''),[chosen,setChosen]=useState<Record<string,string[]>>({}),[raw,setRaw]=useState<any>();
 const [selected,setSelected]=useState<any>();
 const captureRows=useMemo(()=>captures.map(c=>({...c,__rowId:c.captureId||c.id})),[captures]);
 const captureColumns=useMemo(()=>[{field:'capturedAt',label:'수집 시각'},{field:'status',label:'상태'},{field:'sourceUrl',label:'원천 화면'},{field:'captureId',label:'이벤트 ID'}],[]);
 const load=()=>request('capture.list').then(v=>setCaptures(arr(v))).catch(e=>report(String(e)));useEffect(()=>{load();},[]);
 async function preview(id:string){try{setCaptureId(id);const result=await request('collector.preview',{captureId:id});setReview(result);setChosen(Object.fromEntries((result.records||[]).map((r:any)=>[r.recordKey,r.changes.filter((c:any)=>!c.conflict).map((c:any)=>c.field)])));}catch(e){report(String(e));}}
 return <section className="panel"><h2>수집 관리자</h2><p className="muted">원본과 정규화 반영은 분리됩니다. 충돌은 필드별로 선택하세요.</p><label className="file-button">수집 JSON 가져오기 (이전 파일 호환)<input type="file" accept=".json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;const result=await request('capture.import',{bundle:JSON.parse(await file.text())});report('전달 묶음 검증·보관 완료');await load();if(result.captureIds?.[0])preview(result.captureIds[0]);}catch(err){report(String(err));}}}/></label><button onClick={load}>새로고침</button>{gridList?<><div className="row"><span>{captures.length}건</span><button disabled={!selected} onClick={()=>preview(selected.__rowId)}>변경 검토</button><button disabled={!selected} onClick={async()=>{try{setRaw(await request('capture.read',{captureId:selected.__rowId}));}catch(e){report(String(e));}}}>원본 보기</button></div><div className="capture-grid" style={{height:240}}><DataGrid rows={captureRows} columns={captureColumns} readOnly onSelect={setSelected}/></div></>:<div className="capture-list">{captures.map(c=><div className="row" key={c.captureId||c.id}><button onClick={()=>preview(c.captureId||c.id)}>{c.capturedAt||c.createdAt||c.captureId||c.id}</button><span>{c.status} {c.sourceUrl||c.origin}</span><button onClick={async()=>{try{setRaw(await request('capture.read',{captureId:c.captureId||c.id}));}catch(e){report(String(e));}}}>원본</button></div>)}</div>}{raw&&<details open><summary>원본 확인 <button onClick={()=>download('capture.json',JSON.stringify(raw,null,2))}>JSON 출력</button></summary><pre>{JSON.stringify(raw,null,2)}</pre></details>}{review&&<><p>{review.status} {(review.warnings||[]).join(' · ')}</p>{review.records?.map((r:any)=><fieldset key={r.recordKey}><legend>{r.sourceId} · {JSON.stringify(r.identity)} · {r.isNew?'신규':'기존 비교'}</legend>{r.changes.map((c:any)=><label className={'review-field '+(c.conflict?'conflict':'')} key={c.field}><input type="checkbox" disabled={!c.conflict} checked={!c.conflict||chosen[r.recordKey]?.includes(c.field)||false} onChange={e=>setChosen({...chosen,[r.recordKey]:e.target.checked?[...(chosen[r.recordKey]||[]),c.field]:(chosen[r.recordKey]||[]).filter(f=>f!==c.field)})}/><strong>{c.field}</strong><span>{JSON.stringify(c.previous)} → {JSON.stringify(c.incoming)}</span><em>{c.conflict?'충돌 · 선택 승인':'신규/보완 · 자동 반영'}</em></label>)}</fieldset>)}<button className="primary" onClick={async()=>{try{await request('collector.apply',{captureId,previewToken:review.previewToken,decisions:review.records.map((r:any)=>({recordKey:r.recordKey,storeVersion:r.storeVersion,fields:chosen[r.recordKey]||[]}))});report('선택 필드 반영 완료');setReview(null);load();}catch(e){report(String(e));}}}>선택 필드 반영</button></>}</section>;
}
