import {FilterEditor,emptyFilter} from '../Filter';
export type CollectionRule={sourceId:string;dataset:string;identityFields:string[];enabled?:boolean;screenFilter?:any;urlFilter?:any;[key:string]:any};
const asGroup=(filter:any)=>!filter?emptyFilter():'join' in filter?filter:{join:'and',conditions:[filter]};
function UrlCondition({value,onChange}:{value:any;onChange:(value:any)=>void}){
 const conditions=value&&'join' in value?value.conditions:value?[value]:[];
 const simple=!value||(value.join!=='or'&&conditions.length<=1&&conditions.every((condition:any)=>condition.field==='url'&&['equals','contains'].includes(condition.operator)&&(condition.values?.length||0)<=1&&!condition.path?.length&&!condition.includeEmpty&&(!condition.compareAs||condition.compareAs==='raw')));
 const condition=simple?conditions[0]:undefined;
 const setSimple=(operator:string,text:string)=>onChange(text.trim()?{join:'and',conditions:[{field:'url',operator,values:[text]}]}:undefined);
 return <div className="url-condition"><p>URL 조건 · 같은 Frame의 화면 조건과 함께 확인</p>{simple?<div className="row"><label>URL 비교<select aria-label="규칙 URL 비교" value={condition?.operator||'contains'} onChange={event=>onChange({join:'and',conditions:[{field:'url',operator:event.target.value,values:condition?.values||[]}]})}><option value="contains">포함</option><option value="equals">정확히 일치</option></select></label><label>URL 또는 주소 일부<input aria-label="규칙 URL 조건" placeholder="빈칸은 URL 제한 없음" value={condition?.values?.[0]||''} onChange={event=>setSimple(condition?.operator||'contains',event.target.value)}/></label></div>:<p className="muted">저장된 복합 URL 조건을 유지하고 있습니다. 아래 상세 조건에서 수정하세요.</p>}<details><summary>URL 상세 조건 · AND/OR</summary><FilterEditor columns={[{field:'url',label:'Frame URL'}]} value={asGroup(value)} onChange={onChange}/></details></div>;
}
export function CollectionRuleEditor({rules,sources,onChange}:{rules:CollectionRule[];sources:any[];onChange:(rules:CollectionRule[])=>void}){
 const update=(i:number,values:Partial<CollectionRule>)=>onChange(rules.map((rule,n)=>n===i?{...rule,...values}:rule));
 return <div className="rule-editor"><p className="muted">원본 Dataset과 업무 식별 열을 지정합니다. URL·화면·Dataset 조건은 같은 Frame에서 함께 확인합니다. 기본 업무 분류를 끄고 규칙도 비우면 수집하지 않습니다.</p>{rules.map((rule,i)=>{const source=sources.find(s=>s.sourceId===rule.sourceId);const fields=[...new Set<string>([...(source?.columns||[]).map((c:any)=>c.field),...rule.identityFields])];return <fieldset key={i}><legend>수집 규칙 {i+1}</legend><div className="row"><label><input type="checkbox" checked={rule.enabled!==false} onChange={e=>update(i,{enabled:e.target.checked})}/>사용</label><label>대상 표<select aria-label="규칙 대상 표" value={rule.sourceId} onChange={e=>update(i,{sourceId:e.target.value})}><option value="">선택</option>{sources.map(s=><option key={s.sourceId} value={s.sourceId}>{s.label}</option>)}</select></label><label>원본 Dataset<input aria-label="규칙 Dataset 키" value={rule.dataset||''} placeholder="$pointInfo 또는 원본 표 키" onChange={e=>update(i,{dataset:e.target.value})}/></label><button onClick={()=>onChange(rules.filter((_,n)=>n!==i))}>규칙 삭제</button></div><p>업무 식별 열 · 저장 중복 정책과 별도</p><div className="row">{fields.map(field=><label key={field}><input type="checkbox" checked={rule.identityFields.includes(field)} onChange={e=>update(i,{identityFields:e.target.checked?[...rule.identityFields,field]:rule.identityFields.filter(k=>k!==field)})}/>{field}</label>)}</div><label>추가 식별 원천 키<input aria-label="추가 규칙 식별 키" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const key=e.currentTarget.value.trim();if(key&&!rule.identityFields.includes(key))update(i,{identityFields:[...rule.identityFields,key]});e.currentTarget.value='';}}} placeholder="키 입력 후 Enter"/></label><UrlCondition value={rule.urlFilter} onChange={urlFilter=>update(i,{urlFilter})}/><details><summary>화면 조건 · 중첩 AND/OR</summary><FilterEditor columns={fields.map(field=>({field}))} allowFieldInput value={asGroup(rule.screenFilter)} onChange={screenFilter=>update(i,{screenFilter})}/></details></fieldset>;})}<button onClick={()=>onChange([...rules,{sourceId:sources[0]?.sourceId||'',dataset:'$pointInfo',identityFields:[],enabled:true}])}>+ 수집 규칙</button></div>;
}
