import {useEffect,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import type {RecordRow} from '../Grid';
export function ContextLinksPanel({sourceId,row,report}:{sourceId:string;row:RecordRow;report:(s:string)=>void}){
 const [linked,setLinked]=useState<Record<string,any>>({}),[title,setTitle]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState('');
 const filter={join:'and',conditions:[{field:'sourceId',operator:'equals',values:[sourceId]},{field:'rowId',operator:'equals',values:[row.__rowId]}]};
 async function load(){const results=await Promise.all(['memos','schedules','file_links'].map(async source=>[source,await request('table.read',{sourceId:source,filter,limit:1000})] as const));return Object.fromEntries(results);}
 useEffect(()=>{let current=true;const update=()=>{if(row.__rowId.startsWith('new-')){setLinked({});return;}load().then(value=>{if(current)setLinked(value);}).catch(e=>report(String(e)));};update();window.addEventListener('pce-linked-saved',update);return()=>{current=false;window.removeEventListener('pce-linked-saved',update);};},[sourceId,row.__rowId]);
 return <><details><summary>연결된 메모·일정·파일</summary>{(['memos','schedules','file_links'] as const).map(source=><section key={source}><h4>{({memos:'메모',schedules:'일정',file_links:'파일'})[source]} · {linked[source]?.rowCount||0}</h4>{linked[source]?.rows.map((item:RecordRow)=><div className="context-link" key={item.__rowId}>{source==='file_links'?<button onClick={async()=>{try{await request('files.open',{path:item.path});}catch(e){report(String(e));}}}>{item.name||item.path}</button>:<><strong>{item.title}</strong>{source==='memos'?<p>{item.body}</p>:<p>{item.start} ~ {item.end||item.start}</p>}</>}</div>)}{linked[source]?.hasMore&&<p className="muted">1000개까지 표시합니다. 해당 표에서 필터로 나머지 자료를 확인하세요.</p>}</section>)}</details><details><summary>기본 일정 연결</summary><input aria-label="연결 일정 제목" placeholder="일정 제목" value={title} onChange={e=>setTitle(e.target.value)}/><label>시작<input aria-label="연결 일정 시작" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료<input aria-label="연결 일정 종료" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button disabled={!title.trim()||!start||row.__rowId.startsWith('new-')} onClick={async()=>{try{if(end&&end<start)throw Error('종료는 시작 이후로 입력하세요.');await request('grid.commit',{sourceId:'schedules',tableVersion:linked.schedules?.storeVersion,changes:{added:[{title,start,end:end||start,sourceId,rowId:row.__rowId}],updated:[],deleted:[]}});setTitle('');setStart('');setEnd('');setLinked(await load());report('일정 연결 저장 완료');}catch(e){report(String(e));}}}>기간 일정 저장</button></details></>;
}
