import {useEffect,useMemo,useRef,useState} from 'react';
import type {CapturePayload} from '../../../packages/contracts/src';
import {presentCapture,defaultExtractionOptions,type ExtractionMode} from '../../../plugins/collector/presentation';
import {DataGrid,type RecordRow} from '../Grid';
import {download,exportSheet} from '../ImportExport';
export function ExtractionPanel({payload,bundle,labels,onDataset,onRule}:{payload:CapturePayload;bundle?:unknown;labels:Record<string,string>;onDataset?:(name:string,rows:RecordRow[],columns:any[])=>Promise<void>;onRule?:(dataset:string)=>void}){
 const [options,setOptions]=useState(defaultExtractionOptions),[source,setSource]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const drafts=useRef<Record<string,RecordRow[]>>({});
 useEffect(()=>{const check=(event:Event)=>{if(Object.keys(drafts.current).length)event.preventDefault();};window.addEventListener('pce:close-check',check);return()=>window.removeEventListener('pce:close-check',check);},[]);
 const presented=useMemo(()=>presentCapture(payload,labels,options),[payload,labels,options]);
 const table=presented.tables.find(t=>t.source===source)||presented.tables[0];
 const columns=useMemo(()=>table?.columns.map(field=>{const values=(payload.tables[table.source]||[]).map(row=>row[field]).filter(value=>value!=null&&value!=='');const kinds=new Set(values.map(value=>typeof value==='object'?'json':typeof value==='boolean'?'boolean':typeof value==='number'?(Number.isInteger(value)?'integer':'decimal'):'text'));return {field,label:labels[field]||field,kind:kinds.size===0?'text':kinds.size===1?[...kinds][0]:kinds.size===2&&kinds.has('integer')&&kinds.has('decimal')?'decimal':'json'};})||[],[table,labels,payload]);
 const rows=useMemo(()=>table?(drafts.current[table.source]||table.rows.map((r,i)=>({...r,__rowId:'extract-'+i}))):[],[table]);
 return <section className="panel"><h3>임시 추출 자료</h3><div className="row"><select aria-label="추출 보기" value={options.mode} onChange={e=>setOptions({...options,mode:e.target.value as ExtractionMode})}><option value="mappedTables">한글 매핑 표만</option><option value="mappedAll">한글 매핑 전체</option><option value="allTables">모든 표</option><option value="all">모든 자료</option></select>{(['hideEmptyTables','hideEmptyRows','hideEmptyColumns'] as const).map((key,i)=><label key={key}><input type="checkbox" checked={!options[key]} onChange={e=>setOptions({...options,[key]:!e.target.checked})}/>{['빈 표','빈 행','빈 열'][i]} 표시</label>)}</div><div className="row"><select aria-label="추출 표 선택" value={table?.source||''} onChange={e=>setSource(e.target.value)}>{presented.tables.map(t=><option value={t.source} key={t.source}>{t.source} · {t.rows.length}행</option>)}</select><button onClick={()=>download('pce-extraction.json',JSON.stringify(bundle||payload,null,2))}>원본 JSON 출력</button>{table&&<><button onClick={()=>exportSheet(table.source,drafts.current[table.source]||rows,columns,'xlsx',true)}>임시 표 XLSX</button><button onClick={()=>exportSheet(table.source,drafts.current[table.source]||rows,columns,'csv',true)}>임시 표 CSV</button>{onDataset&&<button disabled={busy} onClick={async()=>{try{setBusy(true);await onDataset(table.source,(drafts.current[table.source]||rows).map(({__rowId,...row})=>row),columns);}catch(e){setError(String(e));}finally{setBusy(false);}}}>내 자료로 복사</button>}{onRule&&<button onClick={()=>onRule(table.source)}>이 표의 수집 규칙 설정</button>}</>}</div>{!table&&<p>현재 보기에서 표시할 표가 없습니다. 매핑 사전을 설정하거나 모든 표 보기를 선택하세요.</p>}{table&&<div className="preview-grid"><DataGrid rows={rows} columns={columns} onChange={next=>{drafts.current[table.source]=next;}}/></div>}{Object.keys(presented.pointInfo).length>0&&<details><summary>표 외 값</summary><pre>{JSON.stringify(presented.pointInfo,null,2)}</pre></details>}{error&&<p className="error">{error}</p>}<details><summary>수집 출처·경고</summary><pre>{JSON.stringify({frames:payload.frames?.map(frame=>({framePath:frame.framePath,url:frame.url})),warnings:payload.warnings},null,2)}</pre></details></section>;
}
