import {useEffect,useState} from 'react';
import type {RecordRow} from '../Grid';
const fields:Record<string,{field:string;label:string;type?:string}[]>={
 memos:[{field:'title',label:'제목'},{field:'body',label:'메모 본문',type:'textarea'},{field:'sourceId',label:'연결 표'},{field:'rowId',label:'연결 레코드 ID'},{field:'screenKey',label:'화면 키'}],
 schedules:[{field:'title',label:'일정 제목'},{field:'start',label:'시작',type:'datetime-local'},{field:'end',label:'종료',type:'datetime-local'},{field:'sourceId',label:'연결 표'},{field:'rowId',label:'연결 레코드 ID'},{field:'screenKey',label:'화면 키'}],
 templates:[{field:'name',label:'템플릿 이름'},{field:'masterId',label:'마스터 참조'},{field:'body',label:'텍스트 / Markdown 본문',type:'textarea'}],
 launchers:[{field:'name',label:'바로가기 이름'},{field:'kind',label:'종류'},{field:'target',label:'파일·폴더 경로 / URL'}],
};
export function RecordFormPanel({sourceId,selected,rows,sources,onApply,report}:{sourceId:string;selected:RecordRow|null;rows:RecordRow[];sources:any[];onApply:(row:RecordRow)=>void;report:(s:string)=>void}){
 const [draft,setDraft]=useState<RecordRow>({}),[editing,setEditing]=useState(false);
 useEffect(()=>{setDraft(selected?Object.fromEntries(Object.entries(selected).filter(([k])=>!k.startsWith('__'))):{});setEditing(!!selected);},[sourceId,selected?.__rowId]);
 if(!fields[sourceId])return null;
 function apply(){if(!(draft.title||draft.name||'').trim()){report('제목 또는 이름을 입력하세요.');return;}if(sourceId==='schedules'&&(!draft.start||draft.end&&draft.end<draft.start)){report('일정 시작과 종료를 확인하세요.');return;}if(sourceId==='templates'&&editing&&draft.masterId===selected?.__rowId){report('자기 자신을 마스터로 선택할 수 없습니다.');return;}onApply({...draft,__rowId:editing&&selected?selected.__rowId:'new-'+crypto.randomUUID(),...(editing&&selected?{__storeVersion:selected.__storeVersion}:{})});report('입력 내용을 편집 버퍼에 적용했습니다. 저장으로 확정하세요.');}
 return <details className="record-form"><summary>{sourceId==='templates'?'텍스트·Markdown 마스터 / 파생 템플릿':sourceId==='schedules'?'기본 일정 입력':sourceId==='launchers'?'바로가기 입력':'메모 입력'} · {editing?'선택 레코드 수정':'새 레코드'}</summary><button onClick={()=>{setDraft({});setEditing(false);}}>새로 입력</button><div className="record-fields">{fields[sourceId].map(({field,label,type})=><label key={field}>{label}{field==='sourceId'?<select value={draft[field]||''} onChange={e=>setDraft({...draft,[field]:e.target.value})}><option value="">연결 없음</option>{sources.map(s=><option key={s.sourceId} value={s.sourceId}>{s.label}</option>)}</select>:field==='masterId'?<select value={draft[field]||''} onChange={e=>setDraft({...draft,[field]:e.target.value})}><option value="">마스터 없음</option>{rows.filter(r=>r.__rowId!==selected?.__rowId&&!r.__rowId.startsWith('new-')).map(r=><option key={r.__rowId} value={r.__rowId}>{r.name||r.__rowId}</option>)}</select>:field==='kind'?<select value={draft[field]||''} onChange={e=>setDraft({...draft,[field]:e.target.value})}><option value="">선택</option><option value="file">파일</option><option value="folder">폴더</option><option value="url">URL</option><option value="internal">직링크</option><option value="script">브라우저 스크립트</option></select>:type==='textarea'?<textarea value={draft[field]||''} onChange={e=>setDraft({...draft,[field]:e.target.value})} placeholder={sourceId==='templates'?'예: # {{name}}\n금액: {{amount}}\n본문을 비우면 마스터 본문을 상속합니다.':''}/>:<input type={type||'text'} value={draft[field]||''} onChange={e=>setDraft({...draft,[field]:e.target.value})}/>}</label>)}</div>{sourceId==='templates'&&<p className="muted">{'{{열키}} / {{JSON열.내부경로}}'}로 선택 레코드의 값을 넣습니다. 생성·뷰어는 문서를 만들 대상 레코드의 오른쪽 패널에서 실행하세요.</p>}<button className="primary" onClick={apply}>편집 버퍼에 적용</button></details>;
}
