import {useEffect,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {DataGrid,type RecordRow} from '../Grid';
import {FilterEditor,emptyFilter} from '../Filter';
import {download} from '../ImportExport';
const arr=(v:any)=>Array.isArray(v)?v:v?.relations||v?.captures||v?.rows||[];
export function RelationPanel({sources,sourceId,report}:{sources:any[];sourceId?:string;report:(s:string)=>void}){
 const [relations,setRelations]=useState<any[]>([]),[definition,setDefinition]=useState<any>({id:'',name:'',leftSourceId:sourceId||sources[0]?.sourceId||'',rightSourceId:'',fieldPairs:[{left:'',right:''}],cardinality:'many'}),[preview,setPreview]=useState<any>(null),[reviewed,setReviewed]=useState('');
 const load=()=>request('relation.list').then(v=>setRelations(arr(v))).catch(e=>report(String(e)));useEffect(()=>{load();},[]);
 const left=sources.find(s=>s.sourceId===definition.leftSourceId),right=sources.find(s=>s.sourceId===definition.rightSourceId);
 async function call(command:string){try{if(command==='relation.save'&&reviewed!==JSON.stringify(definition))throw Error('변경한 관계를 다시 미리보기하세요.');const r=await request(command,{definition,...(command==='relation.save'?{previewToken:preview?.previewToken}:{})});if(command==='relation.preview'){setPreview(r);setReviewed(JSON.stringify(definition));}if(command==='relation.save'){setDefinition(r);setPreview(null);setReviewed('');report('관계 저장 완료');load();}}catch(e){report(String(e));}}
 return <section className="panel"><h2>{sourceId?'테이블 관계 설정':'관계 관리자'}</h2><p className="muted">중앙 관리와 테이블 설정은 같은 관계 정의를 편집합니다. 원본 행을 병합하거나 삭제하지 않습니다.</p><div className="chips">{relations.filter(r=>!sourceId||r.leftSourceId===sourceId||r.rightSourceId===sourceId).map(r=><button key={r.id} onClick={()=>{setDefinition(r);setPreview(null);}}>{r.name||r.id}</button>)}<button onClick={()=>{setDefinition({id:'',name:'',leftSourceId:sourceId||'',rightSourceId:'',fieldPairs:[{left:'',right:''}],cardinality:'many'});setPreview(null);}}>+ 관계</button></div><label>관계 이름<input value={definition.name} onChange={e=>{setDefinition({...definition,name:e.target.value});setPreview(null);}}/></label><div className="row">{(['leftSourceId','rightSourceId'] as const).map((key,i)=><label key={key}>{i?'연결 대상':'기준 표'}<select aria-label={i?"연결 대상":"기준 표"} value={definition[key]} onChange={e=>{setDefinition({...definition,[key]:e.target.value});setPreview(null);}}><option value="">선택</option>{sources.map(s=><option value={s.sourceId} key={s.sourceId}>{s.label}</option>)}</select></label>)}</div>{definition.fieldPairs.map((pair:any,i:number)=><div className="row" key={i}>{(['left','right'] as const).map((key,j)=><select key={key} aria-label={j?'연결 대상 열':'기준 열'} value={pair[key]} onChange={e=>{setDefinition({...definition,fieldPairs:definition.fieldPairs.map((p:any,n:number)=>n===i?{...p,[key]:e.target.value}:p)});setPreview(null);}}><option value="">연결 열 선택</option>{(j?right:left)?.columns?.map((c:any)=><option value={c.field} key={c.field}>{c.label||c.field}</option>)}</select>)}<button onClick={()=>setDefinition({...definition,fieldPairs:definition.fieldPairs.filter((_:any,n:number)=>n!==i)})}>×</button></div>)}<button onClick={()=>setDefinition({...definition,fieldPairs:[...definition.fieldPairs,{left:'',right:''}]})}>+ 복합 연결 열</button><label>다중 매칭 처리<select aria-label="다중 매칭 처리" value={definition.cardinality} onChange={e=>{setDefinition({...definition,cardinality:e.target.value});setPreview(null);}}><option value="many">여러 행 연결 허용</option><option value="one">한 행만 · 여러 매칭은 검토</option></select></label><details><summary>추가 연결 조건</summary><FilterEditor columns={right?.columns||[]} value={definition.filter||emptyFilter()} onChange={filter=>{setDefinition({...definition,filter});setPreview(null);}}/></details><div className="row"><button onClick={()=>call('relation.preview')}>영향 미리보기</button><button className="primary" disabled={!preview||reviewed!==JSON.stringify(definition)} onClick={()=>call('relation.save')}>미리보기 승인 · 저장</button>{definition.id&&<button onClick={async()=>{try{setPreview(await request('relation.query',{id:definition.id}));}catch(e){report(String(e));}}}>연결 결과 조회</button>}</div>{preview&&<pre>{JSON.stringify(preview,null,2)}</pre>}</section>;
}
