import {useEffect,useRef,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {CollectionRuleEditor,type CollectionRule} from './CollectionRuleEditor';
import {download} from '../ImportExport';
import {useUnsavedChanges} from '../../bookmarklet/lifecycle';
type Entry={key:string;value:string;field?:string};
const labels:Record<string,string>={'dictionary.keys':'열 표시명','dictionary.codes':'코드 표시값','dictionary.headers':'Import 헤더 대응','dictionary.hidden':'숨김 설정','screen.bindings':'화면 대응','collector.rules':'수집 규칙','json.presentations':'JSON 표시 설정'};
const formKeys=['dictionary.keys','dictionary.codes','dictionary.headers'];
type RuleSetting=null|CollectionRule[]|{rules:CollectionRule[];includeDefaults:boolean;[key:string]:unknown};
function ruleSetting(value:string):RuleSetting{const parsed=JSON.parse(value);if(parsed===null||Array.isArray(parsed))return parsed;if(parsed&&Array.isArray(parsed.rules)&&typeof parsed.includeDefaults==='boolean')return parsed;throw Error('수집 규칙의 저장 형식을 확인하세요.');}
const defaultRules=(value:RuleSetting)=>value===null||(!Array.isArray(value)&&value.includeDefaults);
const customRules=(value:RuleSetting):CollectionRule[]=>value===null?[]:Array.isArray(value)?value:value.rules;
function withRules(value:RuleSetting,rules:CollectionRule[],includeDefaults=defaultRules(value)):RuleSetting{return {...(value&&!Array.isArray(value)?value:{}),rules,includeDefaults};}
function toEntries(key:string,value:any):Entry[]{if(key==='dictionary.codes')return Object.entries(value||{}).flatMap(([field,codes])=>Object.entries(codes||{}).map(([code,label])=>({field,key:code,value:String(label)})));return Object.entries(value||{}).map(([key,value])=>({key,value:String(value)}));}
export function SettingsPanel({report,sources}:{sources:any[];report:(s:string)=>void}){
 const [key,setKey]=useState('dictionary.keys'),[value,setValue]=useState('{}'),[entries,setEntries]=useState<Entry[]>([]),[version,setVersion]=useState<number>(),[raw,setRaw]=useState(false),[busy,setBusy]=useState(false),[suggestedDataset,setSuggestedDataset]=useState('');
 const [baseline,setBaseline]=useState<string>(),dirtyRef=useRef(false),busyRef=useRef(false);busyRef.current=busy;
 const [loading,setLoading]=useState(true),loadGeneration=useRef(0),activeKey=useRef(key);activeKey.current=key;
 function canLeave(){return !busyRef.current&&(!dirtyRef.current||confirm('저장하지 않은 설정 변경을 버릴까요?'));}
 function selectKey(k:string){if(!canLeave())return;++loadGeneration.current;setLoading(true);setValue(k==='collector.rules'?'null':'{}');setEntries([]);setVersion(undefined);setRaw(false);setKey(k);if(k===activeKey.current)void load(k);}
 async function load(k:string){const generation=++loadGeneration.current;setLoading(true);try{const r=await request('settings.read',{key:k});if(generation!==loadGeneration.current)return;const v=k==='collector.rules'?r.value??null:r.value??{};setValue(JSON.stringify(v,null,2));setBaseline(JSON.stringify(v));dirtyRef.current=false;setEntries(formKeys.includes(k)?toEntries(k,v):[]);setVersion(r.storeVersion);}catch(e){if(generation===loadGeneration.current)report(String(e));}finally{if(generation===loadGeneration.current)setLoading(false);}}
 useEffect(()=>{load(key);},[key]);
 useEffect(()=>{const fn=(event:Event)=>{const detail=(event as CustomEvent).detail;selectKey(detail.key||'collector.rules');setSuggestedDataset(detail.dataset||'');};window.addEventListener('pce-open-settings',fn);return()=>{++loadGeneration.current;window.removeEventListener('pce-open-settings',fn);};},[]);
 function parsed(){if(raw||!formKeys.includes(key))return JSON.parse(value);const seen=new Set<string>(),output:Record<string,any>=Object.create(null);for(const entry of entries){if(!entry.key.trim()||key==='dictionary.codes'&&!entry.field?.trim())throw Error('원천 키와 코드 열을 입력하세요.');const id=key==='dictionary.codes'?JSON.stringify([entry.field,entry.key]):entry.key;if(seen.has(id))throw Error('동일한 원천 키가 반복됩니다.');seen.add(id);if(key==='dictionary.codes'){const field=entry.field!;output[field]??=Object.create(null);output[field][entry.key]=entry.value;}else output[entry.key]=entry.value;}return output;}
 let draftFingerprint:string;try{draftFingerprint=JSON.stringify(parsed());}catch{draftFingerprint='invalid:'+value+JSON.stringify(entries);}
 const dirty=!loading&&baseline!==undefined&&draftFingerprint!==baseline;dirtyRef.current=dirty;useUnsavedChanges(dirty||busy);
 function toggleRaw(){try{if(!raw)setValue(JSON.stringify(parsed(),null,2));else if(formKeys.includes(key))setEntries(toEntries(key,JSON.parse(value)));setRaw(!raw);}catch(e){report(String(e));}}
 async function save(){setBusy(true);try{await request('settings.save',{key,value:parsed(),storeVersion:version});report('설정 저장 완료');await load(key);window.dispatchEvent(new CustomEvent('pce-settings-saved',{detail:{key}}));}catch(e){report(String(e));}finally{setBusy(false);}}
 async function exportPolicy(){setBusy(true);try{const policy=await request('collector.policy');download('pce-collection-policy.json',JSON.stringify(policy,null,2));report('저장된 수집 정책을 내보냈습니다. 연결된 확장은 저장된 정책을 다시 읽어 적용합니다.');}catch(e){report(String(e));}finally{setBusy(false);}}
 return <section className="panel"><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><h2>사전·화면·규칙 설정</h2><div className="row"><select aria-label="설정 종류" value={key} disabled={busy} onChange={e=>selectKey(e.target.value)}>{Object.entries(labels).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select>{formKeys.includes(key)&&<button onClick={toggleRaw}>{raw?'입력 표':'JSON 원문'}</button>}</div><p className="muted">원천 키와 원값은 유지됩니다. 표시명, 코드 표시값, 가져올 파일의 헤더 대응을 따로 설정합니다.</p>{key==='collector.rules'?<fieldset disabled={busy||loading} style={{border:0,padding:0}}>{suggestedDataset&&<div className="row"><span>추출 표: {suggestedDataset}</span><button onClick={()=>{const current=ruleSetting(value);setValue(JSON.stringify(withRules(current,[...customRules(current),{sourceId:'',dataset:suggestedDataset,identityFields:[],enabled:true}]),null,2));setSuggestedDataset('');}}>추출 표의 규칙 추가</button></div>}<label><input type="checkbox" checked={defaultRules(ruleSetting(value))} onChange={e=>{const current=ruleSetting(value);setValue(JSON.stringify(withRules(current,customRules(current),e.target.checked),null,2));}}/>기본 업무 분류 사용</label><p className="muted">기본 접수·공고·계약 화면 규칙과 아래 사용자 규칙을 함께 사용할 수 있습니다. 이 옵션을 바꾸어도 작성한 사용자 규칙은 유지됩니다.</p><CollectionRuleEditor sources={sources} rules={customRules(ruleSetting(value))} onChange={rules=>setValue(JSON.stringify(withRules(ruleSetting(value),rules),null,2))}/></fieldset>:formKeys.includes(key)&&!raw?<><div className="setting-entries">{entries.map((entry,i)=><div className="row" key={i}>{key==='dictionary.codes'&&<input aria-label="코드 열 키" placeholder="열 원천 키" value={entry.field||''} onChange={e=>setEntries(entries.map((v,n)=>n===i?{...v,field:e.target.value}:v))}/>}<input aria-label="사전 원천 키" placeholder={key==='dictionary.headers'?'입력 파일 헤더':'원천 키 / 코드'} value={entry.key} onChange={e=>setEntries(entries.map((v,n)=>n===i?{...v,key:e.target.value}:v))}/><span>→</span><input aria-label="사전 대응 값" placeholder={key==='dictionary.headers'?'대상 열 원천 키':'표시값'} value={entry.value} onChange={e=>setEntries(entries.map((v,n)=>n===i?{...v,value:e.target.value}:v))}/><button title="대응 삭제" onClick={()=>setEntries(entries.filter((_,n)=>n!==i))}>×</button></div>)}</div><button onClick={()=>setEntries([...entries,{key:'',value:'',...(key==='dictionary.codes'?{field:''}:{})}])}>+ 대응</button></>:<textarea aria-label="설정 JSON" className="code tall" value={value} onChange={e=>setValue(e.target.value)}/>}<div className="row"><button className="primary" disabled={busy||loading} onClick={save}>검증·저장</button><button disabled={busy||loading} onClick={()=>{if(canLeave())void load(key);}}>저장값 다시 읽기</button>{key==='collector.rules'&&<button disabled={busy||loading} onClick={exportPolicy}>저장된 수집 정책 내보내기</button>}</div></fieldset></section>;
}
