import {useEffect,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import type {Column} from '../Grid';
export function TableSettingsPanel({source,columns,onSaved,report,dirty}:{source:any;dirty:boolean;columns:Column[];onSaved:()=>Promise<void>;report:(s:string)=>void}){
 const [draft,setDraft]=useState<Column[]>(columns),[mode,setMode]=useState('allow'),[keys,setKeys]=useState<string[]>([]),[field,setField]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setDraft(columns);setMode(source?.duplicatePolicy?.mode||'allow');setKeys(source?.duplicatePolicy?.keys||[]);},[columns,source?.sourceId,source?.storeVersion]);
 function change(index:number,values:Partial<Column>){setDraft(current=>current.map((c,i)=>i===index?{...c,...values}:c));}
 async function save(){setBusy(true);try{await request('table.configure',{sourceId:source.sourceId,storeVersion:source.storeVersion,columns:draft,duplicatePolicy:{mode,keys}});await onSaved();report('표 구조·표시·중복 정책 저장 완료');}catch(e){report(String(e));}finally{setBusy(false);}}
 return <section className="panel"><h3>표 구조·표시·저장 중복 정책</h3><p className="muted">표시명·숨김·고정은 원천 키와 원값을 유지합니다. 저장 중복과 관계의 다중 매칭은 각각 설정합니다.</p><div className="column-settings">{draft.map((c,i)=><div className="row" key={c.field}><code>{c.field}</code><input aria-label={`${c.field} 표시명`} value={c.label||''} onChange={e=>change(i,{label:e.target.value})}/><select aria-label={`${c.field} 자료형`} value={c.kind||'text'} onChange={e=>change(i,{kind:e.target.value})}>{['text','json','decimal','integer','boolean','date','datetime','code'].map(k=><option key={k}>{k}</option>)}</select><label><input type="checkbox" checked={!!c.hidden} onChange={e=>change(i,{hidden:e.target.checked})}/>숨김</label><label><input type="checkbox" checked={!!c.frozen} onChange={e=>change(i,{frozen:e.target.checked})}/>고정</label><label><input type="checkbox" checked={c.editable!==false} onChange={e=>change(i,{editable:e.target.checked})}/>편집</label></div>)}</div><div className="row"><input aria-label="추가 열 키" value={field} onChange={e=>setField(e.target.value)} placeholder="추가 열 원천 키"/><button onClick={()=>{if(!field.trim()||field.startsWith('__')||draft.some(c=>c.field===field.trim())){report('중복되지 않는 열 키를 입력하세요. __ 접두사는 내부 값입니다.');return;}setDraft([...draft,{field:field.trim(),label:field.trim(),kind:'text'}]);setField('');}}>+ 열</button></div><label>저장 중복 처리<select aria-label="저장 중복 처리" value={mode} onChange={e=>setMode(e.target.value)}><option value="allow">중복 허용</option><option value="skip">신규 건너뛰기</option><option value="compare">기존값 비교·검토</option></select></label><div className="row">{draft.map(c=><label key={c.field}><input type="checkbox" checked={keys.includes(c.field)} onChange={e=>setKeys(e.target.checked?[...keys,c.field]:keys.filter(k=>k!==c.field))}/>{c.label||c.field}</label>)}</div><p className="muted">중복 판단 열: {keys.join(' + ')||'미지정'} · 빈 판단값은 중복으로 제거하지 않습니다.</p>{dirty&&<p className="muted">표 편집 내용을 먼저 저장한 뒤 구조 설정을 저장하세요.</p>}<button className="primary" disabled={busy||!source||dirty} onClick={save}>설정 저장</button></section>;
}
