import {useEffect,useMemo,useRef,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {combineAggregation,parseAggregationFile,selectAggregationHeader,type AggregationSelection,type AggregationResult} from '../../../plugins/files/aggregation';
import {download,exportSheet} from '../../../plugins/files/index';
import {DataGrid,type GridHandle,type RecordRow} from '../../ui/Grid';
import {useUnsavedChanges} from '../../bookmarklet/lifecycle';
import './capture-tools.css';

export function AggregationPopup({report}:{report:(message:string)=>void}){
 const [result,setResult]=useState<AggregationResult>({columns:[],rows:[],files:[]}),[pending,setPending]=useState<AggregationSelection[]>([]),[active,setActive]=useState(0),[confirmed,setConfirmed]=useState<number[]>([]),[aliases,setAliases]=useState<Record<string,string>>({}),[useAliases,setUseAliases]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[name,setName]=useState('취합 자료'),[history,setHistory]=useState<AggregationResult['files']>([]);
 const currentResult=useRef(result);currentResult.current=result;
 const lock=useRef(false),grid=useRef<GridHandle|null>(null),input=useRef<HTMLInputElement>(null),alive=useRef(true);
 useUnsavedChanges(dirty||pending.length>0);
 useEffect(()=>{alive.current=true;request('settings.read',{key:'dictionary.headers'}).then(setting=>{if(alive.current&&setting.value&&typeof setting.value==='object'&&!Array.isArray(setting.value))setAliases(setting.value);}).catch(error=>report('헤더 사전 연결 실패: '+error));return()=>{alive.current=false;};},[]);
 const preview=useMemo(()=>{if(!pending.length)return {result,error:''};try{return {result:combineAggregation(result,pending,useAliases?aliases:{}),error:''};}catch(error){return {result,error:String(error)};}},[result,pending,useAliases,aliases]);
 const rows=useMemo(()=>preview.result.rows.map((row,index)=>({...row,__rowId:'aggregate-'+index})),[preview.result.rows]);
 const selected=pending[active];
 const headerRows=useMemo(()=>selected?.headers.map((header,index)=>({__rowId:'header-'+index,position:index+1,original:selected.sheet.matrix[selected.headerRow][index]??'',header}))||[],[selected]);
 const headerColumns=useMemo(()=>[{field:'position',label:'열',kind:'integer',editable:false},{field:'original',label:'원래 헤더',editable:false},{field:'header',label:'적용할 헤더'}],[]);
 async function readFiles(files:File[]){if(lock.current||!files.length)return;if(pending.length&&!confirm('확인 중인 파일을 새 파일들로 바꿀까요?'))return;lock.current=true;setBusy(true);setError('');try{const next=await Promise.all(files.map(async file=>{const sheet=parseAggregationFile(await file.arrayBuffer(),file.name);return selectAggregationHeader(sheet,sheet.headerCandidates[0]);}));if(!alive.current)return;setPending(next);setActive(0);setConfirmed([]);report(next.length+'개 파일의 첫 시트를 읽었습니다. 각 파일의 헤더를 확인하세요.');}catch(error){if(alive.current)setError(String(error)+' 기존 취합 자료는 변경하지 않았습니다.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
 function patchSelection(next:AggregationSelection){setPending(previous=>previous.map((selection,index)=>index===active?next:selection));setConfirmed(previous=>previous.filter(index=>index!==active));}
 function apply(){if(lock.current)return;try{const next=combineAggregation(result,pending,useAliases?aliases:{});setResult(next);setHistory(previous=>[...previous,...next.files]);setPending([]);setConfirmed([]);setDirty(true);setError('');report('미리보기 승인 · '+next.rows.length+'행을 임시 취합했습니다.');}catch(error){setError(String(error));}}
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const snapshot=structuredClone(currentResult.current);const output=await request('dataset.create',{name:name.trim(),columns:snapshot.columns,rows:snapshot.rows,duplicatePolicy:{mode:'allow',keys:[]}});setDirty(false);report('새 SQL 자료로 저장했습니다: '+output.sourceId);}catch(error){setError('저장 실패 · 취합 자료 유지: '+error);}finally{lock.current=false;setBusy(false);}}
 return <section className="capture-workspace aggregation-workspace" onDragOver={event=>{event.preventDefault();}} onDrop={event=>{event.preventDefault();void readFiles(Array.from(event.dataTransfer.files));}}>
  <div className="capture-toolbar"><button disabled={busy} onClick={()=>input.current?.click()}>파일 가져오기</button><input ref={input} aria-label="취합 파일" hidden type="file" multiple accept=".xlsx,.xls,.csv,.tsv" onChange={event=>{void readFiles(Array.from(event.target.files||[]));event.target.value='';}}/><span className="muted">여러 파일을 여기에 놓으세요</span><span className="capture-spacer"/><button disabled={busy||!!pending.length||!result.rows.length} onClick={()=>exportSheet(name,rows,result.columns,'xlsx',true)}>XLSX</button><button disabled={busy||!!pending.length||!result.rows.length} onClick={()=>exportSheet(name,rows,result.columns,'csv',true)}>CSV</button><button disabled={busy||!!pending.length||!result.rows.length} onClick={()=>download(name+'.json',JSON.stringify({columns:result.columns,rows:result.rows},null,2))}>JSON</button></div>
  {pending.length>0&&<section className="aggregation-preview"><div className="capture-tabs" role="tablist" aria-label="취합 파일 확인">{pending.map((selection,index)=><button role="tab" aria-selected={active===index} key={index} onClick={()=>setActive(index)}>{index+1}. {selection.sheet.name}{confirmed.includes(index)?' · 확인됨':''}</button>)}</div>
   {selected&&<><div className="capture-toolbar"><span>{selected.sheet.sheetName}</span><label>헤더 행 <input aria-label="취합 헤더 행" type="number" min={1} max={selected.sheet.matrix.length} value={selected.headerRow+1} onChange={event=>{const value=Number(event.target.value)-1;if(Number.isInteger(value)&&value>=0&&value<selected.sheet.matrix.length)patchSelection(selectAggregationHeader(selected.sheet,value));}}/></label><select aria-label="헤더 후보" value={selected.headerRow} onChange={event=>patchSelection(selectAggregationHeader(selected.sheet,Number(event.target.value)))}>{[...new Set([selected.headerRow,...selected.sheet.headerCandidates])].map(index=><option key={index} value={index}>{index+1}행 · {selected.sheet.matrix[index].filter(value=>value!=null&&value!=='').slice(0,4).join(' / ')}</option>)}</select><button onClick={()=>{setPending(previous=>previous.filter((_,index)=>index!==active));setActive(0);setConfirmed([]);}}>이 파일 제외</button></div>
   <div className="aggregation-headers"><DataGrid rows={headerRows} columns={headerColumns} onChange={next=>patchSelection({...selected,headers:next.map(row=>String(row.header??''))})}/></div>
   <div className="capture-toolbar"><label><input type="checkbox" checked={confirmed.includes(active)} onChange={event=>setConfirmed(previous=>event.target.checked?[...previous,active]:previous.filter(index=>index!==active))}/>이 파일의 헤더 확인</label><label><input type="checkbox" checked={useAliases} onChange={event=>{setUseAliases(event.target.checked);setConfirmed([]);}}/>헤더 사전 적용</label><span className="capture-spacer"/><button onClick={()=>{setPending([]);setConfirmed([]);}}>가져오기 취소</button><button className="primary" disabled={busy||!!preview.error||confirmed.length!==pending.length} onClick={apply}>전체 미리보기 승인 · 취합</button></div></>}
   {preview.result.files.map((file,index)=><small className="aggregation-file-summary" key={index}>{file.name}: {file.rows}행{file.ignoredHeaders.length?' · 제외 열: '+file.ignoredHeaders.join(', '):''}</small>)}
  </section>}
  {(error||preview.error)&&<p className="error" role="alert">{error||preview.error}</p>}
  <div className="aggregation-grid"><DataGrid rows={rows} columns={preview.result.columns} readOnly={busy||pending.length>0} handle={handle=>{grid.current=handle;}} onChange={next=>{setResult(previous=>({...previous,rows:next.map(({__rowId,...row})=>row)}));setDirty(true);}}/></div>
  <div className="capture-toolbar"><span>{rows.length}행 · {preview.result.columns.length}열 {dirty?'· 미저장':''}</span><button disabled={busy||!!pending.length||!result.rows.length} onClick={()=>grid.current?.remove()}>선택 행 삭제</button><button disabled={busy||!!pending.length||!result.rows.length} onClick={()=>grid.current?.fillDown()}>아래로 채우기</button><span className="capture-spacer"/><input aria-label="취합 자료 이름" value={name} onChange={event=>setName(event.target.value)}/><button className="primary" disabled={busy||!!pending.length||!result.rows.length||!name.trim()} onClick={()=>void save()}>새 SQL 자료로 저장</button></div>
  <details><summary>취합 기준·파일 이력</summary><p>첫 승인 파일의 헤더가 기준입니다. 다음 파일은 같은 헤더 열만 누적하며 없는 값은 비워 둡니다. 헤더명을 수정하거나 사전을 적용할 수 있습니다. 각 파일의 첫 시트만 사용합니다. 취합·출력은 임시 작업이며 SQL 저장은 별도입니다.</p>{history.map((file,index)=><p key={index}>{file.name}: {file.rows}행 · 제외 열 {file.ignoredHeaders.join(', ')||'없음'}</p>)}</details>
 </section>;
}
