import {useEffect,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {HwpxPanel} from '../../shared/Hwpx';
import {TemplatesPanel} from '../../shared/Templates';
import type {PrototypeSelection,PrototypeServices} from '../../bookmarklet/contracts';
import {sqlDocuments} from '../document-storage';
import {contextSelection,RecordGrid} from './RecordGrid';
import {renderTemplate} from '../../../plugins/template/index';
import {openHwpx,base64ToBytes,resolveHwpxTemplate,generateHwpx,exportHwpx} from '../../../plugins/hwpx/index';
import {download} from '../../../plugins/files/index';

export function RecordPicker({sourceId,rowId,onSelect}:{sourceId?:string;rowId?:string;onSelect:(selection:PrototypeSelection|null)=>void}){
 const [sources,setSources]=useState<any[]>([]),[source,setSource]=useState(sourceId||''),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState(rowId||''),[error,setError]=useState('');
 useEffect(()=>{request('table.list').then(result=>setSources(Array.isArray(result)?result:result.sources)).catch(error=>setError(String(error)));},[]);
 useEffect(()=>{let active=true;setRows([]);if(!source){onSelect(null);return;}(async()=>{let rows:any[]=[],offset=0,version:number|undefined;while(true){const page=await request('table.read',{sourceId:source,offset,limit:1000});if(!active)return {rows:[]};if(version!==undefined&&version!==page.storeVersion)throw new Error('조회 중 표가 변경되었습니다. 다시 선택하세요.');version=page.storeVersion;rows.push(...page.rows);offset+=page.rows.length;if(!page.hasMore)break;if(!page.rows.length)throw new Error('다음 레코드 페이지를 읽지 못했습니다.');}return {rows};})().then(result=>{if(!active)return;setRows(result.rows);const row=result.rows.find((row:any)=>row.__rowId===selected);onSelect(row?{datasetId:source,datasetName:sources.find(s=>s.sourceId===source)?.label||source,rowId:row.__rowId,values:row}:null);}).catch(error=>{if(active)setError(String(error));});return()=>{active=false;};},[source]);
 return <div className="record-picker"><div className="row"><label>연결 표 <select aria-label="연결 표" value={source} onChange={event=>{setSource(event.target.value);setSelected('');onSelect(null);}}><option value="">자료 없이 사용</option>{sources.map(s=><option key={s.sourceId} value={s.sourceId}>{s.label}</option>)}</select></label><label>레코드 <select aria-label="연결 레코드" value={selected} onChange={event=>{setSelected(event.target.value);const row=rows.find(row=>row.__rowId===event.target.value);onSelect(row?{datasetId:source,datasetName:sources.find(s=>s.sourceId===source)?.label||source,rowId:row.__rowId,values:row}:null);}}><option value="">레코드 선택</option>{rows.map(row=><option key={row.__rowId} value={row.__rowId}>{Object.entries(row).filter(([key])=>!key.startsWith('__')).slice(0,3).map(([,value])=>typeof value==='object'?JSON.stringify(value):String(value??'')).join(' · ')}</option>)}</select></label></div>{error&&<p className="muted">{error}</p>}</div>;
}
export function DocumentsPopup({report,sourceId,rowId,context}:{report:(text:string)=>void;sourceId?:string;rowId?:string;context?:any}){
 const [kind,setKind]=useState('text'),[detail,setDetail]=useState(false),[showData,setShowData]=useState(false),[selection,setSelection]=useState<PrototypeSelection|null>(null),[entries,setEntries]=useState<any[]>([]),[busy,setBusy]=useState(false);
 const refresh=()=>Promise.all((['templates','hwpx-templates'] as const).map(namespace=>sqlDocuments.listDocuments<any>(namespace).then(values=>values.map(entry=>({...entry,namespace}))))).then(values=>setEntries(values.flat()));
 useEffect(()=>{refresh().catch(error=>report(String(error)));},[detail]);
 useEffect(()=>{let live=true;contextSelection(context,sourceId,rowId).then(value=>{if(live)setSelection(value);}).catch(error=>report(String(error)));return()=>{live=false;};},[sourceId,rowId,context?.screenKey]);
 const services:PrototypeServices={notify:report,selection,select:setSelection,navigate:()=>{},datasets:async()=>[]};
 async function generate(entry:any){try{setBusy(true);const fresh=await sqlDocuments.listDocuments<any>(entry.namespace);const saved=fresh.find(candidate=>candidate.documentId===entry.documentId);if(!saved)throw Error('템플릿이 삭제되었습니다. 목록을 다시 확인하세요.');const values=selection?.values||{};if(entry.namespace==='templates'){const result=renderTemplate(saved.value.body,values,saved.value.program);download(saved.value.name+'.md',result.text,'text/markdown;charset=utf-8');report(result.warnings.join(' · ')||'문서를 생성했습니다.');}else{const template=resolveHwpxTemplate(entry.documentId,fresh).template;const result=generateHwpx(openHwpx(base64ToBytes(template.masterZip!),template.filename),template.anchors,values,template.program);const bytes=exportHwpx(result.archive);const url=URL.createObjectURL(new Blob([new Uint8Array(bytes).buffer],{type:'application/hwp+zip'}));const link=document.createElement('a');link.href=url;link.download=template.name+'.hwpx';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);report([...result.warnings,...result.archive.warnings].join(' · ')||'문서를 생성했습니다.');}}catch(error){report(String(error));}finally{setBusy(false);}}
 return <div className="feature-content"><div className="document-toolbar"><strong>{selection?selection.datasetName:'문서 생성'}</strong><button onClick={()=>setShowData(!showData)} aria-pressed={showData}>DB</button><button onClick={()=>setDetail(!detail)} aria-pressed={detail}>{detail?'문서 목록':'상세'}</button></div><div className={'document-layout'+(showData?' with-data':'')}><section><div hidden={detail}><div className="template-list">{entries.map(entry=><button key={entry.namespace+entry.documentId} disabled={busy} onClick={()=>generate(entry)}><small>{entry.namespace==='templates'?'기안문':'한글문서'}</small><br/>{entry.value.name}</button>)}</div>{!entries.length&&<button onClick={()=>setDetail(true)}>+ 템플릿</button>}</div><div hidden={!detail}><div className="row"><button aria-pressed={kind==='text'} onClick={()=>setKind('text')}>텍스트 · MD</button><button aria-pressed={kind==='hwpx'} onClick={()=>setKind('hwpx')}>HWPX</button></div><div hidden={kind!=='text'}><TemplatesPanel services={services} documents={sqlDocuments}/></div><div hidden={kind!=='hwpx'}><HwpxPanel services={services} documents={sqlDocuments}/></div></div></section>{showData&&<RecordGrid onSelect={setSelection} report={report}/>}</div></div>;
}
