import {useEffect,useRef,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import type {PrototypeSelection} from '../../bookmarklet/contracts';
import {contextSelection,RecordGrid} from './RecordGrid';
export function ExplorerPopup({sourceId,rowId,report,context}:{sourceId?:string;rowId?:string;report:(text:string)=>void;context?:any}){
 const [selection,setSelection]=useState<PrototypeSelection|null>(null),[ready,setReady]=useState(false),[root,setRoot]=useState(''),[settingVersion,setSettingVersion]=useState<number|null>(null),[listing,setListing]=useState<any>(null),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[showData,setShowData]=useState(false),[relative,setRelative]=useState('');
 const sequence=useRef(0),selectedRef=useRef(selection);selectedRef.current=selection;
 useEffect(()=>()=>{++sequence.current;},[]);
 useEffect(()=>{request('settings.read',{key:'explorer.root'}).then(result=>{setRoot(result.value?.basePath||'');setSettingVersion(result.storeVersion);}).catch(error=>report(String(error)));},[]);
 useEffect(()=>{let live=true;setReady(false);setListing(null);++sequence.current;contextSelection(context,sourceId,rowId).then(value=>{if(live){setSelection(value);setReady(true);setRelative('');}}).catch(error=>report(String(error)));return()=>{live=false;};},[sourceId,rowId,context?.screenKey]);
 async function run(action:string,path=relative){const generation=++sequence.current,current=selectedRef.current;try{setBusy(true);const result=await request('explorer.context',{...(selection?{sourceId:selection.datasetId,rowId:selection.rowId}:{}),action,relativePath:path});if(generation!==sequence.current||current!==selectedRef.current)return;if(!result.file){setListing(result);setRelative(path);}if(action==='open')report('탐색기에 열었습니다.');}catch(error){if(generation===sequence.current)report(String(error));}finally{if(generation===sequence.current)setBusy(false);}}
 useEffect(()=>{if(ready){setListing(null);void run('list','');}},[ready,selection]);
 return <div className="feature-content"><div className="document-toolbar"><strong>{selection?.datasetName||'다운로드'}</strong><button onClick={()=>setShowData(!showData)} aria-pressed={showData}>DB</button><button onClick={()=>setSettings(!settings)} aria-pressed={settings}>설정</button><button disabled={busy||!ready} onClick={()=>run('open')}>탐색기</button></div>{settings&&<section className="panel"><div className="row"><label>기준 폴더<input aria-label="폴더 기준 경로" value={root} onChange={event=>setRoot(event.target.value)}/></label><button disabled={busy||settingVersion===null} onClick={async()=>{try{setBusy(true);const result=await request('settings.save',{key:'explorer.root',value:{basePath:root},storeVersion:settingVersion});setSettingVersion(result.storeVersion);setSettings(false);await run('list','');}catch(error){report(String(error));}finally{setBusy(false);}}}>저장</button></div><small>비워 두면 다운로드 폴더를 사용합니다.</small></section>}<div className={'document-layout'+(showData?' with-data':'')}><section>{listing&&<><div className="row"><button disabled={!relative||busy} onClick={()=>run('list',relative.split('/').slice(0,-1).join('/'))}>↑</button><span title={listing.path}>{relative||selection?.datasetName||'다운로드'}</span><button disabled={busy} onClick={()=>run('list')}>↻</button></div>{!listing.exists?<button disabled={busy} onClick={()=>run('ensure','')}>업무 폴더 생성</button>:<div className="folder-list">{listing.entries.map((entry:any)=><button className="folder-entry" key={entry.name} disabled={busy} onDoubleClick={()=>run(entry.isDirectory?'list':'open',[relative,entry.name].filter(Boolean).join('/'))}><span>{entry.isDirectory?'▸':'▤'}</span><span>{entry.name}</span><small>{entry.size==null?'':new Intl.NumberFormat('ko').format(entry.size)+' B'}</small></button>)}</div>}{listing.hasMore&&<button onClick={()=>run('open')}>전체 목록 열기</button>}</> }</section>{showData&&<RecordGrid onSelect={value=>{++sequence.current;setListing(null);setSelection(value);setRelative('');}} report={report}/>}</div></div>;
}
