import {useEffect,useMemo,useState} from 'react';
import type {CapturePayload} from '../../../packages/contracts/src';
import {request} from '../../../plugins/core/gateway';
import {DataGrid,type RecordRow} from '../../ui/Grid';
import {mergeGridEdits} from '../../ui/editBuffer';
import {download,exportSheet} from '../../../plugins/files/index';
import {presentCapture,defaultExtractionOptions,isDisplayEmpty,type ExtractionMode} from '../../../plugins/collector/presentation';
import './capture-tools.css';
import {extensionCommand} from '../transport';

export function ExtractPopup({report}:{report:(text:string)=>void}){
  const [capture,setCapture]=useState<{payload:CapturePayload;bundle:unknown}|null>(null),[generation,setGeneration]=useState(0),[framePath,setFramePath]=useState(''),[labels,setLabels]=useState<Record<string,string>>({}),[valueLabels,setValueLabels]=useState<Record<string,Record<string,string>>>({}),[hiddenKeys,setHiddenKeys]=useState<string[]>([]),[register,setRegister]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState(''),[urlMode,setUrlMode]=useState('equals'),[keys,setKeys]=useState<string[]>([]),[screenField,setScreenField]=useState(''),[screenValue,setScreenValue]=useState(''),[policyVersion,setPolicyVersion]=useState<number|null>(null),[busy,setBusy]=useState(false);
  function canReplace(){const check=new Event('pce:close-check',{cancelable:true});window.dispatchEvent(check);return !check.defaultPrevented||confirm('수정 중인 임시 표를 버리고 다시 읽을까요?');}
  async function extract(){if(!canReplace())return;setBusy(true);try{const result=await extensionCommand({type:'capture',mode:'extract'});setCapture(result);setGeneration(previous=>previous+1);setFramePath(result.payload.frames?.[0]?.framePath||'');setRegister('');report('현재 로딩된 정보를 임시로 추출했습니다. 등록 전에는 DB를 변경하지 않습니다.');}catch(error){report(String(error));}finally{setBusy(false);}}
  useEffect(()=>{void extract();Promise.all(['dictionary.keys','dictionary.codes','dictionary.hidden'].map(key=>request('settings.read',{key}))).then(([keys,codes,hidden])=>{setLabels(keys.value||{});setValueLabels(codes.value||{});setHiddenKeys(Array.isArray(hidden.value)?hidden.value:[]);}).catch(error=>report('표시 사전 연결 실패: '+error));},[]);
  const frame=capture?.payload.frames?.find(frame=>frame.framePath===framePath);
  const payload:CapturePayload|undefined=frame?{pointInfo:frame.pointInfo,tables:frame.tables,warnings:capture?.payload.warnings||[],frames:[frame]}:capture?.payload;
  const columns=register?[...new Set((payload?.tables[register]||[]).flatMap(row=>Object.keys(row)))]:[];
  async function startRegistration(dataset:string){try{const policy=await request('collector.policy');setPolicyVersion(policy.storeVersion);setRegister(dataset);setName(dataset);setKeys([]);setUrl(frame?.url||'');const field=Object.keys(payload?.pointInfo||{}).find(key=>/depth2|screenId/i.test(key))||'';setScreenField(field);setScreenValue(String(payload?.pointInfo[field]??''));}catch(error){report(String(error));}}
  return <div className="capture-workspace"><div className="capture-toolbar"><button disabled={busy} onClick={extract}>현재 페이지 다시 읽기</button></div><details><summary>추출 안내</summary><p>규칙과 관계없이 현재 로딩된 원천 화면을 읽습니다. 임시 편집·출력은 원본을 바꾸지 않으며 표 저장과 수집 규칙 등록은 별도입니다. 다른 화면은 원래 탭에서 연 후 다시 읽으세요.</p></details>{capture&&<><label>원천 화면 <select aria-label="원천 화면" value={framePath} onChange={event=>{if(!canReplace())return;setFramePath(event.target.value);setRegister('');}}>{capture.payload.frames?.map(frame=><option key={frame.framePath} value={frame.framePath}>{frame.framePath} · {frame.url}</option>)}</select></label>{payload&&<ExtractionTableWorkspace key={framePath+generation} payload={payload} bundle={capture.bundle} labels={labels} valueLabels={valueLabels} hiddenKeys={hiddenKeys} onRule={dataset=>void startRegistration(dataset)} onDataset={async(name,rows,columns)=>{const result=await request('dataset.create',{name,rows,columns,duplicatePolicy:{mode:'allow',keys:[]}});report('독립 자료로 저장했습니다: '+result.sourceId);}}/>}</>}
  {register&&payload&&<section className="extraction-registration"><strong>화면에 연결할 수집 표 등록</strong><details><summary>등록 동작</summary><p>조건과 업무키를 확인하고 등록하면 빈 수집 표와 규칙을 만듭니다. 이후 수동 또는 자동 수집에서 변경을 반영합니다.</p></details><div className="form-grid"><label>표 이름<input value={name} onChange={event=>setName(event.target.value)}/></label><label>URL 조건<select value={urlMode} onChange={event=>setUrlMode(event.target.value)}><option value="equals">정확 일치</option><option value="contains">포함</option></select><input aria-label="등록 URL" value={url} onChange={event=>setUrl(event.target.value)}/></label><label>화면 필드<select value={screenField} onChange={event=>{setScreenField(event.target.value);setScreenValue(String(payload.pointInfo[event.target.value]??''));}}><option value="">URL만으로 지정</option>{Object.keys(payload.pointInfo).map(key=><option key={key}>{key}</option>)}</select></label>{screenField&&<label>화면 값<input value={screenValue} onChange={event=>setScreenValue(event.target.value)}/></label>}</div><fieldset><legend>행을 식별할 업무키 (복수 선택)</legend>{columns.map(field=><label className="inline" key={field}><input type="checkbox" checked={keys.includes(field)} onChange={event=>setKeys(event.target.checked?[...keys,field]:keys.filter(key=>key!==field))}/>{labels[field]||field}</label>)}</fieldset><div className="row"><button disabled={busy||!keys.length||!url.trim()||!name.trim()} className="primary" onClick={async()=>{try{setBusy(true);const result=await request('collector.register',{payload:capture!.payload,dataset:register,label:name,identityFields:keys,urlFilter:{field:'url',operator:urlMode,values:[url]},screenFilter:screenField?{field:screenField,operator:'equals',values:[screenValue]}:undefined,framePath:frame?.framePath,policyVersion});report('수집 표와 규칙을 등록했습니다: '+result.source.label);setRegister('');}catch(error){report('등록 실패 · 입력 유지: '+error);}finally{setBusy(false);}}}>조건 확인 · 표와 규칙 등록</button><button onClick={()=>setRegister('')}>취소</button></div></section>}
  </div>;
}


function ExtractionTableWorkspace({payload,bundle,labels,valueLabels,hiddenKeys,onDataset,onRule}:{payload:CapturePayload;bundle:unknown;labels:Record<string,string>;valueLabels:Record<string,Record<string,string>>;hiddenKeys:string[];onDataset:(name:string,rows:RecordRow[],columns:any[])=>Promise<void>;onRule:(dataset:string)=>void}){
 const [options,setOptions]=useState(defaultExtractionOptions),[showHidden,setShowHidden]=useState(false),[source,setSource]=useState(''),[drafts,setDrafts]=useState<Record<string,RecordRow[]>>({}),[selected,setSelected]=useState<RecordRow>(),[detail,setDetail]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const check=(event:Event)=>{if(Object.keys(drafts).length)event.preventDefault();};window.addEventListener('pce:close-check',check);window.addEventListener('beforeunload',check);return()=>{window.removeEventListener('pce:close-check',check);window.removeEventListener('beforeunload',check);};},[drafts]);
 const presented=useMemo(()=>presentCapture(payload,labels,options),[payload,labels,options]);
 const table=presented.tables.find(table=>table.source===source)||presented.tables[0];
 const fullRows=useMemo(()=>table?(drafts[table.source]||(payload.tables[table.source]||[]).map((row,index)=>({...row,__rowId:'extract-'+index}))):[],[table,drafts,payload]);
 const columns=useMemo(()=>table?.columns.filter(field=>showHidden||!hiddenKeys.includes(field)).map(field=>{const kinds=new Set(fullRows.map(row=>row[field]).filter(value=>!isDisplayEmpty(value)).map(value=>typeof value==='object'?'json':typeof value==='boolean'?'boolean':typeof value==='number'?(Number.isInteger(value)?'integer':'decimal'):'text'));return {field,label:labels[field]||field,values:valueLabels[field],kind:kinds.size===0?'text':kinds.size===1?[...kinds][0]:kinds.size===2&&kinds.has('integer')&&kinds.has('decimal')?'decimal':'json'};})||[],[table,labels,valueLabels,hiddenKeys,showHidden,fullRows]);
 const rows=useMemo(()=>fullRows.filter(row=>!options.hideEmptyRows||columns.some(column=>!isDisplayEmpty(row[column.field]))),[fullRows,columns,options.hideEmptyRows]);
 const outputRows=()=>rows.map(row=>Object.fromEntries(columns.map(column=>[column.field,row[column.field]])));
 return <><div className="capture-toolbar"><select aria-label="추출 보기" value={options.mode} onChange={event=>setOptions({...options,mode:event.target.value as ExtractionMode})}><option value="mappedTables">한글 매핑 표만</option><option value="mappedAll">한글 매핑 전체</option><option value="allTables">모든 표</option><option value="all">모든 자료</option></select><details><summary>빈칸 표시</summary><div className="extraction-options">{(['hideEmptyTables','hideEmptyRows','hideEmptyColumns'] as const).map((key,index)=><label key={key}><input type="checkbox" checked={!options[key]} onChange={event=>setOptions({...options,[key]:!event.target.checked})}/>{['빈 표','빈 행','빈 열'][index]} 표시</label>)}<label><input type="checkbox" checked={showHidden} onChange={event=>setShowHidden(event.target.checked)}/>사전 숨김키 표시</label></div></details><span className="capture-spacer"/><button onClick={()=>download('pce-extraction.json',JSON.stringify(bundle||payload,null,2))}>원본 JSON 출력</button></div>
  <div className="capture-tabs" role="tablist" aria-label="추출 표">{presented.tables.map(candidate=><button key={candidate.source} role="tab" aria-selected={table?.source===candidate.source} onClick={()=>{setSource(candidate.source);setSelected(undefined);setDetail(false);}}>{labels[candidate.source]||candidate.source} · {candidate.rows.length}</button>)}</div>
  {table?<><div className="capture-toolbar"><span>{rows.length}행 · {columns.length}열 {drafts[table.source]?'· 임시 편집':''}</span><span className="capture-spacer"/><button disabled={!selected} onClick={()=>setDetail(!detail)}>행 JSON</button><button onClick={()=>exportSheet(table.source,rows,columns,'xlsx',true)}>임시 표 XLSX</button><button onClick={()=>exportSheet(table.source,rows,columns,'csv',true)}>임시 표 CSV</button><button disabled={busy} onClick={async()=>{setBusy(true);try{await onDataset(table.source,outputRows(),columns);}catch(error){setError(String(error));}finally{setBusy(false);}}}>내 자료로 복사</button><button onClick={()=>onRule(table.source)}>이 표의 수집 규칙 설정</button></div><div className="capture-main-grid"><DataGrid rows={rows} columns={columns} readOnly={busy} onSelect={setSelected} onChange={(next,deleted)=>setDrafts(previous=>({...previous,[table.source]:mergeGridEdits(fullRows,next,deleted)}))}/></div></>:<div className="capture-main-grid muted">현재 보기에서 표시할 표가 없습니다. 다른 보기나 원천 화면을 선택하세요.</div>}
  {detail&&selected&&<div className="capture-detail"><pre>{JSON.stringify(selected,null,2)}</pre></div>}{Object.keys(presented.pointInfo).length>0&&<details><summary>표 외 화면 값 · {Object.keys(presented.pointInfo).length}개</summary><div style={{height:220}}><DataGrid readOnly rows={Object.entries(presented.pointInfo).map(([key,value],index)=>({__rowId:String(index),key,label:labels[key]||key,value}))} columns={[{field:'key',label:'원천 키'},{field:'label',label:'표시 이름'},{field:'value',label:'값',kind:'json'}]}/></div></details>}{error&&<p className="error">{error}</p>}<details><summary>출처·읽기 경고</summary><pre>{JSON.stringify({frames:payload.frames?.map(frame=>({framePath:frame.framePath,url:frame.url})),warnings:payload.warnings},null,2)}</pre></details></>;
}
