import {useEffect,useRef,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {extensionCommand,openSurface} from '../transport';
import type {TableRow,TableSource} from '../../../packages/contracts/src/index';
type LauncherKind='url'|'script'|'file'|'folder';
type LauncherDraft={name:string;kind:LauncherKind;target:string};
type LauncherTable=TableSource&{storeVersion:number};
const kinds=[{value:'url',label:'URL · 직링크'},{value:'script',label:'스크립트'},{value:'file',label:'PC 파일'},{value:'folder',label:'폴더'}] as const;
const blank=():LauncherDraft=>({name:'',kind:'url',target:''});
const fromRow=(row:TableRow):LauncherDraft=>({name:String(row.name||''),kind:kinds.some(kind=>kind.value===row.kind)?row.kind as LauncherKind:'url',target:String(row.target||'')});
export function LauncherPopup({report,mode,rowId}:{report:(text:string)=>void;mode?:string;rowId?:string}){
 const [table,setTable]=useState<LauncherTable>(),[editing,setEditing]=useState<TableRow>(),[adding,setAdding]=useState(mode==='add'),[draft,setDraft]=useState<LauncherDraft>(blank),[baseline,setBaseline]=useState<LauncherDraft>(blank),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const dirty=adding&&JSON.stringify(draft)!==JSON.stringify(baseline);
 const guard=useRef(false),opened=useRef(false),generation=useRef(0),mounted=useRef(true);guard.current=dirty||busy;
 useEffect(()=>{const close=(event:Event)=>{if(guard.current)event.preventDefault();};const unload=(event:BeforeUnloadEvent)=>{if(guard.current){event.preventDefault();event.returnValue='';}};window.addEventListener('pce:close-check',close);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('pce:close-check',close);window.removeEventListener('beforeunload',unload);};},[]);
 async function refresh(){const current=++generation.current;let first:LauncherTable|undefined,offset=0;const rows:TableRow[]=[];do{const page=await request<LauncherTable>('table.read',{sourceId:'launchers',offset,limit:1000});if(first&&first.storeVersion!==page.storeVersion)throw Error('조회 중 런처 설정이 변경되었습니다. 다시 읽어 주세요.');first??=page;rows.push(...page.rows);offset+=page.rows.length;if(!page.hasMore)break;if(!page.rows.length)throw Error('다음 바로가기 목록을 읽지 못했습니다.');}while(true);if(current===generation.current&&mounted.current)setTable({...first!,rows});}
 useEffect(()=>{mounted.current=true;void refresh().catch(reason=>{setError(String(reason));report(String(reason));}).finally(()=>{if(mounted.current)setLoading(false);});return()=>{mounted.current=false;++generation.current;};},[]);
 useEffect(()=>{if(table&&rowId&&!opened.current){opened.current=true;const row=table.rows.find(candidate=>candidate.__rowId===rowId);if(row)edit(row);else setError('선택한 바로가기를 찾지 못했습니다.');}},[table,rowId]);
 function canLeave(){return !busy&&(!dirty||confirm('저장하지 않은 바로가기 변경을 버릴까요?'));}
 function edit(row?:TableRow){if(!canLeave())return;const next=row?fromRow(row):blank();setEditing(row);setAdding(true);setDraft(next);setBaseline(next);setError('');}
 function cancel(){if(!canLeave())return;setAdding(false);setEditing(undefined);setDraft(blank());setBaseline(blank());setError('');}
 function change(values:Partial<LauncherDraft>){setDraft(previous=>({...previous,...values}));setError('');}
 async function notifyRefresh(message:string){const results=await Promise.allSettled([refresh(),extensionCommand({type:'ui.refresh'})]);const failures=results.filter(result=>result.status==='rejected') as PromiseRejectedResult[];const notice=failures.length?`${message} 목록 갱신 실패: ${failures.map(result=>String(result.reason)).join('; ')}`:message;if(mounted.current)setError(failures.length?notice:'');report(notice);}
 async function save(){if(busy||!table)return;setError('');try{if(!draft.name.trim()||!draft.target.trim())throw Error('이름과 실행 대상을 입력하세요.');if(draft.kind==='url'){const url=new URL(draft.target.trim());if(!['http:','https:'].includes(url.protocol))throw Error('URL은 http 또는 https 주소를 입력하세요.');}const values={name:draft.name.trim(),kind:draft.kind,target:draft.kind==='script'?draft.target:draft.target.trim()};setBusy(true);guard.current=true;await request('grid.commit',{sourceId:'launchers',tableVersion:table.storeVersion,changes:{added:editing?[]:[values],updated:editing?[{rowId:editing.__rowId,storeVersion:editing.__storeVersion,values}]:[],deleted:[]}});setBaseline({...draft});setAdding(false);setEditing(undefined);await notifyRefresh('바로가기를 저장했습니다.');}catch(reason){const message='저장 실패 · 입력 유지: '+reason;setError(message);report(message);}finally{setBusy(false);}}
 async function remove(row:TableRow){if(!table||!canLeave()||!confirm(`“${String(row.name||'바로가기')}”를 삭제할까요?`))return;setBusy(true);guard.current=true;setError('');try{await request('grid.commit',{sourceId:'launchers',tableVersion:table.storeVersion,changes:{added:[],updated:[],deleted:[{rowId:row.__rowId,storeVersion:row.__storeVersion}]}});setAdding(false);setEditing(undefined);setDraft(blank());setBaseline(blank());await notifyRefresh('바로가기를 삭제했습니다.');}catch(reason){const message='삭제 실패: '+reason;setError(message);report(message);}finally{setBusy(false);}}
 const execute=(row:TableRow)=>{void extensionCommand({type:'launcher.run',rowId:row.__rowId}).then(()=>report('실행 요청 완료')).catch(reason=>{setError(String(reason));report(String(reason));});};
 return <div className="feature-content launcher-surface"><fieldset className="feature-fieldset" disabled={busy||loading}><div className="row"><strong style={{flex:1}}>런처</strong><button onClick={()=>edit()}>+ 추가</button><button onClick={()=>{if(canLeave())void refresh().catch(reason=>setError(String(reason)));}}>새로고침</button></div>
  <div className="launcher-cards" aria-label="바로가기 목록" style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(min(100%,160px),1fr))',gap:8}}>
   <button type="button" onClick={()=>openSurface('documents').catch(reason=>report(String(reason)))}>문서 생성</button><button type="button" onClick={()=>openSurface('explorer').catch(reason=>report(String(reason)))}>업무 폴더</button>
   {table?.rows.map(row=><div key={row.__rowId} className="launcher-entry" style={{display:'flex',alignItems:'stretch',minWidth:0}}><button type="button" title={String(row.description||row.target||'').slice(0,200)} style={{flex:1,minWidth:0,overflowWrap:'anywhere',textAlign:'left'}} onClick={()=>execute(row)}>{String(row.name||'이름 없는 바로가기')}</button><button type="button" title="바로가기 설정" aria-label={`${String(row.name||'바로가기')} 설정`} onClick={()=>edit(row)} style={{padding:'6px'}}><svg width="16" height="16" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"><circle cx="10" cy="4" r="1.5"/><circle cx="10" cy="10" r="1.5"/><circle cx="10" cy="16" r="1.5"/></svg></button></div>)}
  </div>
  {adding&&<form className="panel editor" onSubmit={event=>{event.preventDefault();void save();}}><h3>{editing?'바로가기 설정':'바로가기 추가'}</h3>
   <div className="row" role="tablist" aria-label="바로가기 종류">{kinds.map(kind=><button type="button" role="tab" key={kind.value} aria-selected={draft.kind===kind.value} onClick={()=>change({kind:kind.value})}>{kind.label}</button>)}</div>
   <label>이름<input value={draft.name} onChange={event=>change({name:event.target.value})}/></label><label>{draft.kind==='script'?'실행할 JavaScript':draft.kind==='url'?'URL 주소':'파일·폴더 절대 경로'}<textarea value={draft.target} onChange={event=>change({target:event.target.value})} rows={draft.kind==='script'?8:3}/></label>
   {draft.kind==='script'&&<small>저장은 실행하지 않습니다. 실행하려면 Chrome 사용자 스크립트 허용이 필요합니다.</small>}
   <div className="row">{dirty&&<small style={{marginRight:'auto'}}>미저장</small>}{editing&&<button type="button" onClick={()=>void remove(editing)}>삭제</button>}<button type="button" onClick={cancel}>취소</button><button type="submit" className="primary" disabled={!table||busy}>저장</button></div>
  </form>}
 </fieldset>{loading&&<p role="status">불러오는 중…</p>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
