import {useEffect,useMemo,useRef,useState} from 'react';
import {request} from '../../../plugins/core/gateway';
import {DataGrid,type Column} from '../../../plugins/grid/index';
import type {TableRow,TableSource} from '../../../packages/contracts/src/index';
import {blankDraft,calendarDays,calendarSelection,dateFrom,dayOf,matchesNoteScreen,moveCalendarPeriod,noteColors,noteColumns,noteLabel,noteSaveValues,noteScreenKey,notesOnDate,rowDraft,sortNotes,text,today,type NoteContext,type NoteDraft,type NoteKind,type NoteMode} from './notes-model';
import './notes.css';
export {localDate,calendarDays,moveCalendarPeriod,noteSaveValues,notesOnDate,visibleNotes,noteLabel,noteScreenKey,matchesNoteScreen,sortNotes,calendarSelection} from './notes-model';
type NoteTable=TableSource&{storeVersion:number};
type OwnedRow=TableRow&{__noteSource:NoteKind};
type SaveNote=(source:NoteKind,values:Record<string,unknown>,original:TableRow|undefined,requestId:string)=>Promise<TableRow>;
type SheetState='clean'|'dirty'|'saving'|'error';
const equal=(a:NoteDraft,b:NoteDraft)=>JSON.stringify(a)===JSON.stringify(b);
function Icon({kind}:{kind:'title'|'star'|'screen'|'sticky'|'color'|'trash'|'restore'}){
 const paths={title:'M4 4h12M10 4v12M7 16h6',star:'M10 2l2.5 5.1 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8L10 2z',screen:'M3 3h14v10H3V3zm7 10v4m-4 0h8',sticky:'M4 3h12v9l-5 5H4V3zm7 14v-5h5',color:'M10 2a8 8 0 100 16h1a2 2 0 001-3.7 1 1 0 01.5-1.8H15A3 3 0 0018 9a8 8 0 00-8-7zM6 7h.1M10 5h.1M14 7h.1M5 11h.1',trash:'M3 5h14M8 5V3h4v2M5 5l1 12h8l1-12M8 8v6m4-6v6',restore:'M5 5h8a4 4 0 010 8h-2M5 5l3-3M5 5l3 3M4 13v4h7'};
 return <svg width="16" height="16" viewBox="0 0 20 20" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d={paths[kind]}/></svg>;
}
async function openSticky(source:NoteKind,rowId:string){const {openSurface}=await import('../transport');return openSurface('notes',{sourceId:source,rowId,mode:'sticky'});}
function NoteSheet({row,source,initial,ready,context,persist,onState,onCreated,standalone=false}:{row?:TableRow;source:NoteKind;initial?:NoteDraft;ready:boolean;context:NoteContext;persist:SaveNote;onState:(state:SheetState)=>void;onCreated?:(row:TableRow)=>void;standalone?:boolean}){
 const first=useRef(row?rowDraft(row):initial||blankDraft());
 const [draft,setDraft]=useState(first.current),[saved,setSaved]=useState(first.current),[status,setStatus]=useState<SheetState>(row?'clean':'dirty'),[error,setError]=useState(''),[showTitle,setShowTitle]=useState(!!first.current.title),[composing,setComposing]=useState(false);
 const latest=useRef(draft),baseline=useRef(saved),original=useRef(row),flight=useRef<Promise<void>|undefined>(undefined),mounted=useRef(true),pending=useRef<{id:string;snapshot:NoteDraft;values:Record<string,unknown>;original?:TableRow}|undefined>(undefined);
 latest.current=draft;baseline.current=saved;
 const dirty=!original.current||!equal(draft,saved),screenKey=noteScreenKey(context);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;onState('clean');};},[]);
 useEffect(()=>{onState(status);},[status]);
 useEffect(()=>{if(row&&row.__storeVersion!==original.current?.__storeVersion&&!flight.current&&!pending.current&&equal(latest.current,baseline.current)){original.current=row;const next=rowDraft(row);latest.current=next;baseline.current=next;setDraft(next);setSaved(next);}},[row]);
 function change(values:Partial<NoteDraft>){const next={...latest.current,...values};latest.current=next;setDraft(next);if(!flight.current){setStatus('dirty');onState('dirty');}setError('');}
 async function save(){
  if(!ready||flight.current||composing)return;
  if(!pending.current&&original.current&&equal(latest.current,baseline.current))return;
  try{
   if(!pending.current){const snapshot={...latest.current};pending.current={id:crypto.randomUUID(),snapshot,values:noteSaveValues(source,snapshot,original.current),original:original.current};}
  }catch(reason){setError(String(reason));setStatus('error');onState('error');return;}
  const attempt=pending.current;setStatus('saving');onState('saving');
  const run=(async()=>{try{
   const result=await persist(source,attempt.values,attempt.original,attempt.id);
   original.current=result;baseline.current=attempt.snapshot;pending.current=undefined;
   void import('../transport').then(({extensionCommand})=>extensionCommand({type:'ui.refresh'})).catch(()=>{});
   if(!mounted.current)return;
   setSaved(attempt.snapshot);onCreated?.(result);setError('');
   const next=equal(latest.current,attempt.snapshot)?'clean':'dirty';setStatus(next);onState(next);
  }catch(reason){if(mounted.current){const message=String(reason);if(/\[(?:STALE_VERSION|INVALID_REQUEST|VALIDATION|REFERENCE_CONFLICT|NOT_FOUND)\]/.test(message))pending.current=undefined;setError(message);setStatus('error');onState('error');}}
  finally{flight.current=undefined;}})();flight.current=run;await run;
 }
 useEffect(()=>{if(!ready||!dirty||status==='saving'||status==='error'||composing)return;const timer=setTimeout(()=>void save(),550);return()=>clearTimeout(timer);},[draft,saved,ready,status,composing]);
 async function reload(){if(flight.current)return;if(dirty&&!confirm('저장되지 않은 입력을 버리고 DB의 메모를 다시 읽을까요?'))return;try{let offset=0;let found:TableRow|undefined;do{const page=await request<NoteTable>('table.read',{sourceId:source,offset,limit:1000});found=page.rows.find(r=>r.__rowId===original.current?.__rowId);if(found||!page.hasMore)break;offset+=page.rows.length;if(!page.rows.length)break;}while(true);if(!found)throw Error('DB에서 메모를 찾지 못했습니다. 입력은 유지됩니다.');original.current=found;pending.current=undefined;const next=rowDraft(found);latest.current=next;baseline.current=next;setDraft(next);setSaved(next);setError('');setStatus('clean');onState('clean');}catch(reason){setError(String(reason));}}
 const title=noteLabel(draft),trashed=draft.trashed===true;
 const tool=(kind:Parameters<typeof Icon>[0]['kind'],label:string,action:()=>void,pressed?:boolean,disabled=false)=><button type="button" title={label} aria-label={label} aria-pressed={pressed} disabled={disabled} onClick={action}><Icon kind={kind}/></button>;
 return <article className={'note-sheet'+(trashed?' note-trashed':'')} data-color={draft.color||'yellow'} data-note-id={original.current?.__rowId||'new'} aria-label={title}>
  <div className="note-tools"><span className="note-kind">{source==='schedules'?'일정':draft.screenKey?'화면 메모':'메모'}</span>
   {tool('title','제목 표시',()=>setShowTitle(v=>!v),showTitle,trashed)}
   {tool('star','중요',()=>change({important:!draft.important}),draft.important,trashed)}
   {tool('screen','현재 화면 고정',()=>change({screenKey:draft.screenKey?'':screenKey}),!!draft.screenKey,trashed||(!screenKey&&!draft.screenKey))}
   {!standalone&&tool('sticky','스티커 열기',()=>{if(original.current)void openSticky(source,original.current.__rowId).catch(reason=>setError(String(reason)));},undefined,!original.current||trashed)}
   <details><summary aria-label="메모 색상" title="메모 색상"><Icon kind="color"/></summary><div className="note-palette">{noteColors.map(color=><button type="button" key={color.key} data-swatch={color.key} aria-label={`${color.name} 색상`} aria-pressed={draft.color===color.key} disabled={trashed} style={{background:({yellow:'#fff2af',green:'#e4efba',blue:'#d4eaf8',pink:'#f7dce5',plain:'#fafaf7'})[color.key]}} onClick={event=>{change({color:color.key});event.currentTarget.closest('details')?.removeAttribute('open');}}/>)}</div></details>
   {trashed?tool('restore','메모 복원',()=>change({trashed:false})):tool('trash','휴지통으로 이동',()=>change({trashed:true}))}
  </div>
  {showTitle&&<input className="note-title" aria-label="메모 일정 제목" value={draft.title} readOnly={trashed} onChange={event=>change({title:event.target.value})}/>}
  <textarea className="note-body" aria-label="메모 일정 내용" value={draft.body} readOnly={trashed} rows={standalone?9:4} autoFocus={standalone&&!row} onChange={event=>change({body:event.target.value})} onCompositionStart={()=>setComposing(true)} onCompositionEnd={()=>setComposing(false)}/>
  {source==='schedules'&&<div className="notes-toolbar"><label>시작<input type="date" aria-label="일정 시작일" value={draft.start} readOnly={trashed} onChange={event=>change({start:event.target.value})}/></label><label>종료<input type="date" aria-label="일정 종료일" value={draft.end} readOnly={trashed} onChange={event=>change({end:event.target.value})}/></label></div>}
  <details className="note-options"><summary>일정·표시 설정</summary><div className="notes-toolbar"><select aria-label="메모 표시 범위" value={draft.screenKey?'screen':'general'} disabled={trashed} onChange={event=>change({screenKey:event.target.value==='screen'?(draft.screenKey||screenKey):''})}><option value="general">공통</option><option value="screen" disabled={!screenKey&&!draft.screenKey}>화면 고정</option></select><label><input type="checkbox" checked={draft.urgent} disabled={trashed} onChange={event=>change({urgent:event.target.checked})}/>긴급</label><label><input type="checkbox" checked={draft.completed} disabled={trashed} onChange={event=>change({completed:event.target.checked})}/>완료</label></div></details>
  <div className="note-state" role="status"><span>{status==='saving'?'저장 중…':status==='error'?'저장 실패':dirty?'저장 대기':'저장됨'}</span>{dirty&&<button type="button" disabled={!ready||status==='saving'} onClick={()=>void save()}>{status==='error'?'재시도':'지금 저장'}</button>}<time dateTime={text(original.current?.createdAt)}>{text(original.current?.createdAt)&&new Date(text(original.current?.createdAt)).toLocaleDateString('ko-KR')}</time></div>
  {error&&<div className="note-error" role="alert">{error}<p>입력은 이 창에 남아 있습니다.</p>{original.current&&<button type="button" onClick={()=>void reload()}>DB 값 다시 읽기</button>}</div>}
 </article>;
}
const managerColumns:Column[]=[{field:'typeLabel',label:'구분'},{field:'displayTitle',label:'제목·첫 줄'},{field:'body',label:'내용'},{field:'createdAt',label:'생성일'},{field:'updatedAt',label:'수정일'},{field:'start',label:'기준일'},{field:'important',label:'중요',kind:'boolean'},{field:'screenKey',label:'화면 연결'}];
export function NotesPopup({context,report,mode,rowId,sourceId}:{context:NoteContext;report:(text:string)=>void;mode?:string;rowId?:string;sourceId?:string}){
 const standalone=mode==='sticky'||mode==='add';
 const [section,setSection]=useState<NoteMode>(['all','memos','manager','schedules','calendar'].includes(mode||'')?mode as NoteMode:'all');
 const [tables,setTables]=useState<Partial<Record<NoteKind,NoteTable>>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [search,setSearch]=useState(''),[sort,setSort]=useState<'updated'|'created'|'title'|'date'>('updated'),[scope,setScope]=useState<'all'|'common'|'screen'>('all'),[showOther,setShowOther]=useState(false),[trash,setTrash]=useState(false),[focusDate,setFocusDate]=useState(today),[calendarView,setCalendarView]=useState<'month'|'week'|'day'|'eisenhower'>('month');
 const [dates,setDates]=useState<string[]>([]),[rangeAnchor,setRangeAnchor]=useState<string>(),[chosen,setChosen]=useState<string>(),[newSheet,setNewSheet]=useState<{key:string;source:NoteKind;initial:NoteDraft;row?:TableRow}|undefined>(()=>standalone&&!rowId?{key:crypto.randomUUID(),source:sourceId==='schedules'?'schedules':'memos',initial:blankDraft()}:undefined);
 const cache=useRef(tables),generation=useRef(0),states=useRef(new Map<string,SheetState>()),pending=useRef(new Map<string,Record<string,unknown>>()),tail=useRef<Promise<unknown>>(Promise.resolve()),alive=useRef(true);
 cache.current=tables;
 const screenKey=noteScreenKey(context);
 async function readAll(){const serial=++generation.current;setLoading(true);try{const entries=await Promise.all((['memos','schedules'] as NoteKind[]).map(async source=>{let first:NoteTable|undefined,offset=0;const rows:TableRow[]=[];do{const page=await request<NoteTable>('table.read',{sourceId:source,offset,limit:1000});if(first&&first.storeVersion!==page.storeVersion)throw Error('조회 중 목록 구조가 변경되었습니다. 다시 불러오세요.');first??=page;rows.push(...page.rows);offset+=page.rows.length;if(!page.hasMore)break;if(!page.rows.length)throw Error('다음 메모 페이지를 읽지 못했습니다.');}while(true);return [source,{...first!,rows}] as const;}));if(serial===generation.current&&alive.current){const next=Object.fromEntries(entries);cache.current=next;setTables(next);setError('');}}catch(reason){if(serial===generation.current){setError(String(reason));report(String(reason));}}finally{if(serial===generation.current)setLoading(false);}}
 useEffect(()=>{alive.current=true;void readAll();return()=>{alive.current=false;++generation.current;};},[]);
 const blocked=()=>[...states.current.values()].some(state=>state!=='clean');
 useEffect(()=>{const close=(event:Event)=>{if(blocked())event.preventDefault();};const unload=(event:BeforeUnloadEvent)=>{if(blocked()){event.preventDefault();event.returnValue='';}};window.addEventListener('pce:close-check',close);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('pce:close-check',close);window.removeEventListener('beforeunload',unload);};},[]);
 function navigate(action:()=>void){if(blocked()){report('변경을 저장한 뒤 이동하세요. 저장 실패 시 입력은 현재 창에 유지됩니다.');return;}if(newSheet?.row)setNewSheet(undefined);action();}
 const persist:SaveNote=(source,values,original,requestId)=>{
  const run=tail.current.catch(()=>{}).then(async()=>{
   if(!pending.current.has(requestId)){const cached=cache.current[source];if(!cached)throw Error('SQL 목록을 읽지 못했습니다. 연결을 확인하고 재시도하세요.');const definition=await request<NoteTable>('table.read',{sourceId:source,offset:0,limit:1});const table={...cached,columns:definition.columns,storeVersion:definition.storeVersion};cache.current={...cache.current,[source]:table};const additions=noteColumns.filter(column=>!table.columns.some(existing=>existing.field===column.field));const stamp=new Date().toISOString();const content={...values,updatedAt:stamp,...(!original?{createdAt:stamp}:{})};pending.current.set(requestId,{sourceId:source,tableVersion:table.storeVersion,changes:{added:original?[]:[content],updated:original?[{rowId:original.__rowId,storeVersion:original.__storeVersion,values:content}]:[],deleted:[],...(additions.length?{columns:[...table.columns,...additions]}:{})}});}
   const result=await request<{rows:TableRow[];storeVersion:number}>('grid.commit',pending.current.get(requestId)!,requestId as ReturnType<typeof crypto.randomUUID>);const row=result.rows[0];if(!row)throw Error('저장한 메모 응답을 확인할 수 없습니다.');const table=cache.current[source]!;const columns=(pending.current.get(requestId)?.changes as any).columns||table.columns;const next={...cache.current,[source]:{...table,columns,storeVersion:result.storeVersion,rows:table.rows.some(r=>r.__rowId===row.__rowId)?table.rows.map(r=>r.__rowId===row.__rowId?row:r):[...table.rows,row]}};cache.current=next;pending.current.delete(requestId);if(alive.current)setTables(next);return row;
  });tail.current=run;return run;
 };
 const all=useMemo<OwnedRow[]>(()=>Object.entries(tables).flatMap(([source,table])=>table!.rows.map(row=>({...row,__noteSource:source as NoteKind}))),[tables]);
 const rows=useMemo(()=>sortNotes(all.filter(row=>(trash?row.trashed===true:row.trashed!==true)&&(section==='memos'?row.__noteSource==='memos':section==='schedules'||section==='calendar'?row.__noteSource==='schedules':true)&&(showOther||matchesNoteScreen(row.screenKey,screenKey))&&(scope==='common'?!row.screenKey:scope==='screen'?!!row.screenKey&&matchesNoteScreen(row.screenKey,screenKey):true)&&(!search.trim()||`${noteLabel(row)}\n${text(row.body)}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))),sort),[all,section,trash,showOther,scope,screenKey,search,sort]);
 const mark=(key:string)=>(state:SheetState)=>{if(state==='clean')states.current.delete(key);else states.current.set(key,state);};
 const sheet=(row:OwnedRow)=><NoteSheet key={row.__noteSource+row.__rowId} row={row} source={row.__noteSource} context={context} ready={!loading} persist={persist} onState={mark(row.__noteSource+row.__rowId)} standalone={standalone}/>;
 const make=(source:NoteKind,start=today(),end=start)=>navigate(()=>{const initial=blankDraft(start);initial.end=end;if(scope==='screen')initial.screenKey=screenKey;setNewSheet({key:crypto.randomUUID(),source,initial});});
 const draftCanvas=newSheet&&<NoteSheet key={newSheet.key} row={newSheet.row} initial={newSheet.initial} source={newSheet.source} context={context} ready={!loading&&!!tables[newSheet.source]} persist={persist} onState={mark(newSheet.key)} onCreated={row=>setNewSheet(current=>current?.key===newSheet.key?{...current,row}:current)} standalone={standalone}/>;
 const managerRows=useMemo(()=>rows.map(row=>({...row,__rowId:row.__noteSource+':'+row.__rowId,noteId:row.__rowId,typeLabel:row.__noteSource==='schedules'?'일정':row.screenKey?'화면':'메모',displayTitle:noteLabel(row)})),[rows]);
 const chosenRow=all.find(row=>row.__noteSource+':'+row.__rowId===chosen);
 if(standalone)return <section className="notes-v4 sticky">{rowId?(all.find(row=>row.__rowId===rowId&&row.__noteSource===(sourceId==='schedules'?'schedules':'memos'))?sheet(all.find(row=>row.__rowId===rowId&&row.__noteSource===(sourceId==='schedules'?'schedules':'memos'))!):<p>{loading?'불러오는 중…':'메모를 찾을 수 없습니다.'}</p>):draftCanvas}{error&&<p role="alert">{error}<button onClick={()=>void readAll()}>연결 재시도</button></p>}</section>;
 return <section className="notes-v4">
  <nav className="notes-toolbar" aria-label="메모 메뉴">{([['all','전체'],['memos','메모'],['manager','관리'],['schedules','일정'],['calendar','달력']] as const).map(([value,label])=><button key={value} aria-pressed={section===value} onClick={()=>navigate(()=>{setSection(value);setChosen(undefined);})}>{label}</button>)}<button onClick={()=>make('memos')}>+ 메모</button><button onClick={()=>make('schedules')}>+ 일정</button></nav>
  <div className="notes-toolbar"><input type="search" aria-label="메모 일정 검색" placeholder="검색" value={search} onChange={event=>{const value=event.target.value;navigate(()=>setSearch(value));}}/><select aria-label="메모 정렬" value={sort} onChange={event=>setSort(event.target.value as typeof sort)}><option value="updated">수정일</option><option value="created">생성일</option><option value="title">제목·첫 줄</option><option value="date">기준일</option></select><select aria-label="메모 범위" value={scope} onChange={event=>navigate(()=>setScope(event.target.value as typeof scope))}><option value="all">전체</option><option value="common">공통</option><option value="screen">현재 화면</option></select><label><input type="checkbox" checked={showOther} onChange={event=>navigate(()=>setShowOther(event.target.checked))}/>다른 화면</label><button onClick={()=>navigate(()=>{setTrash(v=>!v);setChosen(undefined);})} aria-pressed={trash}>휴지통</button><button onClick={()=>navigate(()=>void readAll())}>새로고침</button></div>
  {draftCanvas}
  {section==='manager'?<><div className="notes-manager-grid"><DataGrid rows={managerRows} columns={managerColumns} readOnly onSelect={row=>navigate(()=>setChosen(String(row.__rowId)))}/></div><div className="notes-manager-detail">{chosenRow?sheet(chosenRow):<p className="notes-empty">행을 선택하면 아래에서 내용을 편집합니다.</p>}</div></>:section==='calendar'?<>
   <div className="notes-toolbar"><select aria-label="메모 일정 보기" value={calendarView} onChange={event=>navigate(()=>setCalendarView(event.target.value as typeof calendarView))}><option value="month">월간</option><option value="week">주간</option><option value="day">일간</option><option value="eisenhower">아이젠하워</option></select>{calendarView!=='eisenhower'&&<><button aria-label="이전 기간" onClick={()=>setFocusDate(moveCalendarPeriod(focusDate,calendarView,-1))}>이전</button><input aria-label="일정 기준일" type="date" value={focusDate} onChange={event=>{if(event.target.value)setFocusDate(event.target.value);}}/><button onClick={()=>setFocusDate(today())}>오늘</button><button aria-label="다음 기간" onClick={()=>setFocusDate(moveCalendarPeriod(focusDate,calendarView,1))}>다음</button></>}<button disabled={!dates.length} onClick={()=>{const sorted=[...dates].sort();make('schedules',sorted[0],sorted[sorted.length-1]);}}>선택 기간에 일정 추가</button><button disabled={!dates.length} onClick={()=>{setDates([]);setRangeAnchor(undefined);}}>날짜 선택 해제</button></div>
   {calendarView==='eisenhower'?<div className="notes-quadrants">{[{important:true,urgent:true,label:'중요 · 긴급'},{important:true,urgent:false,label:'중요 · 여유'},{important:false,urgent:true,label:'일상 · 긴급'},{important:false,urgent:false,label:'일상 · 여유'}].map(group=><section key={group.label}><h3>{group.label}</h3><div className="notes-board">{rows.filter(row=>(row.important===true)===group.important&&(row.urgent===true)===group.urgent).map(sheet)}</div></section>)}</div>:<div style={{overflowX:'auto'}}><div className={'notes-calendar '+calendarView}>{calendarDays(focusDate,calendarView).map(date=><section className="notes-calendar-cell" key={date} aria-selected={dates.includes(date)}><button aria-label={`${date} 선택`} onClick={event=>{setDates(previous=>calendarSelection(previous,date,event.shiftKey,rangeAnchor));if(!event.shiftKey)setRangeAnchor(date);}}>{date.slice(5)} {['일','월','화','수','목','금','토'][dateFrom(date).getDay()]}</button><button aria-label={`${date} 일정 입력`} onClick={()=>make('schedules',date)}>+</button>{notesOnDate(rows,date).map(row=><button key={row.__rowId} className="notes-calendar-entry" onClick={()=>navigate(()=>setChosen(row.__noteSource+':'+row.__rowId))}>{noteLabel(row)}</button>)}</section>)}</div></div>}{chosenRow&&<div className="notes-manager-detail">{sheet(chosenRow)}</div>}
  </>:<div className="notes-board">{rows.filter(row=>row.__rowId!==newSheet?.row?.__rowId).map(sheet)}</div>}
  {!rows.length&&!loading&&<p className="notes-empty">{trash?'휴지통이 비어 있습니다.':search?'검색 결과가 없습니다.':'아직 메모·일정이 없습니다.'}</p>}{loading&&<p role="status">불러오는 중…</p>}{error&&<p role="alert">{error}</p>}
 </section>;
}
