import {useEffect,useState} from 'react';
import {extensionCommand} from '../transport';
export function WorkPopup({report}:{report:(text:string)=>void}){
 const [detection,setDetection]=useState<any>(null),[frameId,setFrameId]=useState(''),[selection,setSelection]=useState<Record<string,string>>({}),[year,setYear]=useState(new Date().getFullYear()),[count,setCount]=useState(1000),[searchAfter,setSearchAfter]=useState(false),[busy,setBusy]=useState(false);
 async function run(action:any){try{setBusy(true);const result=await extensionCommand({type:'work.action',frameId:frameId===''?undefined:Number(frameId),action:{...action,selection,mode:action.kind==='detect'?'inspect':'apply'}});setDetection(result);report(result.message||result.status);if(result.frames?.length===1)setFrameId(String(result.frames[0].frameId));}catch(error){report(String(error));}finally{setBusy(false);}}
 useEffect(()=>{void run({kind:'detect'});},[]);
 const candidates=detection?.candidates||[];const frames=[...new Set<number>(candidates.map((candidate:any)=>candidate.frameId))];
 return <div className="feature-content"><h2>업무 화면 · 요소 선택</h2><p className="muted">자동으로 확정할 수 없는 화면이나 버튼은 직접 선택합니다. 찾기와 후보 선택은 페이지를 변경하지 않습니다.</p><div className="row"><button disabled={busy} onClick={()=>run({kind:'detect'})}>요소 다시 찾기</button><label>실행할 frame<select aria-label="업무 frame" value={frameId} onChange={event=>{setFrameId(event.target.value);setSelection({});}}><option value="">자동 판단</option>{frames.map(id=><option key={id} value={id}>frame {id}</option>)}</select></label></div><section className="panel form-grid">{(['startDate','endDate','rowCount','search','excel'] as const).map((role,index)=><label key={role}>{['시작일','종료일','조회 건수','조회 버튼','엑셀 버튼'][index]}<select aria-label={role+' 후보'} value={selection[role]||''} onChange={event=>setSelection({...selection,[role]:event.target.value})}><option value="">자동 판단</option>{candidates.filter((candidate:any)=>candidate.role===role&&(frameId===''||candidate.frameId===Number(frameId))).map((candidate:any)=><option key={candidate.frameId+candidate.id} value={candidate.id}>{candidate.label||candidate.elementId} · {candidate.value} · frame {candidate.frameId}</option>)}</select></label>)}</section><section className="panel"><div className="row"><button disabled={busy} onClick={()=>run({kind:'yearShift',years:-1,searchAfter})}>−1년</button><input type="number" aria-label="연간 조회 연도" value={year} onChange={event=>setYear(Number(event.target.value))}/><button disabled={busy} onClick={()=>run({kind:'yearShift',years:1,searchAfter})}>+1년</button><button disabled={busy} onClick={()=>run({kind:'yearRange',year,searchAfter})}>연간 기간 적용</button><label><input type="checkbox" checked={searchAfter} onChange={event=>setSearchAfter(event.target.checked)}/>기간 적용 후 조회</label></div><div className="row"><input type="number" aria-label="요청 건수" min="1" value={count} onChange={event=>setCount(Number(event.target.value))}/><button disabled={busy} onClick={()=>run({kind:'setRowCount',rowCount:count})}>조회 건수 적용</button><button disabled={busy} onClick={()=>run({kind:'search'})}>조회</button><button disabled={busy} onClick={()=>run({kind:'excel'})}>엑셀 다운로드</button></div></section>{detection&&<details><summary>판별 근거 · 경고</summary><pre>{JSON.stringify(detection,null,2)}</pre></details>}</div>;
}
