import {useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import {DataGrid,type Column,type RecordRow} from '../grid/index';
export function download(name:string,content:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function exportSheet(name:string,rows:RecordRow[],columns:Column[],format:'xlsx'|'csv',labels:boolean){const visible=columns.filter(c=>!c.field.startsWith('__')||c.field.startsWith('__virtual'));const output=[visible.map(c=>labels?c.label||c.field:c.field),...rows.map(r=>visible.map(c=>{const value=r[c.field];return value!==null&&typeof value==='object'?JSON.stringify(value):value??'';}))];const sheet=XLSX.utils.aoa_to_sheet(output);const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'자료');XLSX.writeFile(book,name+'.'+format,{bookType:format});}
export function ImportDialog({columns,headerMap,onApply,onClose}:{columns:Column[];headerMap:Record<string,string>;onApply:(rows:RecordRow[],columns:Column[],asNew:boolean,name:string)=>Promise<void>;onClose:()=>void}){
 const [matrix,setMatrix]=useState<any[][]>([]),[header,setHeader]=useState(1),[firstCol,setFirstCol]=useState(1),[lastCol,setLastCol]=useState(0),[lastRow,setLastRow]=useState(0),[mapping,setMapping]=useState<Record<number,string>>({}),[dedup,setDedup]=useState<string[]>([]),[name,setName]=useState('가져온 자료'),[asNew,setAsNew]=useState(!columns.length),[error,setError]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[onlyMapped,setOnlyMapped]=useState(false);
 function accept(sheet:any[][]){setMatrix(sheet);const candidate=sheet.findIndex(row=>row.some(v=>v!==null&&v!==undefined&&String(v).trim()));setHeader(candidate+1||1);setLastRow(sheet.length);setLastCol(Math.max(0,...sheet.map(r=>r.length)));setMapping({});setDedup([]);setFirstCol(1);setError('');}
 const heads=matrix[header-1]||[];
 const selectedColumns=useMemo(()=>heads.map((h,i)=>({i,field:mapping[i]??headerMap[String(h)]??String(h===null||h===undefined||h===''?`열${i+1}`:h)})).filter(h=>h.i>=firstCol-1&&h.i<(lastCol||heads.length)&&h.field&&(!onlyMapped||columns.some(c=>c.field===h.field)||!!headerMap[String(heads[h.i])])),[heads,mapping,firstCol,lastCol,onlyMapped,columns,headerMap]);
 const previewColumns=selectedColumns.map(h=>({field:h.field,label:h.field,kind:'text'}));
 const rawRows=matrix.slice(header,lastRow||matrix.length).filter(row=>row.some(v=>v!==''&&v!==null&&v!==undefined)).map((row,n)=>Object.fromEntries([['__rowId',`import-${n}`],...selectedColumns.map(h=>[h.field,row[h.i]??''])]));
 const rows=dedup.length?rawRows.filter((r,i,all)=>all.findIndex(x=>dedup.every(f=>JSON.stringify(x[f])===JSON.stringify(r[f])))===i):rawRows;
 async function apply(){try{setBusy(true);if(!selectedColumns.length)throw Error('가져올 열을 하나 이상 선택하세요.');if(asNew&&!name.trim())throw Error('새 자료집 이름을 입력하세요.');if(new Set(selectedColumns.map(c=>c.field)).size!==selectedColumns.length)throw Error('같은 대상 열이 반복됩니다. 헤더 매핑을 수정하세요.');await onApply(rows.map(({__rowId,...r})=>r),previewColumns,asNew,name);onClose();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="modal-shade"><section className="modal wide"><header><h2>자료 가져오기</h2><button onClick={onClose}>닫기</button></header><p className="muted">첫 시트만 읽습니다. 영역과 헤더를 확인한 뒤 적용하세요. 기존 표 추가는 편집 버퍼에 쌓이며 저장 버튼으로 확정합니다.</p><input aria-label="가져올 파일" type="file" accept=".xlsx,.xls,.csv,.tsv" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;const book=/\.(csv|tsv)$/i.test(file.name)?XLSX.read(await file.text(),{type:'string',raw:true}):XLSX.read(await file.arrayBuffer(),{type:'array'});accept(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,defval:'',raw:false}));setName(file.name.replace(/\.[^.]+$/,''));}catch(err){setError(String(err));}}}/><details><summary>클립보드 텍스트</summary><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Excel에서 복사한 내용을 붙여넣으세요"/><button onClick={()=>accept(text.replace(/\r/g,'').split('\n').map(r=>r.split('\t')))}>텍스트 읽기</button></details><div className="row"><label>헤더 행 <input type="number" min="1" value={header} onChange={e=>setHeader(+e.target.value)}/></label><label>시작 열 <input type="number" min="1" value={firstCol} onChange={e=>setFirstCol(+e.target.value)}/></label><label>마지막 열 <input type="number" value={lastCol} onChange={e=>setLastCol(+e.target.value)}/></label><label>마지막 행 <input type="number" value={lastRow} onChange={e=>setLastRow(+e.target.value)}/></label></div><div className="row"><label><input type="checkbox" checked={asNew} onChange={e=>setAsNew(e.target.checked)}/>독립 Dataset 생성</label>{asNew&&<input aria-label="새 Dataset 이름" value={name} onChange={e=>setName(e.target.value)}/>}<label><input type="checkbox" checked={onlyMapped} onChange={e=>setOnlyMapped(e.target.checked)}/>기존 열·사전 매핑 열만</label></div><div className="mapping">{heads.map((h,i)=><label key={i}>{String(h)||`빈 헤더 ${i+1}`} → <input value={mapping[i]??headerMap[String(h)]??String(h===null||h===undefined||h===''?`열${i+1}`:h)} onChange={e=>setMapping({...mapping,[i]:e.target.value})}/>{!columns.some(c=>c.field===selectedColumns.find(x=>x.i===i)?.field)&&<small>추가 열</small>}</label>)}</div><details><summary>중복 제거 기준 열 · {rawRows.length-rows.length}행 제외 예정</summary>{previewColumns.map(c=><label key={c.field}><input type="checkbox" checked={dedup.includes(c.field)} onChange={e=>setDedup(e.target.checked?[...dedup,c.field]:dedup.filter(f=>f!==c.field))}/>{c.label} </label>)}</details><div className="preview-grid"><DataGrid rows={rows.slice(0,100)} columns={previewColumns} readOnly/></div><p>{rows.length}행 적용 예정 · 미리보기 최대 100행</p>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy||!rows.length||!selectedColumns.length} onClick={apply}>미리보기 승인·적용</button></section></div>;
}
