import { useEffect, useRef } from 'react';
import { TabulatorFull as Tabulator } from 'tabulator-tables';
export type Column = {field:string;label?:string;kind?:string;editable?:boolean;hidden?:boolean;frozen?:boolean;values?:Record<string,string>};
export type RecordRow = Record<string, any>;
export type GridHandle = {rows:()=>RecordRow[]; selected:()=>RecordRow[]; add:(rows:RecordRow[])=>void; remove:()=>void; fillDown:()=>void};
export type GridProps={rows:RecordRow[];columns:Column[];readOnly?:boolean;singleClickEdit?:boolean;onChange?:(rows:RecordRow[],deletedIds?:string[])=>void;onSelect?:(row:RecordRow)=>void;onCellSelect?:(row:RecordRow,field:string)=>void;onAddColumn?:()=>void;editableTitles?:string[];onColumnTitleChange?:(field:string,title:string)=>void;transformEdit?:(value:unknown,row:RecordRow,column:Column)=>unknown;onEditError?:(reason:unknown)=>void;handle?:(grid:GridHandle|null)=>void};
export function DataGrid({rows,columns,readOnly=false,singleClickEdit=false,onChange,onSelect,onCellSelect,onAddColumn,editableTitles=[],onColumnTitleChange,transformEdit,onEditError,handle}:GridProps){
 const element=useRef<HTMLDivElement>(null); const callbacks=useRef({onChange,onSelect,onCellSelect,onAddColumn,onColumnTitleChange,transformEdit,onEditError,handle}); callbacks.current={onChange,onSelect,onCellSelect,onAddColumn,onColumnTitleChange,transformEdit,onEditError,handle};
 useEffect(()=>{if(!element.current)return;let ready=false;
 const emit=()=>{if(ready)callbacks.current.onChange?.(grid.getData());};
 const coerce=(input:any,c:Column,row:RecordRow={})=>{let v=input;try{v=callbacks.current.transformEdit?.(input,row,c)??input;}catch(reason){callbacks.current.onEditError?.(reason);return row[c.field];}if(c.kind==='json'&&typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}if(c.kind==='boolean'){if(v==='true')return true;if(v==='false')return false;}if(c.kind==='integer'&&/^[-+]?\d+$/.test(String(v))&&Number.isSafeInteger(Number(v)))return Number(v);return v;};
 const grid:any=new Tabulator(element.current, {data:structuredClone(rows),index:'__rowId',nestedFieldSeparator:false,height:'100%',layout:'fitDataStretch',placeholder:'표에 자료가 없습니다. 가져오기 또는 행 추가를 사용하세요.',selectableRange:1,selectableRangeColumns:true,headerSortClickElement:'icon',selectableRangeRows:true,selectableRangeClearCells:false,editTriggerEvent:'dblclick',clipboard:true,clipboardCopyStyled:false,clipboardCopyRowRange:'range',clipboardCopyConfig:{rowHeaders:false,columnHeaders:false},clipboardPasteParser:'range',clipboardPasteAction:readOnly?undefined:(data:any[])=>{const range=grid.getRanges()[0];if(!range||!data.length)return [];const chosen=range.getRows();const active=grid.getRows('active');const start=active.findIndex((row:any)=>row.getData().__rowId===chosen[0]?.getData().__rowId);const count=range.getCells().flat().length===1?data.length:chosen.length;const affected=active.slice(start,start+count);for(const [i,row] of affected.entries()){for(const [field,value] of Object.entries(data[i%data.length])){const column=columns.find(c=>c.field===field);if(column&&column.editable!==false)row.getCell(field)?.setValue(coerce(value,column,row.getData()));}}emit();return affected;},rowHeader:{width:45,formatter:'rownum',hozAlign:'center',headerSort:false,frozen:true,resizable:false},columns:columns.filter(c=>!c.field.startsWith('__')||c.field.startsWith('__virtual')).map(c=>({title:c.label||c.field,field:c.field,visible:!c.hidden,frozen:!!c.frozen,minWidth:140,headerSort:true,editor:readOnly||c.editable===false?false:'input',editableTitle:!readOnly&&editableTitles.includes(c.field),mutatorEdit:(v:any,_data:RecordRow,_type:string,_params:unknown,cell:any)=>coerce(v,c,cell.getRow().getData()),formatter:(cell:any)=>{const v=cell.getValue();const span=document.createElement('span');span.textContent=v===null?'null':typeof v==='object'?JSON.stringify(v):c.values?.[String(v)]??String(v??'');return span;}})).concat(onAddColumn&&!readOnly?[{title:'+',field:'__addColumn',width:42,minWidth:42,headerSort:false,resizable:false,editor:false,clipboard:false,formatter:()=>'',titleFormatter:()=>{const button=document.createElement('button');button.type='button';button.textContent='+';button.setAttribute('aria-label','열 추가');button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();callbacks.current.onAddColumn?.();});return button;}} as any]:[])} as any);
 const selectCell=(cell:any)=>{if(!cell||cell.getField()==='__addColumn')return;callbacks.current.onSelect?.(cell.getRow().getData());callbacks.current.onCellSelect?.(cell.getRow().getData(),cell.getField());};
 grid.on('tableBuilt',()=>{ready=true;});grid.on('cellEdited',(cell:any)=>{emit();selectCell(cell);});grid.on('clipboardPasted',emit);
 grid.on('cellClick',(_e:any,cell:any)=>selectCell(cell));grid.on('columnTitleChanged',(column:any)=>callbacks.current.onColumnTitleChange?.(column.getField(),column.getDefinition().title));
 grid.on('rangeChanged',(range:any)=>{const first=range.getCells()?.[0]?.[0];selectCell(first);});
 // Range selection can suppress Tabulator's cellClick when the current cell is
 // clicked again after layout changes. The context pane follows the actual row.
 const selectContext=(event:MouseEvent)=>{const target=event.target;if(!(target instanceof Element))return;const line=target.closest('.tabulator-row');const chosen=line?grid.getRows('active').find((row:any)=>row.getElement()===line):target.closest('.tabulator-range-overlay')?grid.getRanges()[0]?.getCells()?.[0]?.[0]?.getRow():undefined;if(chosen){callbacks.current.onSelect?.(chosen.getData());const targetCell=target.closest('.tabulator-cell');const field=targetCell?.getAttribute('tabulator-field');const activeCell=field?chosen.getCell(field):grid.getRanges()[0]?.getCells()?.[0]?.[0];selectCell(activeCell);}if(singleClickEdit&&!readOnly&&!event.ctrlKey&&!event.shiftKey&&!event.metaKey&&event.detail===1&&!(target instanceof HTMLInputElement)&&!(target instanceof HTMLTextAreaElement)){const cells=grid.getRanges()[0]?.getCells()?.flat()||[];if(cells.length===1){const cell=cells[0];const column=columns.find(c=>c.field===cell.getField());if(column&&column.editable!==false)requestAnimationFrame(()=>requestAnimationFrame(()=>{if(ready)cell.edit();}));}}};
 element.current.addEventListener('click',selectContext,true);
 const key=(e:KeyboardEvent)=>{if(readOnly||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;const ranges=grid.getRanges();const cell=ranges[0]?.getCells()?.[0]?.[0];if(!cell)return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();e.stopImmediatePropagation();for(const chosen of ranges[0].getCells().flat()){const column=columns.find(c=>c.field===chosen.getField());if(column&&column.editable!==false)chosen.setValue('');}emit();return;}if(e.key==='F2'){e.preventDefault();cell.edit();}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();cell.edit();const seed=()=>{const input=cell.getElement().querySelector('input');if(input){input.value=e.key;input.setSelectionRange(input.value.length,input.value.length);input.dispatchEvent(new Event('input',{bubbles:true}));}};if(cell.getElement().querySelector('input'))seed();else queueMicrotask(seed);}};
 element.current.addEventListener('keydown',key,true);
 const api:GridHandle={rows:()=>grid.getData('active'),selected:()=>{const cells=grid.getRanges()[0]?.getCells()||[];return [...new Map(cells.flat().map((c:any)=>[c.getRow().getData().__rowId,c.getRow().getData()])).values()] as RecordRow[];},add:(newRows)=>{if(!readOnly)grid.addData(newRows).then(emit);},remove:()=>{if(readOnly)return;const ids=api.selected().map(r=>r.__rowId);Promise.all(ids.map(id=>grid.deleteRow(id))).then(()=>callbacks.current.onChange?.(grid.getData(),ids));},fillDown:()=>{if(readOnly)return;const range=grid.getRanges()[0]?.getCells()||[];if(range.length<2)return;range.slice(1).forEach((line:any[])=>line.forEach((cell:any,i:number)=>{const column=columns.find(c=>c.field===cell.getField());if(column&&column.editable!==false)cell.setValue(range[0][i].getValue());}));emit();}};
 callbacks.current.handle?.(api); const node=element.current;
 return()=>{ready=false;node.removeEventListener('keydown',key,true);node.removeEventListener('click',selectContext,true);callbacks.current.handle?.(null);grid.destroy();};
 },[rows,columns,readOnly,singleClickEdit,!!onAddColumn,editableTitles.join('|')]);
 return <div className="grid-host" ref={element}/>;
}


