import { useEffect, useState } from 'react';
import type { BookmarkletPlugin, LocalDocument, PrototypeLauncher, PrototypeServices } from '../contracts';
import { useUnsavedChanges } from '../lifecycle';
import { listDocuments, putDocument, removeDocument, validatePrototypeValue } from '../storage';

export function LauncherPanel({ services }: { services: PrototypeServices }) {
  const [entries, setEntries] = useState<LocalDocument<PrototypeLauncher>[]>([]), [editing, setEditing] = useState<LocalDocument<PrototypeLauncher> | null>(null);
  const [name, setName] = useState(''), [target, setTarget] = useState(''), [kind, setKind] = useState<PrototypeLauncher['kind']>('url');
  const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false);useUnsavedChanges(dirty);
  const report = (error: unknown) => services.notify('실패: ' + (error instanceof Error ? error.message : String(error)));
  async function refresh() { try { setEntries(await listDocuments<PrototypeLauncher>('launchers')); } catch (error) { report(error); } }
  useEffect(() => { void refresh(); }, []);
  function begin(entry?: LocalDocument<PrototypeLauncher>) { if(dirty&&!confirm('저장하지 않은 런처 변경을 버릴까요?'))return;setDirty(false); setEditing(entry ?? null); setName(entry?.value.name ?? ''); setTarget(entry?.value.target ?? ''); setKind(entry?.value.kind ?? 'url'); }
  return <div className="two-pane"><section className="panel"><span className="eyebrow">QUICK LAUNCH</span><h2>자주 쓰는 업무 바로가기</h2><div className="launcher-cards">{entries.map(entry => <article className="launcher-card" key={entry.documentId}><span>{entry.value.kind === 'url' ? '↗' : '⌘'}</span><strong>{entry.value.name}</strong><small>{entry.value.kind === 'url' ? entry.value.target : '수동 페이지 스크립트'}</small><div className="row">{entry.value.kind === 'url' ? <a className="button primary" href={entry.value.target} target="_blank" rel="noopener noreferrer">열기</a> : <button className="primary" onClick={() => { if (!confirm(`'${entry.value.name}'의 저장된 코드를 이 페이지에서 실행할까요?\n\n${entry.value.target.slice(0, 500)}`)) return; try { const script = document.createElement('script'); script.textContent = `try { ${entry.value.target}\n } catch (error) { alert('PCE 스크립트 오류: '+ error.message); }`; document.documentElement.append(script); script.remove(); services.notify('페이지 스크립트 실행을 요청했습니다. 사이트 CSP가 실행을 차단할 수 있습니다.'); } catch (error) { report(error); } }}>코드 확인·수동 실행</button>}<button onClick={() => begin(entry)}>편집</button><button onClick={async () => { if (!confirm('이 바로가기를 삭제할까요?')) return; try { await removeDocument('launchers', entry.documentId, entry.storeVersion); await refresh(); } catch (error) { report(error); } }}>삭제</button></div></article>)}</div>{!entries.length && <p className="muted">오른쪽에서 첫 바로가기를 추가하세요.</p>}</section><section className="panel editor"><h2>{editing ? '바로가기 편집' : '새 바로가기'}</h2><label>이름<input aria-label="런처 이름" value={name} onChange={event => {setName(event.target.value);setDirty(true);}} /></label><label>종류<select aria-label="런처 종류" value={kind} onChange={event => {setKind(event.target.value as PrototypeLauncher['kind']);setDirty(true);}}><option value="url">웹 URL · 직링크</option><option value="script">수동 페이지 스크립트</option></select></label><label>{kind === 'url' ? '웹 주소' : 'JavaScript 코드'}<textarea aria-label="런처 대상" value={target} onChange={event => {setTarget(event.target.value);setDirty(true);}} placeholder={kind === 'url' ? 'https://...' : '직접 작성한 코드를 확인 후 수동 실행합니다.'} /></label><div className="row"><button className="primary" disabled={busy} onClick={async () => { try { setBusy(true);const value = { name: name.trim(), kind, target: target.trim() }; validatePrototypeValue('launchers', value); await putDocument('launchers', editing?.documentId ?? crypto.randomUUID(), editing?.storeVersion ?? null, value); setEditing(null);setName('');setTarget('');setDirty(false);await refresh(); services.notify('바로가기를 저장했습니다. 자동 실행은 하지 않습니다.'); } catch (error) { report(error); }finally{setBusy(false);} }}>런처 저장</button><button onClick={() => begin()}>새로 작성</button></div><p className="muted">PC 파일 실행은 데스크탑/확장 연결 기능입니다. 이 프로토타입은 웹 링크와 직접 작성한 코드의 수동 실행을 제공합니다. Tampermonkey 호환 실행기는 아닙니다.</p></section></div>;
}
export const launcherPlugin: BookmarkletPlugin = { id: 'prototype.launcher', label: '런처', features: ['url', 'manual-page-script'], component: LauncherPanel };
