import { useEffect, useRef, useState } from 'react';
import type { BookmarkletPlugin, LocalDocument, PrototypeNote, PrototypeServices } from '../contracts';
import { listDocuments, putDocument, removeDocument, validatePrototypeValue } from '../storage';

const blankNote = (): PrototypeNote => ({ title: '', body: '', kind: 'memo', scope: 'general', done: false, startsOn: new Date().toLocaleDateString('sv-SE'), endsOn: new Date().toLocaleDateString('sv-SE') });
export function NotesPanel({ services }: { services: PrototypeServices }) {
  const [entries, setEntries] = useState<LocalDocument<PrototypeNote>[]>([]), [editing, setEditing] = useState<LocalDocument<PrototypeNote> | null>(null);
  const [draft, setDraft] = useState<PrototypeNote>(blankNote), [view, setView] = useState('all'), [search, setSearch] = useState(''), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false);
  const dirtyRef = useRef(dirty); dirtyRef.current=dirty;
  useEffect(()=>{const closing=(event:Event)=>{if(dirtyRef.current)event.preventDefault();};window.addEventListener('pce:close-check',closing);return ()=>window.removeEventListener('pce:close-check',closing);},[]);
  const report = (error: unknown) => services.notify('실패: ' + (error instanceof Error ? error.message : String(error)));
  async function refresh() { try { setEntries(await listDocuments<PrototypeNote>('notes')); } catch (error) { report(error); } }
  useEffect(() => { void refresh(); }, []);
  function update(values: Partial<PrototypeNote>) { setDraft({ ...draft, ...values }); setDirty(true); }
  function begin(entry?: LocalDocument<PrototypeNote>) { if (dirty && !confirm('저장하지 않은 메모 변경을 버릴까요?')) return; setEditing(entry ?? null); setDraft(entry ? structuredClone(entry.value) : blankNote()); setDirty(false); }
  async function save() {
    try {
      setBusy(true); let next = { ...draft, title: draft.title.trim() };
      if (next.scope === 'screen') next = { ...next, screenUrl: location.origin + location.pathname + location.search };
      if (next.scope === 'record' && !next.rowId) { if (!services.selection) throw new Error('DB에서 연결할 행을 먼저 선택하세요.'); next = { ...next, datasetId: services.selection.datasetId, rowId: services.selection.rowId }; }
      validatePrototypeValue('notes', next as unknown as Record<string, unknown>);
      const saved = await putDocument('notes', editing?.documentId ?? crypto.randomUUID(), editing?.storeVersion ?? null, next); setEditing(saved); setDraft(saved.value); setDirty(false); await refresh(); services.notify('메모·일정을 저장했습니다.');
    } catch (error) { report(error); } finally { setBusy(false); }
  }
  const visible = entries.filter(entry => (view === 'all' || entry.value.kind === view || (view === 'screen' && entry.value.scope === 'screen' && entry.value.screenUrl === location.origin + location.pathname + location.search) || (view === 'record' && entry.value.rowId === services.selection?.rowId && entry.value.datasetId === services.selection?.datasetId)) && (entry.value.title + '\n' + entry.value.body).includes(search)).sort((a, b) => (a.value.startsOn ?? '').localeCompare(b.value.startsOn ?? ''));
  return <div className="two-pane"><section className="panel"><span className="eyebrow">NOTES & SCHEDULE</span><h2>기억할 일, 해야 할 일</h2><div className="row"><button className="primary" onClick={() => begin()}>+ 새 메모·일정</button><button onClick={refresh}>목록 새로고침</button></div><div className="row"><select aria-label="메모 보기" value={view} onChange={event => setView(event.target.value)}><option value="all">전체</option><option value="memo">메모</option><option value="schedule">일정</option><option value="screen">현재 화면</option><option value="record">선택 레코드</option></select><input aria-label="메모 검색" value={search} onChange={event => setSearch(event.target.value)} placeholder="메모 내용 검색" /></div><div className="cards">{visible.map(entry => <button key={entry.documentId} className={'note-card ' + (editing?.documentId === entry.documentId ? 'active' : '')} onClick={() => begin(entry)}><small>{entry.value.kind === 'schedule' ? `${entry.value.startsOn} — ${entry.value.endsOn}` : '메모'} · {entry.value.scope === 'general' ? '일반' : entry.value.scope === 'screen' ? '화면 연결' : '레코드 연결'} {entry.value.done ? '· 완료' : ''}</small><strong>{entry.value.title}</strong><span>{entry.value.body.slice(0, 150)}</span></button>)}</div>{!visible.length && <p className="muted">등록된 내용이 없습니다.</p>}<p className="muted">달력·아이젠하워·칸반, 드래그, 반복·알림과 스티커메모 전체는 2차 범위로 유지합니다.</p></section>
    <section className="panel editor"><h2>{editing ? '메모·일정 편집' : '새 메모·일정'}</h2><label>제목<input aria-label="메모 제목" value={draft.title} onChange={event => update({ title: event.target.value })} /></label><div className="row"><select aria-label="메모 종류" value={draft.kind} onChange={event => update({ kind: event.target.value as PrototypeNote['kind'] })}><option value="memo">메모</option><option value="schedule">기간 일정</option></select><select aria-label="메모 연결" value={draft.scope} onChange={event => update({ scope: event.target.value as PrototypeNote['scope'], rowId: undefined, datasetId: undefined })}><option value="general">일반</option><option value="screen">현재 화면</option><option value="record">선택한 레코드</option></select></div>{draft.scope === 'record' && <p className="muted">{draft.rowId ? '기존 레코드 연결 유지' : services.selection ? `${services.selection.datasetName} · ${services.selection.rowId}` : 'DB에서 행을 선택하세요.'}</p>}{draft.scope === 'screen' && <p className="muted">{location.origin + location.pathname + location.search}</p>}{draft.kind === 'schedule' && <div className="row"><label>시작<input aria-label="일정 시작" type="date" value={draft.startsOn ?? ''} onChange={event => update({ startsOn: event.target.value })} /></label><label>종료<input aria-label="일정 종료" type="date" value={draft.endsOn ?? ''} onChange={event => update({ endsOn: event.target.value })} /></label></div>}<label>내용<textarea aria-label="메모 내용" value={draft.body} onChange={event => update({ body: event.target.value })} /></label><label><input type="checkbox" checked={draft.done} onChange={event => update({ done: event.target.checked })} />완료</label><div className="row"><button className="primary" disabled={busy} onClick={save}>메모·일정 저장</button><span className="muted">{dirty ? '저장 전 변경 있음' : ''}</span>{editing && <button className="danger" onClick={async () => { if (!confirm('이 메모·일정을 삭제할까요?')) return; try { await removeDocument('notes', editing.documentId, editing.storeVersion); setEditing(null); setDraft(blankNote()); setDirty(false); await refresh(); services.notify('메모·일정을 삭제했습니다.'); } catch (error) { report(error); } }}>삭제</button>}</div></section></div>;
}
export const notesPlugin: BookmarkletPlugin = { id: 'prototype.notes', label: '메모·일정', features: ['memo', 'period-schedule', 'screen-link', 'record-link'], component: NotesPanel };
