import { useEffect, useState } from 'react';
import { performPageAction } from '../../../plugins/page-actions/index';
import { readSetting, writeSetting } from '../outbox';
import type { PrototypeServices } from '../contracts';

const defaults = { start: '', end: '', search: '', excel: '', count: '' };
export function PageActions({ services }: { services: PrototypeServices }) {
  const [bindings, setBindings] = useState(defaults), [days, setDays] = useState('7'), [start, setStart] = useState(''), [end, setEnd] = useState(''), [ready, setReady] = useState(false);
  const report = (error: unknown) => services.notify('실패: ' + (error instanceof Error ? error.message : String(error)));
  useEffect(() => { readSetting('work.pageBindings', defaults).then(value => { if (!value || Object.values(value).some(selector => typeof selector !== 'string')) throw new Error('업무 요소 설정 형식을 확인하세요.'); setBindings({ ...defaults, ...value }); setReady(true); }).catch(report); }, []);
  function action(kind: 'click' | 'setValue' | 'dateShift' | 'readText', selector: string, value?: string, amount?: number) { try { if (!ready || !selector.trim()) throw new Error('먼저 업무 요소의 CSS 선택자를 설정하고 저장하세요.'); const result = performPageAction({ kind, selector, value, days: amount }); services.notify('업무 요소 실행: ' + JSON.stringify(result)); return true; } catch (error) { report(error); return false; } }
  return <details className="page-actions"><summary>기간 변경 · 조회 · 조회 건수 · Excel 다운로드</summary><p className="muted">현재 문서에서 사용자가 확인한 CSS 선택자 하나를 지정합니다. 추출로 수집 화면값을 볼 수 있습니다.</p><div className="row">{(Object.entries({ start: '시작 입력', end: '종료 입력', search: '조회 버튼', excel: 'Excel 버튼', count: '건수 표시' }) as [keyof typeof defaults, string][]).map(([field, label]) => <label key={field}>{label}<input aria-label={'업무 ' + label + ' 선택자'} placeholder="CSS 선택자" value={bindings[field]} onChange={event => setBindings({ ...bindings, [field]: event.target.value })} /></label>)}<button disabled={!ready} onClick={async () => { try { await writeSetting('work.pageBindings', bindings); services.notify('이 사이트의 업무 요소 설정을 저장했습니다.'); } catch (error) { report(error); } }}>업무 요소 설정 저장</button></div><div className="row"><input aria-label="업무 시작일" type="date" value={start} onChange={event => setStart(event.target.value)} /><button onClick={() => action('setValue', bindings.start, start)}>시작일 입력</button><input aria-label="업무 종료일" type="date" value={end} onChange={event => setEnd(event.target.value)} /><button onClick={() => action('setValue', bindings.end, end)}>종료일 입력</button><input aria-label="업무 이동 일수" type="number" value={days} onChange={event => setDays(event.target.value)} /><button onClick={() => { if (action('dateShift', bindings.start, undefined, Number(days))) action('dateShift', bindings.end, undefined, Number(days)); }}>기간 이동</button><button onClick={() => action('click', bindings.search)}>조회 실행</button><button onClick={() => action('readText', bindings.count)}>조회 건수 확인</button><button onClick={() => action('click', bindings.excel)}>화면 Excel 다운로드</button></div></details>;
}
