import { useEffect, useMemo, useState } from 'react';
import type { RelationDefinition } from '../../../packages/contracts/src/index';
import type { BookmarkletPlugin, LocalDocument, PrototypeDataset, PrototypeServices } from '../contracts';
import { listDocuments, putDocument, removeDocument, validatePrototypeValue } from '../storage';

type RelationDraft = Omit<RelationDefinition, 'id'>;
const blank = (): RelationDraft => ({ name: '', leftSourceId: '', rightSourceId: '', fieldPairs: [{ left: '', right: '' }], cardinality: 'many' });
export function RelationsPanel({ services }: { services: PrototypeServices }) {
  const [datasets, setDatasets] = useState<LocalDocument<PrototypeDataset>[]>([]), [entries, setEntries] = useState<LocalDocument<RelationDraft>[]>([]), [editing, setEditing] = useState<LocalDocument<RelationDraft> | null>(null), [draft, setDraft] = useState<RelationDraft>(blank);
  const [preview, setPreview] = useState(false);
  const report = (error: unknown) => services.notify('실패: ' + (error instanceof Error ? error.message : String(error)));
  async function refresh() { try { setDatasets(await services.datasets()); setEntries(await listDocuments<RelationDraft>('relations')); } catch (error) { report(error); } }
  useEffect(() => { void refresh(); }, []);
  const left = datasets.find(entry => entry.documentId === draft.leftSourceId), right = datasets.find(entry => entry.documentId === draft.rightSourceId);
  const complete = !!left && !!right && draft.fieldPairs.every(pair => left.value.columns.some(column => column.field === pair.left) && right.value.columns.some(column => column.field === pair.right));
  const matches = useMemo(() => !complete ? [] : left!.value.rows.map(row => ({ row, connected: right!.value.rows.filter(candidate => draft.fieldPairs.every(pair => row[pair.left] !== '' && row[pair.left] != null && JSON.stringify(row[pair.left]) === JSON.stringify(candidate[pair.right]))) })), [left, right, draft, complete]);
  const unmatched = matches.filter(entry => !entry.connected.length).length, multiple = matches.filter(entry => entry.connected.length > 1).length;
  function change(values: Partial<RelationDraft>) { setDraft({ ...draft, ...values }); setPreview(false); }
  return <div className="two-pane"><section className="panel"><h2>관계 중앙 관리</h2><p className="muted">자료집의 값을 병합·삭제하지 않고 연결 결과를 조회합니다. 업무번호와 차수는 열 쌍을 추가하여 함께 비교하세요. 표 설정에서도 이 관계 관리 화면을 사용합니다.</p>{entries.map(entry => <div className="row" key={entry.documentId}><button onClick={() => { setEditing(entry); setDraft(structuredClone(entry.value)); setPreview(false); }}>{entry.value.name}</button><button onClick={async () => { if (!confirm('이 관계 정의를 삭제할까요? 원본 표는 유지됩니다.')) return; try { await removeDocument('relations', entry.documentId, entry.storeVersion); await refresh(); } catch (error) { report(error); } }}>삭제</button></div>)}<button onClick={() => { setEditing(null); setDraft(blank()); setPreview(false); }}>+ 새 관계</button><h3>연결 결과 미리보기</h3>{preview && <><p>전체 {matches.length}행 · 미연결 {unmatched}행 · 다중 매칭 {multiple}행</p><div className="relation-preview"><table><thead><tr><th>기준 레코드</th><th>연결 수</th><th>대상 레코드</th></tr></thead><tbody>{matches.slice(0, 100).map(entry => <tr key={entry.row.__rowId}><td>{JSON.stringify(Object.fromEntries(Object.entries(entry.row).filter(([key]) => !key.startsWith('__'))))}</td><td>{entry.connected.length}</td><td>{JSON.stringify(entry.connected.map(({ __rowId, __storeVersion, ...values }) => values))}</td></tr>)}</tbody></table></div><small>미리보기 최대 100행. 연결 수는 전체 자료집 기준입니다.</small></>}</section>
    <section className="panel editor"><h2>관계 설정</h2><label>이름<input aria-label="관계 이름" value={draft.name} onChange={event => change({ name: event.target.value })} /></label><label>기준 표<select aria-label="관계 기준 표" value={draft.leftSourceId} onChange={event => change({ leftSourceId: event.target.value, fieldPairs: [{ left: '', right: '' }] })}><option value="">선택</option>{datasets.map(entry => <option key={entry.documentId} value={entry.documentId}>{entry.value.name}</option>)}</select></label><label>대상 표<select aria-label="관계 대상 표" value={draft.rightSourceId} onChange={event => change({ rightSourceId: event.target.value, fieldPairs: [{ left: '', right: '' }] })}><option value="">선택</option>{datasets.map(entry => <option key={entry.documentId} value={entry.documentId}>{entry.value.name}</option>)}</select></label>{draft.fieldPairs.map((pair, index) => <div className="row" key={index}><select aria-label={'기준 연결 열 ' + (index + 1)} value={pair.left} onChange={event => change({ fieldPairs: draft.fieldPairs.map((entry, position) => position === index ? { ...entry, left: event.target.value } : entry) })}><option value="">기준 열</option>{left?.value.columns.map(column => <option value={column.field} key={column.field}>{column.label}</option>)}</select><span>＝</span><select aria-label={'대상 연결 열 ' + (index + 1)} value={pair.right} onChange={event => change({ fieldPairs: draft.fieldPairs.map((entry, position) => position === index ? { ...entry, right: event.target.value } : entry) })}><option value="">대상 열</option>{right?.value.columns.map(column => <option value={column.field} key={column.field}>{column.label}</option>)}</select><button disabled={draft.fieldPairs.length === 1} onClick={() => change({ fieldPairs: draft.fieldPairs.filter((_, position) => position !== index) })}>×</button></div>)}<button onClick={() => change({ fieldPairs: [...draft.fieldPairs, { left: '', right: '' }] })}>+ 연결 열 쌍</button><label>다중 매칭 정책<select aria-label="관계 다중 매칭" value={draft.cardinality} onChange={event => change({ cardinality: event.target.value as 'one' | 'many' })}><option value="many">복수 연결 허용</option><option value="one">단일 연결 · 위반 시 검토</option></select></label><div className="row"><button disabled={!complete} onClick={() => setPreview(true)}>관계 미리보기</button><button className="primary" disabled={!preview || !complete || (draft.cardinality === 'one' && multiple > 0)} onClick={async () => { try { if (!draft.name.trim()) throw new Error('관계 이름을 입력하세요.'); validatePrototypeValue('relations', draft as unknown as Record<string, unknown>); const saved = await putDocument('relations', editing?.documentId ?? crypto.randomUUID(), editing?.storeVersion ?? null, draft); setEditing(saved); await refresh(); services.notify('관계 정의를 저장했습니다. 원본 레코드는 변경하지 않았습니다.'); } catch (error) { report(error); } }}>관계 저장</button></div>{draft.cardinality === 'one' && multiple > 0 && preview && <p className="error">단일 연결을 위반하는 {multiple}행이 있습니다. 조건이나 다중 매칭 정책을 조정하세요.</p>}</section></div>;
}
export const relationsPlugin: BookmarkletPlugin = { id: 'prototype.relations', label: '관계 관리', features: ['relations', 'match-preview', 'cardinality'], component: RelationsPanel };
