import { useState } from 'react';
import type { BookmarkletPlugin, PrototypeServices } from '../contracts';
import { exportPrototypeBackup, importTransferBundle, parsePrototypeBackup, parseTransferBundle, restorePrototypeBackup, type PrototypeBackup } from '../storage';
import { download } from '../../../plugins/files/index';

export function SettingsPanel({ services }: { services: PrototypeServices }) {
  const [backup, setBackup] = useState<PrototypeBackup | null>(null), [busy, setBusy] = useState(false), [target, setTarget] = useState<PrototypeBackup | null>(null);
  const report = (error: unknown) => services.notify('실패: ' + (error instanceof Error ? error.message : String(error)));
  return <div className="two-pane"><section className="panel"><span className="eyebrow">PORTABLE WORKSPACE</span><h2>백업과 다른 사이트에서 가져오기</h2><p>이 사이트의 수집 보관함, 독립 자료집, 메모·일정, 런처, 관계, 템플릿과 설정을 함께 보관합니다.</p><button className="primary" disabled={busy} onClick={async () => { try { setBusy(true); const contents = await exportPrototypeBackup(); download('pce-bookmarklet-backup-' + Date.now() + '.json', JSON.stringify(contents, null, 2)); services.notify('전체 백업 JSON 다운로드를 요청했습니다. 원본은 유지됩니다.'); } catch (error) { report(error); } finally { setBusy(false); } }}>북마크릿 전체 백업</button><h3>전체 백업 복원</h3><input aria-label="북마크릿 백업 파일" type="file" accept=".json" onChange={async event => { setBackup(null); setTarget(null); try { const file = event.target.files?.[0]; if (!file) return; if (file.size > 256 * 1024 * 1024) throw new Error('가져오기는 256MB 이하 파일을 사용하세요.'); const parsed = parsePrototypeBackup(JSON.parse(await file.text())); const snapshot = await exportPrototypeBackup(); setTarget(snapshot); setBackup(parsed); services.notify('백업을 검증했습니다. 출처와 교체 수량을 확인한 뒤 복원하세요.'); } catch (error) { report(error); } }} />{backup && <div className="restore-preview"><p>백업 출처: {backup.origin}<br/>대상: {location.origin}<br/>수집 {target?.captures.length ?? 0} → {backup.captures.length}건 · 설정·문서 {target?.settings.length ?? 0} → {backup.settings.length}개</p><p>현재 사이트의 보관함과 문서를 이 백업으로 교체합니다. 현재 자료는 먼저 전체 백업할 수 있습니다. 복원 후 패널을 다시 엽니다.</p><button className="danger" disabled={busy} onClick={async () => { try { setBusy(true); const pending:Promise<void>[]=[];window.dispatchEvent(new CustomEvent('pce:automation-pause',{detail:pending}));await Promise.all(pending);await restorePrototypeBackup(backup, target!); setBackup(null); services.notify('전체 복원 완료. 최신 자료를 읽기 위해 PCE를 닫은 뒤 다시 실행하세요.'); window.dispatchEvent(new CustomEvent('pce:backup-restored')); } catch (error) { report(error); } finally { setBusy(false); } }}>백업 내용으로 교체·복원</button></div>}<h3>PCE 수집 전달 JSON</h3><input aria-label="PCE 수집 전달 파일" type="file" accept=".json" onChange={async event => { try { const file = event.target.files?.[0]; if (!file) return; if (file.size > 256 * 1024 * 1024) throw new Error('가져오기는 256MB 이하 파일을 사용하세요.'); const bundle = parseTransferBundle(JSON.parse(await file.text())); if (!confirm(`${bundle.origin}에서 수집한 ${bundle.captures.length}개 이벤트를 보관함에 가져올까요? 기존 설정은 유지됩니다.`)) return; const result = await importTransferBundle(bundle); window.dispatchEvent(new CustomEvent('pce:captures-changed')); services.notify(`전달 자료 보관 완료 · 신규 ${result.added}건 · 동일 이벤트 ${result.duplicate}건 유지. 데스크탑 DB 반영과는 별개입니다.`); } catch (error) { report(error); } }} /><p className="muted">전달 JSON의 설정 참조는 자동 덮어쓰지 않습니다. 수집 정책과 사전은 업무 탭에서 검토하고 저장하세요.</p></section>
    <section className="panel"><h2>프로토타입의 실행 범위</h2><ul><li>현재 출처: <code>{location.origin}</code></li><li>사이트별 IndexedDB 저장. 다른 사이트의 자료는 JSON으로 전달합니다.</li><li>업무 원본과 표 편집을 구분합니다. 표 변경은 저장으로 확정합니다.</li><li>지정 화면의 1회·자동 수집과 임시 추출은 각각 별도 동작입니다.</li><li>이 버전은 로컬 브라우저 프로토타입입니다. HWPX 구조 뷰어·앵커·치환을 제공합니다. 데스크탑 SQL·PC 파일 실행·PDF/OCR과 고급 문서 편집은 별도 구현 항목입니다.</li></ul><p className="muted">용량·장기 운영·실제 나라장터 권한 검증은 별도입니다. 다운로드한 백업은 브라우저 저장소 밖에서 보관할 수 있습니다.</p></section></div>;
}
export const settingsPlugin: BookmarkletPlugin = { id: 'prototype.settings', label: '설정·백업', features: ['backup', 'restore-preview', 'transfer-import'], component: SettingsPanel };
