import { useEffect, useMemo, useRef, useState } from 'react';
import type { ColumnDefinition, FilterGroup, TableRow } from '../../../packages/contracts/src/index';
import { DataGrid, type GridHandle } from '../../../plugins/grid/index';
import { exportSheet, ImportDialog, download } from '../../../plugins/files/index';
import { FilterEditor, emptyFilter, type Filter } from '../../../plugins/filter-ui/index';
import { aggregateDecimal, evaluateCalculation, getPath, isBlank, matchesFilter, validateFilter } from '../../../plugins/core/index';
import type { BookmarkletPlugin, LocalDocument, PrototypeDataset, PrototypeServices } from '../contracts';
import { listDocuments, putDocument, removeDocument } from '../storage';
import { createLocalDataset, makeRows, mergeVisibleRows, validateDataset } from '../dataset-model';

export function TablesPanel({ services }: { services: PrototypeServices }) {
  const [catalog, setCatalog] = useState<LocalDocument<PrototypeDataset>[]>([]);
  const [current, setCurrent] = useState<LocalDocument<PrototypeDataset> | null>(null);
  const [draft, setDraft] = useState<PrototypeDataset | null>(null);
  const [gridRows, setGridRows] = useState<TableRow[]>([]);
  const [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [importing, setImporting] = useState(false);
  const [filter, setFilter] = useState<Filter>(emptyFilter), [applied, setApplied] = useState<FilterGroup>();
  const [hideEmpty, setHideEmpty] = useState(true), [field, setField] = useState(''), [expression, setExpression] = useState('[단가] * [수량]');
  const [jsonField, setJsonField] = useState(''), [jsonPath, setJsonPath] = useState('');
  const [detail, setDetail] = useState<TableRow | null>(null), [advanced, setAdvanced] = useState(false);
  const grid = useRef<GridHandle | null>(null), draftRef = useRef(draft), dirtyRef = useRef(dirty);
  draftRef.current = draft; dirtyRef.current = dirty;
  const reportError = (error: unknown) => services.notify('실패: ' + (error instanceof Error ? error.message : String(error)));
  async function refresh() { try { setCatalog(await listDocuments<PrototypeDataset>('datasets')); } catch (error) { reportError(error); } }
  useEffect(() => { void refresh(); const listener = () => void refresh(); window.addEventListener('pce:datasets-changed', listener); return () => window.removeEventListener('pce:datasets-changed', listener); }, []);
  useEffect(() => { const closing = (event: Event) => { if (dirtyRef.current) event.preventDefault(); }; window.addEventListener('pce:close-check', closing); return () => window.removeEventListener('pce:close-check', closing); }, []);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirtyRef.current) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, []);
  const project = (rows: TableRow[], columns: ColumnDefinition[], targetFilter: FilterGroup | null | undefined = applied) => rows.filter(row => (!hideEmpty || columns.some(column => !isBlank(row[column.field]))) && matchesFilter(row, targetFilter ?? undefined));
  function open(document: LocalDocument<PrototypeDataset>) {
    if (dirty && !confirm('저장하지 않은 표 변경을 버리고 다른 표를 여시겠습니까?')) return;
    setCurrent(document); const copy = structuredClone(document.value); setDraft(copy); setGridRows(project(copy.rows, copy.columns, null)); setDirty(false); setFilter(emptyFilter()); setApplied(undefined); setDetail(null); services.select(null); setField(copy.columns[0]?.field ?? ''); setJsonField(copy.columns.find(column => column.kind === 'json')?.field ?? '');
  }
  function stage(next: PrototypeDataset, rebuild = true) { draftRef.current = next; setDraft(next); setDirty(true); if (rebuild) setGridRows(project(next.rows, next.columns)); }
  async function save() {
    if (!draft || !current) return;
    try { setBusy(true); validateDataset(draft); const next = { ...draft, rows: draft.rows.map(row => ({ ...row, __storeVersion: row.__storeVersion + 1 })) }; const saved = await putDocument('datasets', current.documentId, current.storeVersion, next); setCurrent(saved); setDraft(next); setDirty(false); await refresh(); services.notify('표 전체를 한 트랜잭션으로 저장했습니다.'); } catch (error) { reportError(error); } finally { setBusy(false); }
  }
  async function newTable() {
    if (dirty) { services.notify('새 표를 만들기 전에 현재 표를 저장하거나 변경을 취소하세요.'); return; }
    const name = prompt('새 독립 자료집 이름', '새 자료집'); if (!name?.trim()) return;
    try { const document = await createLocalDataset(name, [], [{ field: '제목', label: '제목', kind: 'text' }, { field: '내용', label: '내용', kind: 'text' }]); await refresh(); open(document); } catch (error) { reportError(error); }
  }
  const selectedValues = detail && jsonField ? getPath(detail[jsonField], jsonPath ? jsonPath.split('.') : []) : undefined;
  const columns = useMemo(() => draft?.columns ?? [], [draft?.columns]);
  return <div className="db-layout"><aside className="dataset-list"><div className="row"><strong>이 사이트의 DB</strong><button aria-label="자료집 목록 새로고침" onClick={refresh}>↻</button></div><button className="primary" onClick={newTable}>+ 새 자료집</button><button onClick={() => setImporting(true)}>파일·클립보드 가져오기</button><p className="muted">수집 원본은 업무 보관함에 남습니다. 여기서는 사용자가 저장한 독립 표를 편집합니다.</p>{['collected', 'reference'].map(category => <div key={category}><h3>{category === 'collected' ? '수집에서 만든 표' : '참고 자료집'}</h3>{catalog.filter(entry => entry.value.category === category).map(entry => <button className={entry.documentId === current?.documentId ? 'active' : ''} key={entry.documentId} onClick={() => open(entry)}>{entry.value.name}<small>{entry.value.rows.length}행</small></button>)}</div>)}</aside><div className="table-area">
    {!draft ? <div className="welcome"><span className="eyebrow">BROWSER DATABASE</span><h2>표로 시작하는 작은 업무 공간</h2><p>자료집을 만들거나 Excel·CSV를 가져오세요.<br/>업무 탭에서 추출한 표도 여기에 저장할 수 있습니다.</p><button className="primary" onClick={newTable}>새 자료집 만들기</button></div> : <>
      <header className="table-heading"><h2>{draft.name}</h2><span>{draft.rows.length}행 · {dirty ? '저장 전 변경 있음' : '저장됨'}</span><button className="primary" disabled={!dirty || busy} onClick={save}>표 저장</button><button disabled={!dirty || busy} onClick={() => { if (current && confirm('저장 전 변경을 취소하시겠습니까?')) { setDirty(false); const copy = structuredClone(current.value); setDraft(copy); setGridRows(project(copy.rows, copy.columns)); } }}>변경 취소</button></header>
      <div className="toolbar"><button onClick={() => stage({ ...draft, rows: [...draft.rows, ...makeRows([Object.fromEntries(columns.map(column => [column.field, '']))])] })}>+ 행</button><button onClick={() => grid.current?.remove()}>선택 행 삭제</button><button onClick={() => grid.current?.fillDown()}>아래로 채우기</button><button onClick={() => { const name = prompt('새 열 이름'); if (name?.trim()) { try { const next = { ...draft, columns: [...columns, { field: name.trim(), label: name.trim(), kind: 'text' as const }] }; validateDataset(next); stage(next); } catch (error) { reportError(error); } } }}>+ 열</button><button onClick={() => setImporting(true)}>가져오기</button><button onClick={() => services.navigate('relations')}>표 관계 설정</button><button onClick={() => exportSheet(draft.name, project(draft.rows, columns), columns, 'csv', false)}>CSV 출력</button><button onClick={() => exportSheet(draft.name, project(draft.rows, columns), columns, 'xlsx', false)}>XLSX 출력</button><button onClick={() => download(draft.name + '.json', JSON.stringify({ name: draft.name, columns, rows: project(draft.rows, columns).map(({ __rowId, __storeVersion, ...values }) => values) }, null, 2))}>표 JSON</button></div>
      <details className="filter-panel"><summary>필터 · 여러 검색값과 AND/OR</summary><label><input type="checkbox" checked={advanced} onChange={event => setAdvanced(event.target.checked)} />상세 그룹 편집</label><FilterEditor columns={columns} value={filter} onChange={setFilter} compact={!advanced} /><div className="row"><label><input type="checkbox" checked={hideEmpty} onChange={event => { setHideEmpty(event.target.checked); setGridRows(draft.rows.filter(row => (!event.target.checked || columns.some(column => !isBlank(row[column.field]))) && matchesFilter(row, applied))); }} />빈 행 숨김 · 원본 유지</label><button onClick={() => { try { validateFilter(filter as FilterGroup); setApplied(filter as FilterGroup); setGridRows(project(draft.rows, columns, filter as FilterGroup)); } catch (error) { reportError(error); } }}>필터 적용</button><button onClick={() => { setFilter(emptyFilter()); setApplied(undefined); setGridRows(project(draft.rows, columns, null)); }}>필터 초기화</button></div></details>
      <div className="table-grid"><DataGrid singleClickEdit rows={gridRows} columns={columns} handle={handle => grid.current = handle} onChange={(visible, deleted) => { const previous = draftRef.current; if (previous) stage({ ...previous, rows: mergeVisibleRows(previous.rows, visible as TableRow[], deleted) }, false); }} onSelect={row => { setDetail(row as TableRow); services.select({ datasetId: current!.documentId, datasetName: draft.name, rowId: String(row.__rowId), values: row }); }} /></div><p className="muted">표시 {gridRows.length}행 · 클릭 편집 · 드래그 범위 선택 · F2/문자 입력 · Enter 확정 · Tab 이동 · Esc 취소 · Ctrl+C/V · Delete 값 지우기</p>
      <details><summary>열 설정 · 계산 · 중복 제거</summary><div className="column-settings">{columns.map(column => <div className="row" key={column.field}><code>{column.field}</code><input aria-label={column.field + ' 표시명'} value={column.label} onChange={event => stage({ ...draft, columns: columns.map(entry => entry.field === column.field ? { ...entry, label: event.target.value } : entry) })} /><select aria-label={column.field + ' 자료형'} value={column.kind} onChange={event => stage({ ...draft, columns: columns.map(entry => entry.field === column.field ? { ...entry, kind: event.target.value as ColumnDefinition['kind'] } : entry) })}>{['text', 'code', 'integer', 'decimal', 'boolean', 'date', 'json'].map(kind => <option key={kind}>{kind}</option>)}</select></div>)}</div><div className="row"><select aria-label="계산 결과 열" value={field} onChange={event => setField(event.target.value)}>{columns.map(column => <option key={column.field} value={column.field}>{column.label}</option>)}</select><input aria-label="계산 수식" value={expression} onChange={event => setExpression(event.target.value)} /><button onClick={() => { try { const selected = new Set(grid.current?.selected().map(row => row.__rowId)); if (!selected.size) throw new Error('계산할 행을 선택하세요.'); const rows = draft.rows.map(row => selected.has(row.__rowId) ? { ...row, [field]: evaluateCalculation(expression, row) } : row); stage({ ...draft, rows }); services.notify('선택 행 계산 결과를 편집 버퍼에 적용했습니다.'); } catch (error) { reportError(error); } }}>선택 행 계산</button><button onClick={() => { try { services.notify(`${field} 합계 ${aggregateDecimal(grid.current?.rows().map(row => row[field]) ?? [], 'sum')} · 평균 ${aggregateDecimal(grid.current?.rows().map(row => row[field]) ?? [], 'average')}`); } catch (error) { reportError(error); } }}>표시 행 합계·평균</button><button onClick={() => { const keys = prompt('중복 판단 열을 쉼표로 입력', field)?.split(',').map(key => key.trim()).filter(Boolean); if (!keys?.length) return; if (keys.some(key => !columns.some(column => column.field === key))) { services.notify('중복 판단 열 이름을 확인하세요.'); return; } const seen = new Set<string>(); const rows = draft.rows.filter(row => { const key = JSON.stringify(keys.map(column => row[column])); if (seen.has(key)) return false; seen.add(key); return true; }); if (confirm(`${draft.rows.length - rows.length}개 중복 행을 편집 버퍼에서 제거할까요?`)) stage({ ...draft, rows }); }}>중복 미리보기·제거</button></div><button className="danger" onClick={async () => { if (!current || !confirm(`자료집 '${draft.name}' 전체를 삭제할까요? 수집 원본은 유지됩니다.`)) return; try { await removeDocument('datasets', current.documentId, current.storeVersion); setCurrent(null); setDraft(null); setDirty(false); services.select(null); await refresh(); } catch (error) { reportError(error); } }}>자료집 삭제</button></details>
      {detail && <details open><summary>선택 레코드 · JSON 상세 · 연결</summary><div className="row"><button onClick={() => services.navigate('notes')}>이 행의 메모·일정</button><button onClick={() => services.navigate('templates')}>텍스트 템플릿</button><select aria-label="JSON 상세 열" value={jsonField} onChange={event => setJsonField(event.target.value)}><option value="">열 선택</option>{columns.map(column => <option key={column.field} value={column.field}>{column.label}</option>)}</select><input aria-label="JSON 상세 경로" value={jsonPath} onChange={event => setJsonPath(event.target.value)} placeholder="JSON 경로 · a.b" /></div>{jsonField && <><pre>{selectedValues === undefined ? '(누락)' : JSON.stringify(selectedValues, null, 2)}</pre>{Array.isArray(selectedValues) && <div className="array-preview"><DataGrid rows={makeRows(selectedValues.map(value => value && typeof value === 'object' && !Array.isArray(value) ? value : { value }))} columns={[...new Set(selectedValues.flatMap(value => value && typeof value === 'object' && !Array.isArray(value) ? Object.keys(value) : ['value']))].map(key => ({ field: key, label: key }))} readOnly /></div>}</>}</details>}
    </>}
    {importing && <ImportDialog columns={columns} headerMap={{}} onClose={() => setImporting(false)} onApply={async (rows, importedColumns, asNew, name) => {
      if (asNew) { if (dirty) throw new Error('현재 표를 저장하거나 변경을 취소한 뒤 새 자료집으로 가져오세요.'); const next = await createLocalDataset(name, rows, importedColumns as ColumnDefinition[]); await refresh(); open(next); services.notify('가져온 자료를 독립 자료집으로 저장했습니다.'); }
      else { if (!draft) throw new Error('기존 표를 먼저 선택하세요.'); const additional = importedColumns.filter(column => !columns.some(previous => previous.field === column.field)) as ColumnDefinition[]; const next = { ...draft, columns: [...columns, ...additional], rows: [...draft.rows, ...makeRows(rows)] }; validateDataset(next); stage(next); services.notify('추가 열과 행을 편집 버퍼에 넣었습니다. 표 저장으로 확정하세요.'); }
    }} />}
  </div></div>;
}
export const tablesPlugin: BookmarkletPlugin = { id: 'prototype.tables', label: 'DB', features: ['local-datasets', 'grid', 'filter', 'import-export', 'json'], component: TablesPanel };
