import './style.css';
import * as XLSX from 'xlsx';
import { renderGrid } from './grid';
import { defaultScreenRules, extractCapture, extractionViews, loadJson } from './extractor';
import { rpc, captureCurrentPage, runLauncher } from './bridge';
import { RecordView } from './record-view';
import { collectorBridge, documentPayload } from './integrations';
import type { CollectionDecision, CollectionPreview, ExtractionResult, ExtractionView, GridRendererHandle, JsonRow, MvpSettings, ProcurementRecord, ProcurementStage } from './contracts';

const params = new URLSearchParams(location.search);
const mode = params.get('mode') || 'extract';
const tabId = Number(params.get('sourceTabId')) || undefined;
const native = typeof chrome !== 'undefined' && !!chrome.runtime?.id;
const stageLabels:Record<ProcurementStage,string> = {receipt:'접수',bid:'공고',contract:'계약'};
const defaultColumnTypes:NonNullable<MvpSettings['columnTypes']>={ctrtAmt:'money',ctrtDmndAmt:'money',dlvgdsTermYmd:'date',종결금액:'money',미종결금액:'money',선금보증금액:'money',지정일:'date',선금보증기한:'date'};
let settings:MvpSettings = {theme:'light',extractionMode:'tables',hideEmptyColumns:true,hideUnmappedColumns:false,dictionary:{keys:{ctrtNo:'계약번호',ctrtChgOrd:'변경차수',ctrtAmt:'계약금액',dlvgdsTermYmd:'납품기한',ctrtDmndRcptNo:'접수번호',ctrtDmndRcptOrd:'차수'},values:{}},launchers:[],shortcuts:{collect:'Alt+Shift+S',document:'Alt+Shift+D'},columnTypes:{종결금액:'money',미종결금액:'money',선금보증금액:'money',지정일:'date',선금보증기한:'date'}};
let settingsVersion=1, extraction:ExtractionResult|undefined, handle:GridRendererHandle|undefined;
let records:ProcurementRecord[]=[], stage:ProcurementStage='receipt', activeView:ExtractionView|undefined, dirty=false, userVisible=true, isDb=mode==='db';
let recordsRevision=0;
const temporaryBuffers=new Map<string,JsonRow[]>();
const temporaryColumns=new Map<string,string[]>();
let recordView:RecordView|undefined, userColumnDraft:string[]=[];
let settingsQueue:Promise<void>=Promise.resolve();
const demoStore=new Map<ProcurementStage,ProcurementRecord[]>(),demoTrash=new Map<ProcurementStage,ProcurementRecord[]>();
const root=document.querySelector<HTMLElement>('#app')!;
function node<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,cls?:string){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(label:string, action:()=>unknown){const b=node('button',label);b.type='button';b.onclick=()=>{Promise.resolve().then(action).catch(fail);};return b;}
function input(label:string, type='text'){const n=node('input');n.type=type;n.setAttribute('aria-label',label);return n;}
function select(label:string, choices:[string,string][], selected?:string){const n=node('select');n.setAttribute('aria-label',label);for(const [v,t]of choices){const o=node('option',t);o.value=v;n.append(o);}if(selected)n.value=selected;return n;}
const shell=node('section',undefined,'shell'), title=node('header',undefined,'titlebar'), toolbar=node('div',undefined,'toolbar actionbar'), filters=node('div',undefined,'date-controls'), tabs=node('nav',undefined,'tabs'), area=node('div',undefined,'grid-area'), status=node('div',undefined,'status');
const heading=node('strong',mode==='db'?'DB':mode==='collect'?'수집':mode==='document'?'문서 연결':mode==='launcher'?'런처':'추출');
function message(text:string,error=false){const detail=text.replace(/\s*\n\s*/g,' ');status.title=detail;status.textContent=/top URL|출처|origin/i.test(detail)?'출처 미확인 · 추출만 가능합니다.':detail.length>64?detail.slice(0,61)+'…':detail;status.classList.toggle('error',error);}
function fail(error:unknown){message(error instanceof Error?error.message:String(error),true);}
function close(){if(window.parent!==window){window.parent.postMessage({kind:'mvp.close'},'*');}else window.close();}
function sourceKey(key:string){return [...(recordView?.userNames||[])].find(([,alias])=>alias===key)?.[0]||key;}
function gridSettings(){const value=structuredClone(settings);if(isDb&&recordView)for(const[key,alias]of recordView.userNames){if(alias===key)continue;if(value.columnTypes?.[key])(value.columnTypes??={})[alias]=value.columnTypes[key];if(value.columnLocks?.[key]===true)(value.columnLocks??={})[alias]=true;if(Object.hasOwn(value.dictionary.keys,key))value.dictionary.keys[alias]=value.dictionary.keys[key];}return value;}
function theme(){document.documentElement.dataset.theme=settings.theme;handle?.setSettings(gridSettings());window.parent.postMessage({kind:'mvp.settings',settings:{theme:settings.theme,shortcuts:settings.shortcuts,launchers:settings.launchers,screenRules:settings.screenRules}},'*');}
const settingsButton=button('설정',()=>showSettings());title.append(heading,node('span',native?'':'샘플','demo-mark'),node('span',undefined,'spacer'),settingsButton,button('닫기',close));
let dragPointer:number|undefined;
title.addEventListener('pointerdown',e=>{if(e.button!==0||(e.target as Element).closest('button,input,select'))return;dragPointer=e.pointerId;title.setPointerCapture(e.pointerId);window.parent.postMessage({kind:'mvp.drag',phase:'start',screenX:e.screenX,screenY:e.screenY},'*');});
title.addEventListener('pointermove',e=>{if(dragPointer===e.pointerId)window.parent.postMessage({kind:'mvp.drag',phase:'move',screenX:e.screenX,screenY:e.screenY},'*');});
for(const event of ['pointerup','pointercancel']as const)title.addEventListener(event,e=>{if(dragPointer!==e.pointerId)return;dragPointer=undefined;window.parent.postMessage({kind:'mvp.drag',phase:'end',screenX:e.screenX,screenY:e.screenY},'*');});
shell.append(title,toolbar,tabs,area,status);root.append(shell);
function download(value:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type}));const a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function dialog(label:string){const d=node('dialog',undefined,'dialog');const head=node('header',undefined,'titlebar');head.append(node('strong',label),node('span',undefined,'spacer'),button('닫기',()=>d.close()));const body=node('div',undefined,'dialog-body');d.append(head,body);document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();return{d,body};}
function rawDialog(value:unknown){const {body}=dialog('원본 JSON');const text=typeof value==='string'?value:JSON.stringify(value,null,2);body.append(button('JSON 저장',()=>download(text,'g2b-raw.json')),node('pre',text,'raw-view'));}
function nested(label:string, rows:JsonRow[]){const {d,body}=dialog(label);const host=node('div',undefined,'grid-area');body.append(host);const grid=renderGrid(host,{label,rows,settings,onNested:(_row,key,nestedRows)=>nestedView(key,nestedRows)});d.addEventListener('close',()=>grid.destroy());}
function nestedView(key:string,rows:JsonRow[]){nested(key,rows);}
function saveSettings(){const snapshot=structuredClone(settings);const operation=settingsQueue.catch(()=>{}).then(async()=>{if(native){const saved=await rpc<{settings:MvpSettings;storeVersion:number}>('mvp.settings.save',{settings:snapshot,storeVersion:settingsVersion});settingsVersion=saved.storeVersion;}theme();});settingsQueue=operation;return operation;}
function autosave(){theme();void saveSettings().catch(fail);}
const search=input('검색');search.className='search';search.placeholder='검색';search.oninput=()=>handle?.setSearch(search.value);
const save=button('저장',()=>saveRows());save.disabled=true;
const importFile=input('JSON 열기','file');importFile.accept='.json,.txt';importFile.hidden=true;importFile.onchange=async()=>{const file=importFile.files?.[0];if(file){if(dirty&&isDb&&!confirm('저장하지 않은 입력을 닫을까요?'))return;extraction=loadJson(await file.text());temporaryBuffers.clear();temporaryColumns.clear();showExtraction();}importFile.value='';};
const hiddenUser=button('사용자 열 숨김',()=>{userVisible=!userVisible;handle?.setUserColumnsVisible(userVisible);hiddenUser.classList.toggle('active',!userVisible);hiddenUser.setAttribute('aria-pressed',String(!userVisible));});hiddenUser.setAttribute('aria-pressed','false');hiddenUser.title='사용자 열 표시 여부를 전환합니다.';
const finishSelected=button('종결',()=>handle?.toggleSelectedBoolean(recordView?.completionKey||'종결'));finishSelected.hidden=true;
const tabList=node('div',undefined,'tab-list'),tabActions=node('div',undefined,'tab-actions');tabActions.append(hiddenUser,finishSelected,search);tabs.append(tabList,tabActions);
const exports=node('div',undefined,'export-actions');exports.append(button('원본 JSON',()=>rawDialog(isDb?records.map(r=>({recordId:r.recordId,rawJson:r.rawJson})):extraction?.raw||{})),button('JSON',()=>download(JSON.stringify(exportJson(),null,2),'g2b-tables.json')),button('CSV',()=>{const rows=(handle?.rows()||[]).map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,value!==null&&typeof value==='object'?JSON.stringify(value):value])));download(XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows)),'g2b-table.csv','text/csv;charset=utf-8');}),button('Excel',()=>handle?.exportExcel('g2b-table.xlsx')),save,importFile);toolbar.append(filters,exports);
function exportJson(){if(isDb)return handle?.rows()||[];if(!extraction)return{};const tables=Object.fromEntries(extractionViews(extraction,'tables').map(v=>[v.key,temporaryBuffers.get(v.key)||v.rows]));if(settings.extractionMode==='all'){const points=extractionViews(extraction,'all').filter(v=>!Object.hasOwn(tables,v.key));return{pointInfo:points.length===1?(temporaryBuffers.get(points[0].key)||points[0].rows)[0]||{}:Object.fromEntries(points.map(v=>[v.key,(temporaryBuffers.get(v.key)||v.rows)[0]||{}])),tables};}return{tables};}
const start=input('시작일'),end=input('종료일');start.className=end.className='date-field';start.placeholder=end.placeholder='YYYY.MM.DD';
const today=new Date();end.value=dateText(today);const initial=new Date(today);initial.setMonth(initial.getMonth()-3);start.value=dateText(initial);
const dateKey=select('날짜 기준',[['','전체']]);const completion=select('종결 필터',[['all','전체'],['open','미종결'],['closed','종결']]);
function dateText(d:Date){return `${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`;}
function parseDate(value:unknown){const s=String(value??'');const m=/^(\d{4})[.-]?(\d{2})[.-]?(\d{2})(?:$|T|\s)/.exec(s);if(!m)return undefined;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));return d.getFullYear()===+m[1]&&d.getMonth()===+m[2]-1&&d.getDate()===+m[3]?d:undefined;}
function shiftYears(amount:number){if(dirty){message('먼저 입력을 저장하세요.');return;}const d=parseDate(start.value);if(!d)throw new Error('날짜를 YYYY.MM.DD로 입력하세요.');const year=d.getFullYear()+amount;start.value=`${year}.01.01`;end.value=`${year}.12.31`;applyDates();}
filters.append(start,node('span','~'),end,button('−1년',()=>shiftYears(-1)),button('+1년',()=>shiftYears(1)),dateKey,completion);
for(const control of[start,end,dateKey,completion])control.onchange=()=>{if(dirty){message('먼저 입력을 저장하세요.');return;}if((control===start||control===end)&&(!parseDate(start.value)||!parseDate(end.value))){message('날짜를 YYYY.MM.DD로 입력하세요.',true);return;}applyDates();};
function dateChoices(rows:JsonRow[]){const current=dateKey.value;dateKey.replaceChildren(new Option('전체',''));const keys=[...new Set(rows.flatMap(row=>Object.keys(row)))].filter(key=>rows.some(row=>!!parseDate(row[key])));for(const key of keys)dateKey.append(new Option(settings.dictionary.keys[key]||key,key));dateKey.value=keys.includes(current)?current:'';}
function applyDates(){if(isDb){showRecords();return;}const begin=parseDate(start.value),finish=parseDate(end.value);if(dateKey.value&&(!begin||!finish||begin>finish)){message('날짜 구간을 확인하세요.',true);return;}const key=dateKey.value;handle?.setRowFilter(key?row=>{const date=parseDate(row[key]);return !!date&&date>=begin!&&date<=finish!;}:undefined);}
function destroyGrid(){handle?.destroy();handle=undefined;area.replaceChildren();}
function showGrid(view:ExtractionView, options:{userKeys?:string[];readonlyKeys?:string[]}={}){
 destroyGrid();activeView=view;dirty=false;save.disabled=true;save.hidden=!isDb;search.value='';
 handle=renderGrid(area,{label:view.label,rows:view.rows,settings:gridSettings(),userColumnKeys:options.userKeys,itemColumnKeys:isDb&&recordView?[...new Set(records.flatMap(r=>r.children.filter(c=>c.kind==='items').map(c=>recordView!.childNames.get(c.key)!).filter(Boolean)))]:undefined,readOnlyColumnKeys:options.readonlyKeys,allowRowDelete:true,onNotice:text=>message(text,true),
  onRowsChanged:(rows)=>{if(!isDb){temporaryBuffers.set(view.key,rows);return;}dirty=true;save.disabled=!native;if(stage==='contract'&&recordView)handle?.updateDerivedValues(row=>recordView!.derive(row));},onUserColumnsChanged:(keys)=>{if(!isDb){temporaryColumns.set(view.key,keys);return;}userColumnDraft=recordView!.definitionNames(keys);dirty=true;save.disabled=!native;},onColumnRename:(key,label)=>{settings.dictionary.keys={...settings.dictionary.keys,[isDb?sourceKey(key):key]:label};autosave();},onColumnType:(key,type)=>{settings.columnTypes={...settings.columnTypes,[isDb?sourceKey(key):key]:type};autosave();},onColumnLock:(key,locked)=>{settings.columnLocks={...settings.columnLocks,[isDb?sourceKey(key):key]:locked};autosave();},onValueDictionary:(key,value)=>valueDictionary(isDb?sourceKey(key):key,value),...(isDb?{onDeleteRows:(_rows:JsonRow[],indices:number[])=>{void trashRows(indices).catch(fail);}}:{}),onNested:(_row,key,rows)=>nestedView(key,rows)});
 handle.setUserColumnsVisible(userVisible);
}
function showExtraction(){if(!extraction)return;isDb=false;recordView=undefined;finishSelected.hidden=completion.hidden=true;filters.hidden=false;heading.textContent='추출';tabList.replaceChildren();const views=extractionViews(extraction,settings.extractionMode).filter(v=>!settings.hideEmptyTables||(temporaryBuffers.get(v.key)||v.rows).length>0);const show=(view:ExtractionView)=>{const rows=temporaryBuffers.get(view.key)||view.rows;dateChoices(rows);showGrid({...view,rows},{userKeys:temporaryColumns.get(view.key)});applyDates();};for(const view of views){const b=button(view.label,()=>{show(view);for(const tab of tabList.children)tab.classList.toggle('active',tab===b);});tabList.append(b);}if(views[0]){show(views[0]);tabList.firstElementChild?.classList.add('active');}else{dateChoices([]);destroyGrid();save.hidden=true;area.append(node('p','표가 없습니다.','empty'));}message(extraction.warnings.join(' · '));}
function recordRow(record:ProcurementRecord){return recordView!.toRow(record);}
function showRecords(){if(dirty){message('입력을 저장한 뒤 필터를 변경하세요.');return;}isDb=true;completion.hidden=finishSelected.hidden=stage!=='contract';const begin=parseDate(start.value),finish=parseDate(end.value);if(dateKey.value&&(!begin||!finish||begin>finish)){message('날짜 구간을 확인하세요.',true);return;}
 const filtered=records.filter(r=>{if(stage==='contract'&&completion.value!=='all'&&Boolean(r.userValues['종결'])!==(completion.value==='closed'))return false;if(dateKey.value){const d=parseDate(r.fields[dateKey.value]);return !!d&&d>=begin!&&d<=finish!;}return true;});
 showGrid({key:stage,label:stageLabels[stage],stage,rows:filtered.map(recordRow)},{userKeys:recordView!.userKeys,readonlyKeys:recordView!.readonlyKeys});
 area.dataset.recordIds=JSON.stringify(filtered.map(r=>r.recordId));message('');
}
async function loadRecords(next:ProcurementStage=stage){if(dirty&&!confirm('저장하지 않은 입력을 닫을까요?'))return;const revision=++recordsRevision;area.inert=true;area.setAttribute('aria-busy','true');save.disabled=true;message('불러오는 중…');try{const loaded=native?await rpc<ProcurementRecord[]>('mvp.records',{stage:next}):demoStore.get(next)||demoRecords(next);if(revision!==recordsRevision)return;stage=next;records=loaded;if(!native)demoStore.set(stage,records);dirty=false;isDb=true;heading.textContent='DB';filters.hidden=false;
 recordView=new RecordView(records,stage,settings);userColumnDraft=recordView.definitionNames(recordView.userKeys);
 const current=dateKey.value;dateKey.replaceChildren(new Option('전체',''));const keys=[...new Set(records.flatMap(r=>Object.keys(r.fields)))];for(const key of keys.filter(k=>records.some(r=>!!parseDate(r.fields[k])))){dateKey.append(new Option(settings.dictionary.keys[key]||key,key));}dateKey.value=keys.includes(current)?current:'';
 tabList.replaceChildren();for(const [key,label]of Object.entries(stageLabels)){const b=button(label,()=>loadRecords(key as ProcurementStage));b.classList.toggle('active',key===stage);tabList.append(b);}showRecords();}catch(error){if(revision===recordsRevision)throw error;}finally{if(revision===recordsRevision){area.inert=false;area.setAttribute('aria-busy','false');save.disabled=!dirty||!native;}}
}
async function saveRows(){if(!isDb||!native)return;await settingsQueue;const ids=JSON.parse(area.dataset.recordIds||'[]') as string[];const rows=handle?.rows()||[];if(rows.length!==ids.length)throw new Error('업무 행 추가는 현재 지원하지 않습니다. 입력을 유지합니다.');
 const changes=rows.map((row,index)=>recordView!.toEdit(records.find(r=>r.recordId===ids[index])!,row));
 await rpc('mvp.edit',{records:changes,userColumns:{stage,keys:userColumnDraft,settingsStoreVersion:settingsVersion}});(settings.userColumns??={})[stage]=userColumnDraft;settingsVersion++;dirty=false;await loadRecords();message('저장됨');
}
async function collect(){if(!extraction)extraction=extractCapture(await captureCurrentPage(tabId),undefined,settings.screenRules);if(!extraction.observations.length){const text=extraction.warnings.join(' · ')||'등록 화면과 업무키를 확인하세요.';if(window.parent!==window){window.parent.postMessage({kind:'mvp.notice',message:text,error:true},'*');close();return;}message(text,true);return;}
 let preview=await rpc<CollectionPreview>('mvp.preview',{observations:extraction.observations});
 const choices:CollectionDecision[]=[];
 if(preview.conflicts.length){const {d,body}=dialog('값 변경');const checks=new Map<string,HTMLInputElement>();for(const conflict of preview.conflicts){const line=node('div',undefined,'diff');const check=input('신규값 반영','checkbox');checks.set(conflict.recordId+'\0'+conflict.field,check);line.append(check,node('span',settings.dictionary.keys[conflict.field]||conflict.field),node('pre',JSON.stringify(conflict.previous)),node('pre',JSON.stringify(conflict.incoming)));body.append(line);}await new Promise<void>(resolve=>{body.append(button('반영',()=>{for(const c of preview.conflicts)choices.push({recordId:c.recordId,field:c.field,useIncoming:checks.get(c.recordId+'\0'+c.field)!.checked});d.returnValue='apply';d.close();resolve();}));d.addEventListener('close',()=>resolve(),{once:true});});if(d.returnValue!=='apply')return;}
 await rpc('mvp.apply',{observations:preview.observations,token:preview.token,decisions:choices});await collectorBridge.sendCollectedData(preview.observations);stage=preview.observations[0].stage;location.search=`mode=db&sourceTabId=${tabId||''}&stage=${stage}`;
}
async function trashRows(indices:number[]){if(dirty){message('입력을 저장한 뒤 휴지통으로 이동하세요.');return;}const ids=JSON.parse(area.dataset.recordIds||'[]')as string[];const selected=[...new Set(indices)].map(index=>records.find(r=>r.recordId===ids[index])).filter((r):r is ProcurementRecord=>!!r);if(!selected.length)return;if(native)await rpc('mvp.trash',{records:selected.map(r=>({recordId:r.recordId,storeVersion:r.storeVersion}))});else{demoTrash.set(stage,[...(demoTrash.get(stage)||[]),...selected.map(r=>({...r,storeVersion:r.storeVersion+1}))]);demoStore.set(stage,records.filter(r=>!selected.some(s=>s.recordId===r.recordId)));}await loadRecords();message(`${selected.length}개 행을 휴지통으로 이동했습니다.`);}
async function showTrash(){if(dirty){message('입력을 저장한 뒤 휴지통을 여세요.');return;}const trashed=native?await rpc<ProcurementRecord[]>('mvp.records',{stage,trashed:true}):demoTrash.get(stage)||[];const{d,body}=dialog(stageLabels[stage]+' 휴지통');body.classList.add('trash-list');if(!trashed.length){body.append(node('p','휴지통이 비어 있습니다.','empty'));return;}for(const record of trashed){const line=node('div',undefined,'trash-row'),label=node('span',record.identity.join(' · '));label.title=label.textContent||'';line.append(label,button('복원',async()=>{if(native)await rpc('mvp.restore',{records:[{recordId:record.recordId,storeVersion:record.storeVersion}]});else{demoTrash.set(stage,(demoTrash.get(stage)||[]).filter(r=>r.recordId!==record.recordId));demoStore.set(stage,[...(demoStore.get(stage)||[]),{...record,storeVersion:record.storeVersion+1}]);}d.close();await loadRecords();message('행을 복원했습니다.');}));body.append(line);}}
function setDictionaryValue(key:string,value:string,label:string){const values=settings.dictionary.values;settings.dictionary.values={...values,[key]:{...(Object.hasOwn(values,key)?values[key]:{}),[value]:label}};}
function valueDictionary(key:string,value:unknown){const{d,body}=dialog('값 사전 추가'),code=input('원값'),label=input('표시값');code.value=value!==null&&typeof value==='object'?JSON.stringify(value):String(value??'');const line=node('div',undefined,'value-editor');line.append(node('span',key||'(빈 키)'),code,label);body.append(line,button('저장',async()=>{setDictionaryValue(key,code.value,label.value);await saveSettings();handle?.setSettings(gridSettings());d.close();}));label.focus();}
function dictionary(body:HTMLElement,kind:'keys'|'values'){
 const table=node('table',undefined,'dictionary-grid '+kind),header=node('tr');for(const text of kind==='keys'?['원본 키','표시명','유형','입력 잠금','']:['원본 키','원값','표시값',''])header.append(node('th',text));table.append(header);
 const entries=kind==='keys'?[...new Set([...Object.keys(settings.dictionary.keys),...Object.keys(settings.columnTypes||{}),...Object.keys(settings.columnLocks||{})])].map(key=>[key,'',settings.dictionary.keys[key]||'']):Object.entries(settings.dictionary.values).flatMap(([key,values])=>Object.entries(values).map(([value,label])=>[key,value,label]));
 for(const[key,value,label]of entries){const row=node('tr'),edit=input('표시명');edit.value=label;edit.onchange=()=>{if(kind==='keys')settings.dictionary.keys={...settings.dictionary.keys,[key]:edit.value};else setDictionaryValue(key,value,edit.value);};for(const text of kind==='keys'?[key]:[key,value])row.append(node('td',text));const cell=node('td');cell.append(edit);row.append(cell);if(kind==='keys'){const typeCell=node('td'),lockCell=node('td'),type=select('유형 '+key,[['text','텍스트'],['money','금액'],['date','날짜']],settings.columnTypes?.[key]||'text'),lock=input('입력 잠금 '+key,'checkbox');type.onchange=()=>{settings.columnTypes={...settings.columnTypes,[key]:type.value as 'text'|'money'|'date'};};lock.checked=settings.columnLocks?.[key]===true;lock.onchange=()=>{settings.columnLocks={...settings.columnLocks,[key]:lock.checked};};typeCell.append(type);lockCell.append(lock);row.append(typeCell,lockCell);}const remove=node('td');remove.append(button('삭제',()=>{if(kind==='keys'){delete settings.dictionary.keys[key];delete settings.columnTypes?.[key];delete settings.columnLocks?.[key];}else delete settings.dictionary.values[key][value];row.remove();}));row.append(remove);table.append(row);}
 const row=node('tr',undefined,'dictionary-add'),key=input('원본 키'),value=input('원값'),label=input(kind==='keys'?'표시명':'표시값');const cell=(child:HTMLElement)=>{const td=node('td');td.append(child);row.append(td);};cell(key);if(kind==='values')cell(value);cell(label);let type:HTMLSelectElement|undefined,lock:HTMLInputElement|undefined;if(kind==='keys'){type=select('새 열 유형',[['text','텍스트'],['money','금액'],['date','날짜']]);lock=input('새 열 입력 잠금','checkbox');cell(type);cell(lock);}cell(button('추가',()=>{if(!key.value.trim())throw new Error('원본 키를 입력하세요.');if(kind==='keys'){settings.dictionary.keys={...settings.dictionary.keys,[key.value]:label.value};settings.columnTypes={...settings.columnTypes,[key.value]:type!.value as 'text'|'money'|'date'};settings.columnLocks={...settings.columnLocks,[key.value]:lock!.checked};}else setDictionaryValue(key.value,value.value,label.value);body.replaceChildren();dictionary(body,kind);}));table.append(row);body.append(table);
}
function screenRulesEditor(content:HTMLElement){
 const defaultCheck=input('기본 수집 화면 사용','checkbox');defaultCheck.checked=settings.screenRules===undefined;const label=node('label');label.append(defaultCheck,'기본 수집 화면 사용');content.append(label);const list=node('div',undefined,'screen-rules');content.append(list);
 const render=()=>{list.replaceChildren();const defaults=settings.screenRules===undefined,rules=defaults?structuredClone(defaultScreenRules):settings.screenRules!;const table=node('table',undefined,'dictionary-grid screen-grid'),head=node('tr');for(const text of['업무','URL','areaCd','depth1','depth2','depth3',''])head.append(node('th',text));table.append(head);for(const rule of rules){const row=node('tr'),stageField=select('수집 업무',Object.entries(stageLabels)as[string,string][],rule.stage);stageField.disabled=defaults;stageField.onchange=()=>rule.stage=stageField.value as ProcurementStage;const td=node('td');td.append(stageField);row.append(td);for(const key of['urlPattern','areaCd','depth1','depth2','depth3']as const){const field=input(key==='urlPattern'?'수집 URL':key);field.value=rule[key]||'';field.disabled=defaults;field.oninput=()=>rule[key]=field.value;const cell=node('td');cell.append(field);row.append(cell);}const remove=node('td'),b=button('삭제',()=>{settings.screenRules=rules.filter(r=>r.id!==rule.id);render();});b.disabled=defaults;remove.append(b);row.append(remove);table.append(row);}list.append(table);const add=button('조건 추가',()=>{(settings.screenRules??=[]).push({id:crypto.randomUUID(),stage:'receipt',urlPattern:'https://www.g2b.go.kr/*',areaCd:'',depth1:'',depth2:'',depth3:''});render();});add.disabled=defaults;list.append(add,node('p',defaults?'기본 등록 화면과 원천 업무키를 확인합니다.':'URL의 *는 임의 문자열, 비어 있는 depth3는 모든 값에 일치합니다.','demo-mark'));};
 defaultCheck.onchange=()=>{if(defaultCheck.checked)delete settings.screenRules;else settings.screenRules=structuredClone(defaultScreenRules);render();};render();
}
function generalSettings(content:HTMLElement,d:HTMLDialogElement){
 const themeSelect=select('테마',[['light','화이트'],['dark','블랙']],settings.theme);themeSelect.onchange=()=>{settings.theme=themeSelect.value as 'light'|'dark';theme();};const extractionMode=select('추출 범위',[['tables','테이블만'],['all','전체']],settings.extractionMode);extractionMode.onchange=()=>settings.extractionMode=extractionMode.value as 'tables'|'all';content.append(node('div','테마','settings-line'),themeSelect,node('div','추출','settings-line'),extractionMode);
 for(const [key,label]of [['hideEmptyColumns','빈 열 숨김'],['hideUnmappedColumns','사전 미등록 열 숨김'],['hideEmptyTables','빈 테이블 숨김']]as const){const check=input(label,'checkbox');check.checked=!!settings[key];check.onchange=()=>{settings[key]=check.checked;theme();};const l=node('label');l.append(check,label);content.append(node('div',undefined,'settings-line').appendChild(l));}
 const trash=button('휴지통',()=>{d.close();return showTrash();});trash.disabled=!isDb;trash.title=isDb?'현재 업무의 삭제된 행을 복원합니다.':'DB 화면에서 사용할 수 있습니다.';content.append(node('div','데이터','settings-line'),trash);
}
function showSettings(){const original=structuredClone(settings);const {d,body}=dialog('설정'), navigation=node('nav',undefined,'tabs'), content=node('div',undefined,'settings-content'),footer=node('div',undefined,'toolbar');body.append(navigation,content,footer);
 const views:{label:string;render:()=>void}[]=[{label:'일반',render:()=>generalSettings(content,d)},{label:'키 사전',render:()=>dictionary(content,'keys')},{label:'값 사전',render:()=>dictionary(content,'values')},{label:'수집 화면',render:()=>screenRulesEditor(content)},{label:'단축키',render:()=>{for(const [action,label]of [['collect','수집'],['extract','추출'],['db','DB'],['document','문서 연결'],['launcher','런처']]){const line=node('div',undefined,'shortcut-line'),field=input(label);field.value=settings.shortcuts?.[action as keyof NonNullable<MvpSettings['shortcuts']>]||'';field.readOnly=true;field.placeholder='여기서 키를 누르세요';field.onkeydown=e=>{if(e.key==='Tab')return;e.preventDefault();if(e.key==='Escape')return;if(e.key==='Backspace'||e.key==='Delete')field.value='';else if(!['Alt','Shift','Control','Meta'].includes(e.key))field.value=[e.ctrlKey?'Ctrl':'',e.altKey?'Alt':'',e.shiftKey?'Shift':'',e.metaKey?'Meta':'',e.key.toUpperCase()].filter(Boolean).join('+');(settings.shortcuts??={})[action as keyof NonNullable<MvpSettings['shortcuts']>]=field.value;};line.append(node('span',label),field);content.append(line);}content.append(node('p','브라우저 전체 단축키: 확장 프로그램 → 단축키','demo-mark'));}}];
 for(const view of views)navigation.append(button(view.label,()=>{content.replaceChildren();view.render();}));views[0].render();let accepted=false;footer.append(node('span',undefined,'spacer'),button('저장',async()=>{await saveSettings();accepted=true;d.close();if(extraction&&mode!=='db')showExtraction();}));d.addEventListener('close',()=>{if(!accepted){settings=original;theme();}});
}
function showLauncher(){
 destroyGrid();settingsButton.hidden=toolbar.hidden=filters.hidden=tabs.hidden=true;shell.classList.add('launcher-shell');heading.textContent='런처 추가';const label=input('버튼 이름'),script=node('textarea');label.placeholder='버튼 이름';script.placeholder='JavaScript';script.setAttribute('aria-label','JavaScript');const editor=node('div',undefined,'launcher-editor');
 const add=button('저장',async()=>{if(add.disabled)return;if(!label.value.trim()||!script.value.trim())throw new Error('이름과 스크립트를 입력하세요.');const launcher={id:crypto.randomUUID(),label:label.value.trim(),script:script.value};add.disabled=true;settings.launchers=[...settings.launchers,launcher];try{await saveSettings();label.value=script.value='';message('버튼 추가됨');}catch(error){settings.launchers=settings.launchers.filter(item=>item.id!==launcher.id);theme();throw error;}finally{add.disabled=false;}});add.classList.add('primary');editor.append(label,script,add);area.append(editor);
}
function documentBridge(){destroyGrid();toolbar.hidden=filters.hidden=tabs.hidden=true;heading.textContent='문서 연결';const source=extraction?.raw||records;area.append(button('JSON 전달 파일',()=>download(JSON.stringify(documentPayload(source),null,2),'document-input.json')));}
function demoRecords(type:ProcurementStage):ProcurementRecord[]{const identityKeys={receipt:['ctrtDmndRcptNo','ctrtDmndRcptOrd'],bid:['bidPbancNo','bidPbancOrd'],contract:['ctrtNo','ctrtChgOrd']}[type];return Array.from({length:24},(_,i)=>({stage:type,identity:[`SAMPLE-${String(i+1).padStart(3,'0')}`,'01'],recordId:'sample-'+i,storeVersion:1,fields:{[identityKeys[0]]:`SAMPLE-${String(i+1).padStart(3,'0')}`,[identityKeys[1]]:'01',사업명:'회의실 물품 구매 '+(i+1),수량:i===0?0:i,완료:false,ctrtAmt:'35608652.5',ctrtDt:dateText(today).replaceAll('.',''),dlvgdsTermYmd:'20261027',빈열:'',비고:{검토:['규격','수량']}},children:[{key:'items',label:'물품',kind:'items',rows:[{품명:'복합기',수량:1,단가:'35608652.5'}]}],source:{url:'https://www.g2b.go.kr/',areaCd:'14',depth1:'01570',depth2:'01571',framePath:'top'},rawJson:'{"sample":true}',capturedAt:'2026-10-01T00:00:00Z',userValues:type==='contract'?{종결:i===2,지정일:'20261101',종결금액:'1000',선금보증기한:'',선금보증금액:''}:{담당:'예시'}}));}
async function boot(){if(native){try{const response=await rpc<{settings:MvpSettings;storeVersion:number}>('mvp.settings.read',{});settings=response.settings;settingsVersion=response.storeVersion;}catch(error){fail(error);}}settings.columnTypes={...defaultColumnTypes,...settings.columnTypes};theme();
 if(mode==='db'){stage=(params.get('stage')||'receipt') as ProcurementStage;if(!Object.hasOwn(stageLabels,stage))stage='receipt';await loadRecords(stage);}
 else if(mode==='launcher')showLauncher();else if(mode==='settings')showSettings();else{const contractDemo=demoRecords('contract'),demoView=new RecordView(contractDemo,'contract',settings);extraction=native?extractCapture(await captureCurrentPage(tabId),undefined,settings.screenRules):extractCapture({pointInfo:{areaCd:'14',depth1:'01570',depth2:'01571',depth3:'01579'},tables:{접수목록:demoRecords('receipt').map(r=>r.fields),계약목록:contractDemo.map(r=>demoView.toRow(r)),빈표:[]}},undefined,settings.screenRules);if(mode==='collect')await collect();else{showExtraction();if(mode==='document')documentBridge();}}}
window.addEventListener('keydown',event=>{if(event.key==='Escape'&&!event.defaultPrevented&&!document.querySelector('dialog[open]')){event.preventDefault();close();}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
void boot().catch(fail);
